// Investigations: start from a template, work the bench, synthesise.
import { chromium } from "@playwright/test";
import fs from "node:fs";
import { idbCounts } from "./idb.mjs";

fs.mkdirSync("/tmp/shots/rooms", { recursive: true });
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push("PAGEERROR " + e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 200)); });
await page.goto("http://localhost:3000/enter?skip=1&name=Ismail", { waitUntil: "networkidle" });
await page.goto("http://localhost:3000/investigations", { waitUntil: "networkidle" });
await page.screenshot({ path: "/tmp/shots/rooms/inv-empty.png" });
await page.goto("http://localhost:3000/investigations?template=inv-why-empires-fall", { waitUntil: "networkidle" });
await page.waitForURL(/\/investigations\/inv_/);
await page.waitForSelector("text=Claims");
const out = {};
out.claims = await page.locator("section[aria-label=Claims] li").count();
await page.getByLabel("A claim you are considering").fill("Rome's western provinces were already de-urbanising before 400.");
await page.keyboard.press("Enter");
await page.waitForTimeout(300);
out.claimsAfter = await page.locator("section[aria-label=Claims] li").count();
await page.getByLabel("The strongest case against").fill("De-urbanisation shows up in the archaeology only where we have dug.");
await page.keyboard.press("Enter");
await page.getByPlaceholder("What you read, what you noticed, what changed.").fill("Read Ward-Perkins on pottery: the material record is the strongest argument for a real fall.");
await page.getByRole("button", { name: "Add note" }).click();
await page.getByRole("button", { name: "Devil's advocate" }).click();
await page.waitForSelector("text=Added to open questions");
out.openQuestions = await page.locator("section[aria-label='Open questions'] li").count();
await page.getByPlaceholder("One paragraph. What you believe now and why.").fill("Internal fragmentation did most of the work; external pressure set the timing.");
await page.getByRole("button", { name: "80", exact: true }).click();
await page.getByRole("button", { name: "Record position" }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/tmp/shots/rooms/inv-workbench.png", fullPage: true });
await page.reload({ waitUntil: "networkidle" });
await page.waitForSelector("text=Claims");
out.positionPersisted = (await page.getByPlaceholder("One paragraph. What you believe now and why.").inputValue()).slice(0, 40);
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(300);
await page.screenshot({ path: "/tmp/shots/rooms/inv-workbench-mobile.png" });
await page.setViewportSize({ width: 1280, height: 900 });
await page.getByRole("link", { name: /Write the synthesis/ }).click();
await page.waitForURL(/synthesis/);
await page.getByLabel("What the evidence supports").fill("Fiscal strain preceded every major contraction, but the Eastern Empire survived the same strain for a thousand years, so it cannot be sufficient. The archaeology of the fifth-century West shows real material decline: pottery, roofs, coinage. However, the counterclaim about excavation bias is not fully answered.");
await page.getByLabel("What remains contested").fill("Whether climate and disease were causes or accelerants; the Antonine and Justinianic evidence is suggestive but the demographic numbers are contested.");
await page.getByLabel("What would change my mind").fill("A dated regional series showing collapse in provinces with no fiscal or military stress.");
await page.screenshot({ path: "/tmp/shots/rooms/inv-synthesis.png", fullPage: true });
await page.getByRole("button", { name: "Mark synthesised" }).click();
await page.waitForSelector("text=Review");
await page.getByRole("button", { name: "Save the position to the Archive as a note" }).click();
await page.waitForSelector("text=Saved to the Archive");
await page.screenshot({ path: "/tmp/shots/rooms/inv-synthesised.png", fullPage: true });
const c = await idbCounts(page, ["investigations", "skill_evidence", "after_actions", "archive_notes"]);
out.status = c.investigations.map((i) => i.status);
out.evidence = c.skill_evidence.filter((e) => e.source?.kind === "investigation").map((e) => [e.subskill, Math.round(e.score * 100)]);
out.afterActions = c.after_actions.length;
out.archiveNotes = c.archive_notes.length;
await page.goto("http://localhost:3000/investigations", { waitUntil: "networkidle" });
await page.screenshot({ path: "/tmp/shots/rooms/inv-index.png" });
out.errors = errors;
console.log(JSON.stringify(out, null, 1));
await browser.close();
