import { chromium } from "@playwright/test";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:3000/enter?skip=1&name=Ismail", { waitUntil: "networkidle" });
await page.goto("http://localhost:3000/salon/sal-professor-print", { waitUntil: "networkidle" });
await page.waitForSelector("textarea");
const ask = async (t) => { await page.fill("textarea", t); await page.click("button:has-text('Say it')"); await page.waitForTimeout(600); };
await ask("What was literacy like around 1500? Who could actually read?");
await ask("Isn't it obvious that you're just a technological determinist?");
await ask("What about the Hussites in Bohemia, before printing existed?");
await ask("Which counterexample do you personally find most awkward for the thesis?");
const facts = await page.locator("aside li.border-forest").count();
const leading = await page.locator("text=leading").count();
await page.screenshot({ path: "/tmp/claude-0/-home-user-THE-STUDY/3ab2e634-fb47-534f-9fe7-c6bbbf105fc0/scratchpad/salon-conv.png" });
await page.click("button:has-text('End the conversation')");
await page.click("button:has-text('Review the conversation')");
await page.waitForSelector("text=Post-conversation review");
await page.screenshot({ path: "/tmp/claude-0/-home-user-THE-STUDY/3ab2e634-fb47-534f-9fe7-c6bbbf105fc0/scratchpad/salon-review.png" });
await page.reload({ waitUntil: "networkidle" });
const persisted = await page.locator("text=Post-conversation review").count();
console.log(JSON.stringify({ factsRevealed: facts, leadingMarks: leading, reviewPersisted: persisted, errors }));
await browser.close();
