import type { PracticeItem } from "@/lib/v2/content-types";

/**
 * Logic practice items. Ids it-logic-01 … it-logic-39. British spelling throughout.
 *
 * Coverage: identifying conclusions and premises, validity and soundness, deduction versus
 * induction, necessary and sufficient conditions, conditionals (converse, inverse,
 * contrapositive), truth-table counting, quantifiers, formal and informal fallacies,
 * consistency, reconstruction and steelmanning. Every mcq distractor encodes a named
 * mistake so the error classifier can attribute it. Items 34–36 are exam-only; 37–39
 * were added so that the steelmanning and consistency lessons have distinct guided,
 * independent and transfer items.
 */
export const ITEMS_LOGIC: PracticeItem[] = [
  /* ---------------------------------------------------------------- */
  /* Arguments, premises, conclusions                                   */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-01",
    skill: "logic",
    subskill: "identify_conclusion",
    concepts: ["arguments-premises-conclusions"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt:
      "Read the passage and identify its conclusion.\n\n\"The council keeps saying the new car park will ease congestion. But every car park built here in the last decade has been full within a year, and full car parks pull more cars into the centre, not fewer. The new car park will make congestion worse.\"",
    options: [
      "The council keeps saying the new car park will ease congestion.",
      "Every car park built here in the last decade has been full within a year.",
      "Full car parks pull more cars into the centre.",
      "The new car park will make congestion worse.",
    ],
    answer: 3,
    solution:
      "The conclusion is the claim the writer wants you to accept on the strength of the others: that the new car park will make congestion worse. The first sentence reports the council's view, which the passage is arguing against; it is not the writer's claim. The second and third sentences are the premises: past car parks filled quickly, and full car parks attract traffic. Together they are offered as reasons for the final sentence. Here the conclusion does happen to come last, but the test was not its position; it was that the other sentences are given in support of it, while it is not given in support of anything.",
    method: "Ask which statement the others are offered as reasons for. Mark reported opposing views as context, not as premises or conclusion.",
    hints: ["One sentence reports what somebody else says. Is the writer endorsing it?", "Which sentence would the writer defend by pointing to the others?", "The premises are the two facts about car parks; what do they support?"],
    commonErrors: [
      { description: "Took the reported view of the council as the conclusion; the passage is arguing against it.", category: "MISREAD", optionIndex: 0 },
      { description: "Chose a premise (the historical fact) instead of the claim it supports.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Chose the general premise about full car parks; it is a reason, not the claim being argued for.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["conclusion", "reading"],
    origin: "seeded",
  },
  {
    id: "it-logic-02",
    skill: "logic",
    subskill: "argument_forms",
    concepts: ["propositional-logic", "validity-and-soundness"],
    level: "basic",
    difficulty: 2,
    format: "short",
    prompt: "Name the valid argument form: 'If the pump is running, the tank is filling. The pump is running. Therefore the tank is filling.'",
    answer: "modus ponens",
    accept: ["MP", "affirming the antecedent", "modus ponendo ponens"],
    solution:
      "The argument has the form 'if P then Q; P; therefore Q'. That is modus ponens (Latin: the mode that affirms), sometimes called affirming the antecedent. It is valid: in the one row of the truth table where P → Q and P are both true, Q is true as well. Its mirror, modus tollens, runs 'if P then Q; not Q; therefore not P'. The two invalid look-alikes are affirming the consequent (if P then Q; Q; so P) and denying the antecedent (if P then Q; not P; so not Q).",
    method: "Write the argument as letters, then match the pattern against the four conditional forms (two valid, two fallacious).",
    hints: ["Replace the sentences with P and Q. What is asserted in the second premise: P, Q, not P or not Q?", "The second premise affirms the 'if' part. What is the Latin name for affirming the antecedent?"],
    commonErrors: [
      { description: "Named modus tollens; that form denies the consequent rather than affirming the antecedent.", category: "KNOWLEDGE_GAP", pattern: "tollens" },
      { description: "Called the argument a fallacy; affirming the antecedent is valid, affirming the consequent is not.", category: "CONCEPTUAL_ERROR", pattern: "consequent" },
    ],
    transfer: 0,
    minutes: 1,
    tags: ["forms"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Validity and soundness                                             */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-03",
    skill: "logic",
    subskill: "validity",
    concepts: ["validity-and-soundness"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "True or false: the following argument is valid.\n\n\"All cats are reptiles. All reptiles have fur. Therefore all cats have fur.\"",
    answer: "true",
    solution:
      "True. Validity asks only whether the conclusion would have to be true if the premises were true. Suppose, contrary to fact, that every cat were a reptile and every reptile had fur; then every cat would have fur. There is no possible situation in which both premises hold and the conclusion fails, so the argument is valid. It is not sound, because the first premise is false (and the second), and its conclusion happens to be true only by accident. The example is deliberately absurd to force the separation: validity is a property of the form 'all A are B; all B are C; so all A are C', which holds for any A, B and C.",
    method: "Ignore whether the premises are actually true. Try to describe a world in which the premises hold and the conclusion fails; if none exists, the argument is valid.",
    hints: ["Do not ask whether the premises are true. Ask what would follow if they were.", "Replace cats, reptiles and fur with A, B and C. Is 'all A are B; all B are C; so all A are C' a good form?"],
    commonErrors: [{ description: "Judged the argument invalid because a premise is false. False premises make an argument unsound, not invalid.", category: "CONCEPTUAL_ERROR", pattern: "false" }],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["validity", "soundness"],
    origin: "seeded",
  },
  {
    id: "it-logic-04",
    skill: "logic",
    subskill: "validity",
    concepts: ["validity-and-soundness", "quantifiers"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "Exactly one of these arguments is valid. Which?",
    options: [
      "All whales are mammals. Some mammals live on land. Therefore some whales live on land.",
      "All spiders are insects. All insects have six legs. Therefore all spiders have six legs.",
      "All cats are mammals. All dogs are mammals. Therefore all cats are dogs.",
      "Some politicians are honest. All honest people keep their promises. Therefore all politicians keep their promises.",
    ],
    answer: 1,
    solution:
      "Option 2 is valid: 'all A are B; all B are C; so all A are C' cannot have true premises and a false conclusion. Both its premises are false (spiders are arachnids with eight legs), so the argument is unsound, but soundness was not asked. Option 1 has true premises and a false conclusion, which is the signature of invalidity: 'some mammals live on land' says nothing about which mammals. Option 3 is the undistributed middle: cats and dogs both sit inside the class of mammals without overlapping. Option 4 slides from 'some politicians' to 'all politicians'; the premises only establish that the honest ones keep promises.",
    method: "Reduce each argument to its form with letters, then look for a counterexample of the same shape. Ignore the truth of the premises.",
    hints: ["One argument has true premises and a false conclusion. That alone proves it invalid.", "Two of the invalid arguments fail on quantifiers: 'some' does not carry to 'all', and two classes inside a third need not overlap.", "The valid one may have false premises. Check its form: all A are B, all B are C."],
    commonErrors: [
      { description: "Chose the argument with true premises; true premises and a false conclusion is exactly what invalidity looks like.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Accepted the undistributed middle: two classes inside a third need not overlap.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Let 'some politicians' carry the conclusion to 'all politicians'.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["validity", "syllogism"],
    origin: "seeded",
  },
  {
    id: "it-logic-05",
    skill: "logic",
    subskill: "soundness",
    concepts: ["validity-and-soundness"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt: "An argument is valid, and one of its premises is false. Which statement is correct?",
    options: [
      "The argument is unsound, and its conclusion may be either true or false.",
      "The argument is invalid, because a valid argument cannot have a false premise.",
      "The argument is sound, because soundness depends only on form.",
      "The conclusion must be false, because a false premise cannot support a true conclusion.",
    ],
    answer: 0,
    solution:
      "Sound means valid with all premises true, so a valid argument with a false premise is unsound. Nothing further follows about the conclusion: 'all cats are reptiles; all reptiles are animals; so all cats are animals' is valid, has a false premise, and a true conclusion, while replacing 'animals' with 'cold-blooded' gives a valid argument with a false premise and a false conclusion. Option 2 confuses validity (form) with soundness (form plus true premises). Option 3 reverses the definitions. Option 4 assumes a false premise poisons the conclusion, but a true conclusion can be reached from false premises by a valid route; it is just not established by them.",
    method: "Apply the definitions: valid = the form guarantees the conclusion; sound = valid and all premises true. Then ask what the definitions do and do not say about the conclusion.",
    hints: ["What is the definition of soundness?", "Does a false premise say anything about the form of the argument?", "Construct a valid argument with a false premise and a true conclusion."],
    commonErrors: [
      { description: "Treated a false premise as a defect of form; premises bear on soundness, not validity.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Swapped the definitions of valid and sound.", category: "KNOWLEDGE_GAP", optionIndex: 2 },
      { description: "Inferred a false conclusion from a false premise; valid arguments from false premises can still land on truths.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["soundness"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Deduction and induction                                            */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-06",
    skill: "logic",
    subskill: "deduction_induction",
    concepts: ["deduction-vs-induction"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Which of these arguments is inductive?",
    options: [
      "Every prime greater than 2 is odd; 97 is a prime greater than 2; so 97 is odd.",
      "The last 40 quarterly reports from this firm arrived late; so the next one will probably arrive late.",
      "If the fuse has blown, the lights are off; the lights are on; so the fuse has not blown.",
      "No mammals lay eggs, except monotremes; a platypus is a monotreme; so a platypus may lay eggs.",
    ],
    answer: 1,
    solution:
      "Option 2 is inductive: it generalises from a run of observed cases to a prediction about an unobserved one, and it claims only probability ('will probably'). Options 1 and 3 are deductive: if their premises are true their conclusions must be, by universal instantiation in the first and modus tollens in the third. Option 4 is a definitional deduction from an exception clause, not an inference from evidence; it moves from general to particular and does not rest on a sample. Note that direction of inference is not the test: option 1 also goes from general to particular, and would remain deductive if it went the other way with the same guarantee.",
    method: "Ask whether the premises are offered as guaranteeing the conclusion (deductive) or as making it probable (inductive). Look for sampling, prediction or analogy.",
    hints: ["Which argument hedges its conclusion with 'probably'?", "Which argument rests on a series of observed cases rather than a rule?", "Deductive arguments can go from general to particular or the reverse; the test is the guarantee, not the direction."],
    commonErrors: [
      { description: "Took 'general to particular' as the mark of deduction and looked for the reverse; direction is not the criterion.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Read modus tollens as a guess because it reasons backwards from an effect; it is a valid deduction.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Treated a hedged conclusion ('may') from a definitional exception as inductive; no sample or observation is involved.", category: "MISREAD", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["induction"],
    origin: "seeded",
  },
  {
    id: "it-logic-07",
    skill: "logic",
    subskill: "deduction_induction",
    concepts: ["deduction-vs-induction", "validity-and-soundness"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "True or false: a strong inductive argument whose premises are all true can still have a false conclusion.",
    answer: "true",
    solution:
      "True. Inductive strength means the premises make the conclusion probable, not certain; that is the point of the category. 'Every swan recorded by European naturalists for two thousand years has been white, so all swans are white' was a strong argument with true premises until Dutch sailors reached the coast of Western Australia in 1697 and found black ones. The falsehood of the conclusion was not a flaw in the argument but the residual risk any induction carries. Contrast deduction: a valid argument with true premises (a sound argument) cannot have a false conclusion. That is the difference between the two standards.",
    method: "Recall the definitions: validity forbids true premises with a false conclusion; strength only makes that combination improbable.",
    hints: ["What does 'strong' mean for an inductive argument, compared with 'valid' for a deductive one?", "Think of a well-supported generalisation that later turned out false."],
    commonErrors: [{ description: "Applied the deductive standard (true premises guarantee the conclusion) to an inductive argument.", category: "CONCEPTUAL_ERROR", pattern: "false" }],
    transfer: 0,
    minutes: 1,
    examEligible: true,
    tags: ["induction", "swans"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Necessary and sufficient                                           */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-08",
    skill: "logic",
    subskill: "necessary_sufficient",
    concepts: ["necessary-and-sufficient"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt: "Being a square is which kind of condition for being a rectangle?",
    options: ["Necessary but not sufficient", "Sufficient but not necessary", "Both necessary and sufficient", "Neither necessary nor sufficient"],
    answer: 1,
    solution:
      "Every square is a rectangle (four right angles), so being a square guarantees being a rectangle: sufficient. But a rectangle need not be a square (a 2 × 3 rectangle is not), so being a square is not necessary for being a rectangle. The relation runs the other way too: being a rectangle is necessary for being a square, since nothing can be a square without being a rectangle, but it is not sufficient. A quick check for any pair: 'sufficient' means if A then B; 'necessary' means if B then A. Here 'if square then rectangle' is true and 'if rectangle then square' is false.",
    method: "Test the two conditionals separately: does A guarantee B (sufficient)? Is A required for B (necessary)?",
    hints: ["Is every square a rectangle? Is every rectangle a square?", "'A is sufficient for B' means 'if A then B'. 'A is necessary for B' means 'if B then A'."],
    commonErrors: [
      { description: "Reversed the relation: being a rectangle is necessary for being a square, not the other way round.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Assumed the two shapes are equivalent because every square is a rectangle.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Denied the connection altogether, presumably thinking a square is a different shape rather than a special rectangle.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 1,
    examEligible: true,
    tags: ["conditions"],
    origin: "seeded",
  },
  {
    id: "it-logic-09",
    skill: "logic",
    subskill: "necessary_sufficient",
    concepts: ["necessary-and-sufficient", "conditionals-and-contrapositive"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Oxygen is necessary for a fire. Investigators establish that a fire burned in a sealed store room. Which conclusion is licensed by these two facts alone?",
    options: [
      "Oxygen was present in the room while the fire burned.",
      "Oxygen caused the fire.",
      "Because the room contained oxygen, a fire was bound to occur.",
      "Nothing follows; a necessary condition never supports an inference.",
    ],
    answer: 0,
    solution:
      "'Oxygen is necessary for fire' means: if there is fire, there is oxygen. A fire burned, so oxygen was present. That is modus ponens on the necessary-condition conditional, and it is the only inference the two facts license. Option 2 confuses a necessary condition with a cause; oxygen is required, but the fire needs fuel and an ignition source too, and the investigators will want to know what those were. Option 3 treats oxygen as sufficient: rooms full of oxygen do not spontaneously burn. Option 4 overcorrects; necessary conditions do license inferences, from the outcome back to the condition, and from the absence of the condition to the absence of the outcome.",
    method: "Rewrite the necessary condition as 'if outcome then condition', then see which premise you actually have.",
    hints: ["Turn 'oxygen is necessary for fire' into an if–then sentence. Which way does the arrow point?", "You know the outcome occurred. What does the conditional give you?", "A necessary condition being present tells you nothing about the outcome; the outcome having occurred tells you the condition was met."],
    commonErrors: [
      { description: "Promoted a necessary condition to a cause; other conditions were also required.", category: "CAUSAL_ERROR", optionIndex: 1 },
      { description: "Treated the necessary condition as sufficient.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Concluded that necessary conditions license nothing; they license inference from the outcome to the condition.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["conditions", "fire"],
    origin: "seeded",
  },
  {
    id: "it-logic-10",
    skill: "logic",
    subskill: "necessary_sufficient",
    concepts: ["necessary-and-sufficient"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A regulation states: 'Candidates may sit the examination only if they have registered by 1 March.' What kind of condition is registering by 1 March for sitting the examination?",
    options: ["Sufficient: anyone who registers by 1 March may sit the examination.", "Necessary: nobody may sit without registering, but registering alone may not be enough.", "Both necessary and sufficient.", "Neither: the regulation only describes a deadline."],
    answer: 1,
    solution:
      "'A only if B' expresses B as a necessary condition for A: sitting the examination requires registration, so no registration, no examination. It does not say that registration is enough; there may be fees, identity checks or prerequisites in other clauses. The phrase 'only if' is the standard marker of necessity in legal, technical and academic writing, and it is routinely misread as 'if', which would make registration sufficient. To claim both directions the regulation would have to say 'if and only if', or state the sufficient direction separately.",
    method: "Map the connective: 'if B' marks B as sufficient; 'only if B' marks B as necessary; 'if and only if' marks both.",
    hints: ["What is the difference between 'if' and 'only if'?", "Rewrite: 'if a candidate sits the examination, then the candidate registered by 1 March.' Which condition is that?"],
    commonErrors: [
      { description: "Read 'only if' as 'if', turning a necessary condition into a sufficient one.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Assumed both directions; the text gives only one.", category: "ASSUMPTION", optionIndex: 2 },
      { description: "Missed that a deadline clause is a condition at all.", category: "MISREAD", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["conditions", "only-if"],
    origin: "seeded",
  },
  {
    id: "it-logic-11",
    skill: "logic",
    subskill: "necessary_sufficient",
    concepts: ["necessary-and-sufficient", "conditionals-and-contrapositive"],
    level: "intermediate",
    difficulty: 3,
    format: "multi_select",
    prompt: "Rule: if a whole number is divisible by 4, then it is even. Select every statement that follows from this rule.",
    options: [
      "Being even is necessary for being divisible by 4.",
      "Being even is sufficient for being divisible by 4.",
      "Being divisible by 4 is sufficient for being even.",
      "If a number is not even, it is not divisible by 4.",
      "If a number is not divisible by 4, it is not even.",
    ],
    answer: [0, 2, 3],
    solution:
      "The rule is 'if divisible by 4 then even'. So divisibility by 4 is sufficient for evenness (option 3), and, reading the same conditional the other way, evenness is necessary for divisibility by 4 (option 1): a number that fails to be even cannot be divisible by 4. Option 4 is the contrapositive, 'if not even then not divisible by 4', which is equivalent to the rule. Option 2 is the converse, false: 6 is even and not divisible by 4. Option 5 is the inverse, also false, for the same counterexample. The pattern to remember: one conditional yields one sufficiency claim, one necessity claim and one contrapositive, all equivalent; the converse and the inverse are a separate claim.",
    method: "From 'if A then B' extract: A sufficient for B, B necessary for A, and not-B implies not-A. Reject the converse and inverse with a counterexample.",
    hints: ["Write the rule as A → B with A = divisible by 4, B = even. Which option says A is sufficient? Which says B is necessary?", "Which option is the contrapositive, not-B → not-A?", "Test the remaining two with the number 6."],
    commonErrors: [
      { description: "Selected the converse: evenness does not guarantee divisibility by 4 (6).", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Selected the inverse, which is equivalent to the converse and fails for the same reason.", category: "LOGIC_ERROR", optionIndex: 4 },
      { description: "Omitted the contrapositive, not recognising it as equivalent to the rule.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["conditions", "contrapositive"],
    origin: "seeded",
  },
  {
    id: "it-logic-12",
    skill: "logic",
    subskill: "necessary_sufficient",
    concepts: ["necessary-and-sufficient", "contracts"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A clause reads: 'This agreement is binding only if it has been signed by both parties.' Both parties have signed. From this clause alone, what follows about whether the agreement is binding?",
    options: [
      "It is binding: the condition in the clause has been met.",
      "It is not binding: the clause is only about what would prevent it from binding.",
      "Nothing follows: signing is stated as a necessary condition, and other requirements may exist.",
      "It is binding unless one party withdraws before performance begins.",
    ],
    answer: 2,
    solution:
      "'Only if' makes signature by both parties a necessary condition for the agreement to bind. Meeting a necessary condition removes one obstacle; it does not deliver the outcome. Other clauses may require consideration, a date, regulatory approval or a counter-signature by a guarantor, and this clause says nothing about them. Option 1 is the classic promotion of a necessary condition to a sufficient one. Option 2 is also wrong: the clause does not say the agreement fails to bind, only that it would fail without signatures. Option 4 imports a withdrawal rule the clause does not mention. A careful reader notes the direction of the conditional and then goes looking for the rest of the conditions.",
    method: "Identify the condition type from the connective ('only if' = necessary), then ask whether meeting it licenses any conclusion about the outcome. It does not; only failing it does.",
    hints: ["What does 'only if' mark: a sufficient or a necessary condition?", "If a necessary condition is met, what can you conclude about the outcome?", "What could you conclude if one party had not signed?"],
    commonErrors: [
      { description: "Treated a necessary condition as sufficient: the signatures were required, not enough.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Read the clause as denying that the agreement binds; it only states a requirement.", category: "MISREAD", optionIndex: 1 },
      { description: "Added a withdrawal rule that the clause does not contain.", category: "ASSUMPTION", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["conditions", "contracts"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Conditionals, contrapositive, Wason                                */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-13",
    skill: "logic",
    subskill: "contrapositive",
    concepts: ["conditionals-and-contrapositive"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt: "Which statement is the contrapositive of 'If it rains, the match is cancelled'?",
    options: [
      "If the match is cancelled, it rained.",
      "If it does not rain, the match is not cancelled.",
      "If the match is not cancelled, it did not rain.",
      "If the match is cancelled, it did not rain.",
    ],
    answer: 2,
    solution:
      "The contrapositive of 'if P then Q' is 'if not Q then not P': swap the two parts and negate both. With P = it rains and Q = the match is cancelled, that gives 'if the match is not cancelled, it did not rain' (option 3), which is equivalent to the original. Option 1 is the converse (swap without negating), option 2 the inverse (negate without swapping); both say something different from the original: the match may be cancelled for reasons other than rain. Option 4 negates only one side and is simply a different claim.",
    method: "Swap antecedent and consequent, then negate both. Check by asking whether the result must be true whenever the original is.",
    hints: ["The contrapositive both swaps and negates. Which option does both?", "If the match went ahead, could it have rained, given the rule?"],
    commonErrors: [
      { description: "Chose the converse: swapped without negating.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Chose the inverse: negated without swapping.", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Negated only the consequent.", category: "PRECISION_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 1,
    examEligible: true,
    tags: ["contrapositive"],
    origin: "seeded",
  },
  {
    id: "it-logic-14",
    skill: "logic",
    subskill: "contrapositive",
    concepts: ["conditionals-and-contrapositive"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Which statement is logically equivalent to 'If a number is divisible by 6, it is divisible by 3'?",
    options: [
      "If a number is divisible by 3, it is divisible by 6.",
      "If a number is not divisible by 6, it is not divisible by 3.",
      "If a number is not divisible by 3, it is not divisible by 6.",
      "A number is divisible by 6 if and only if it is divisible by 3.",
    ],
    answer: 2,
    solution:
      "Only the contrapositive is equivalent: 'if not divisible by 3, then not divisible by 6' (option 3). The number 9 refutes the other candidates: it is divisible by 3 but not by 6, so the converse (option 1) is false, the inverse (option 2) is false, and the biconditional (option 4) is false. The original is true because 6 = 2 × 3, so any multiple of 6 is a multiple of 3. When a conditional is true and its converse is false, as here, the difference between them is not a technicality: the original says divisibility by 6 is sufficient for divisibility by 3, and the converse would say it is necessary, which it is not.",
    method: "Form the contrapositive by swapping and negating; test the converse and inverse with a counterexample (9).",
    hints: ["Find a number divisible by 3 but not by 6. Which options does it refute?", "Which option is the contrapositive: swapped and negated?"],
    commonErrors: [
      { description: "Chose the converse; 9 is divisible by 3 and not by 6.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Chose the inverse, which fails for the same counterexample.", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Upgraded a one-way conditional to a biconditional.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["contrapositive", "number"],
    origin: "seeded",
  },
  {
    id: "it-logic-15",
    skill: "logic",
    subskill: "converse",
    concepts: ["conditionals-and-contrapositive"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "True or false: if a conditional statement is true, its converse must also be true.",
    answer: "false",
    solution:
      "False. 'If a figure is a square, it has four sides' is true; its converse, 'if a figure has four sides, it is a square', is false. A conditional and its converse are independent claims: both can be true (when P and Q are equivalent), one can be true and the other false, or both can be false. The only transformation that preserves truth is the contrapositive. Treating the converse as automatic is the root of affirming the consequent and of the everyday error of reading 'if' as 'if and only if'.",
    method: "Produce a counterexample: a true conditional whose converse fails.",
    hints: ["Think of a true 'if P then Q' where many things other than P also produce Q.", "The converse swaps the two halves. Does 'every square has four sides' make 'every four-sided figure a square'?"],
    commonErrors: [{ description: "Assumed the converse inherits the truth of the original, in effect reading 'if' as 'if and only if'.", category: "LOGIC_ERROR", pattern: "true" }],
    transfer: 0,
    minutes: 1,
    tags: ["converse"],
    origin: "seeded",
  },
  {
    id: "it-logic-16",
    skill: "logic",
    subskill: "conditional_testing",
    concepts: ["conditionals-and-contrapositive", "formal-fallacies"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt:
      "Four cards lie on a table. Each has a letter on one side and a number on the other. The visible faces show E, K, 4 and 7. Rule to test: 'If a card has a vowel on one side, then it has an even number on the other.' Which cards must be turned over, and only those, to find out whether the rule is broken?",
    options: ["E and 4", "E only", "E and 7", "E, K, 4 and 7"],
    answer: 2,
    solution:
      "The rule is 'vowel → even'. It is broken only by a card with a vowel on one side and an odd number on the other. E might have an odd number behind it, so it must be turned. 7 might have a vowel behind it, so it must be turned (this is the contrapositive: not even → not vowel). K cannot break the rule whatever is behind it, because the rule says nothing about consonants. 4 cannot break it either: a consonant behind it is allowed, and a vowel behind it merely confirms the rule. So the answer is E and 7. In Wason's 1966 study and its many replications, most people choose E alone or E and 4, checking the cases that could confirm the rule rather than the ones that could falsify it. The correct choice follows from asking, for each card, whether any hidden face would make the rule false.",
    method: "For each card ask: is there a hidden face that would falsify the rule? Turn exactly those cards. Falsifiers are vowel-with-odd, so check the vowel and the odd number.",
    hints: ["What combination of letter and number would break the rule?", "Can the K card break the rule, whatever is on its back? Can the 4?", "Which card could hide a vowel behind an odd number?"],
    commonErrors: [
      { description: "Chose the cards named in the rule (vowel, even) rather than the cards that could falsify it; the 4 cannot break the rule.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Checked only the antecedent and missed the contrapositive case: an odd number hiding a vowel.", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Turned every card; K and 4 cannot break the rule, so turning them is not required.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["wason", "falsification"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Propositional logic, truth tables                                  */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-17",
    skill: "logic",
    subskill: "truth_tables",
    concepts: ["propositional-logic"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "In the four-row truth table for two statements P and Q, in how many rows is the conditional P → Q true?",
    answer: 3,
    tolerance: 0,
    solution:
      "The conditional P → Q is false in exactly one row, where P is true and Q is false, and true in the other three: (P true, Q true), (P false, Q true) and (P false, Q false). The two rows with a false antecedent are the ones people resist: 'if it rains the match is cancelled' is not shown false by a dry day with the match cancelled, nor by a dry day with the match played. The rule makes a promise only about rainy days. Because a false antecedent never falsifies a conditional, the conditional counts as true in those rows; this is what makes the contrapositive equivalent and the converse not.",
    method: "Recall that a conditional is falsified by exactly one combination (true antecedent, false consequent) and count the remaining rows.",
    hints: ["How many rows does a table for two statements have?", "In which single combination does 'if P then Q' fail?", "Subtract that one row from the total."],
    commonErrors: [
      { description: "Counted only the row with P and Q both true, reading the conditional as a conjunction.", category: "CONCEPTUAL_ERROR", value: 1 },
      { description: "Counted the rows where P and Q match (both true, both false), reading the conditional as a biconditional.", category: "CONCEPTUAL_ERROR", value: 2 },
      { description: "Counted every row, forgetting the falsifying case.", category: "MISREAD", value: 4 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["truth-tables"],
    origin: "seeded",
  },
  {
    id: "it-logic-18",
    skill: "logic",
    subskill: "truth_tables",
    concepts: ["propositional-logic"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "Three statements P, Q and R have eight truth assignments. In how many of them is (P ∨ Q) → R false?",
    answer: 3,
    tolerance: 0,
    solution:
      "A conditional is false only when its antecedent is true and its consequent false. The antecedent P ∨ Q is true in three of the four (P, Q) combinations: (T,T), (T,F), (F,T). The consequent R must be false, which fixes R. So there are 3 × 1 = 3 falsifying assignments: (T,T,F), (T,F,F), (F,T,F). The other five assignments make the conditional true: the four with R true and the one with P and Q both false (where the antecedent fails, so the promise is not tested). Counting this way, by fixing the falsifying condition and multiplying, is faster and less error-prone than writing all eight rows.",
    method: "Characterise the falsifying case (antecedent true, consequent false), count assignments satisfying it by the multiplication principle.",
    hints: ["When is any conditional false?", "In how many (P, Q) combinations is P ∨ Q true? Remember 'or' is inclusive.", "Multiply by the number of R values that make the consequent false."],
    commonErrors: [
      { description: "Counted every assignment with R false, ignoring that the antecedent must be true.", category: "CONCEPTUAL_ERROR", value: 4 },
      { description: "Read ∨ as ∧ and counted only the assignment with P, Q both true and R false.", category: "CONCEPTUAL_ERROR", value: 1 },
      { description: "Reported the number of rows where the conditional is true.", category: "MISREAD", value: 5 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["truth-tables", "counting"],
    origin: "seeded",
  },
  {
    id: "it-logic-19",
    skill: "logic",
    subskill: "de_morgan",
    concepts: ["propositional-logic"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A control panel shows the message: 'It is not the case that both the pump and the valve are working.' Which statement is logically equivalent?",
    options: ["Neither the pump nor the valve is working.", "At least one of the pump and the valve is not working.", "Exactly one of the pump and the valve is working.", "The pump is not working."],
    answer: 1,
    solution:
      "By De Morgan's law, ¬(P ∧ Q) is equivalent to ¬P ∨ ¬Q: 'not both' means 'at least one is not'. That covers three situations: pump failed, valve failed, or both failed. Option 1 ('neither') is the negation of P ∨ Q, a stronger claim that would rule out the case where one component still works. Option 3 excludes the both-failed case, which the message allows. Option 4 picks one component arbitrarily. The engineering consequence is real: reading 'not both' as 'neither' would send a technician to replace two parts when one may be fine.",
    method: "Apply De Morgan: the negation of a conjunction is the disjunction of the negations.",
    hints: ["List the four states of (pump, valve). Which ones does the message exclude?", "Does the message rule out 'pump working, valve failed'?"],
    commonErrors: [
      { description: "Read 'not both' as 'neither', negating each part instead of the conjunction.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Read the disjunction as exclusive, dropping the both-failed case.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Selected one component without warrant.", category: "ASSUMPTION", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["de-morgan"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Quantifiers                                                        */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-20",
    skill: "logic",
    subskill: "quantifier_negation",
    concepts: ["quantifiers"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A laboratory report says: 'Not all of the samples were contaminated.' Which statement means exactly the same?",
    options: ["None of the samples was contaminated.", "At least one sample was not contaminated.", "Most of the samples were not contaminated.", "At least one sample was contaminated."],
    answer: 1,
    solution:
      "The negation of 'all samples were contaminated' is 'some sample was not contaminated', that is, at least one clean sample exists. Option 1 is far stronger: it claims every sample was clean, which the report does not say. Option 3 introduces 'most', a quantity the report never gives; one clean sample out of a hundred satisfies the report. Option 4 says the opposite kind of thing: it is compatible with the report but not equivalent to it (the report would also be true if no sample were contaminated at all). The general rule: to negate 'all', assert 'some are not'; to negate 'some', assert 'none'.",
    method: "Negate a universal by moving the negation inward: not all A are B becomes some A is not B.",
    hints: ["What is the smallest fact that would make 'all samples were contaminated' false?", "Does the report tell you anything about how many samples were clean?"],
    commonErrors: [
      { description: "Negated 'all' to 'none', overstating the claim.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Imported a quantity ('most') that the statement does not contain.", category: "PRECISION_ERROR", optionIndex: 2 },
      { description: "Chose a statement about contaminated samples rather than about the uncontaminated one that the negation asserts.", category: "MISREAD", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["quantifiers", "negation"],
    origin: "seeded",
  },
  {
    id: "it-logic-21",
    skill: "logic",
    subskill: "quantifier_order",
    concepts: ["quantifiers"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt: "Consider two sentences about a company.\n(1) Every employee has a manager they report to.\n(2) There is one manager to whom every employee reports.\nWhat is the logical relation between them?",
    options: [
      "(2) implies (1), but (1) does not imply (2).",
      "(1) implies (2), but (2) does not imply (1).",
      "They are equivalent.",
      "Neither implies the other.",
    ],
    answer: 0,
    solution:
      "Sentence (1) is 'for every employee there is some manager' (∀x∃y); sentence (2) is 'there is some manager such that every employee reports to them' (∃y∀x). If one manager receives every report, then certainly each employee has a manager, so (2) implies (1). The reverse fails: in a firm where employees report to different managers, (1) is true and (2) false. The order of the quantifiers is the whole difference. The same structure appears in 'everyone has a favourite book' versus 'one book is everyone's favourite', and in 'every process has a handler' versus 'one handler serves every process' in a specification.",
    method: "Write each sentence with its quantifiers in order (∀∃ versus ∃∀). ∃∀ always implies ∀∃; look for a counterexample to the converse.",
    hints: ["Rewrite (1) as 'for each employee, there exists a manager …' and (2) as 'there exists a manager such that, for each employee …'.", "Imagine a firm with two teams and two managers. Which sentence is true there?", "If a single manager receives all reports, is (1) automatically true?"],
    commonErrors: [
      { description: "Reversed the implication: a distinct manager per employee satisfies (1) without (2).", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Ignored quantifier order and treated the sentences as the same claim.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Missed that a single universal manager satisfies the weaker sentence.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["quantifiers", "order"],
    origin: "seeded",
  },
  {
    id: "it-logic-22",
    skill: "logic",
    subskill: "syllogism",
    concepts: ["quantifiers", "formal-fallacies"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "True or false: the following form is valid.\n\n\"All A are B. All C are B. Therefore all A are C.\"",
    answer: "false",
    solution:
      "False. This is the fallacy of the undistributed middle. The term B appears in both premises but neither premise says anything about all of B, so A and C can each sit inside B without touching. Counterexample: all cats are mammals, all dogs are mammals, therefore all cats are dogs. The valid form places the middle term as the subject of one premise and the predicate of the other: all A are B, all B are C, therefore all A are C. The difference is easy to miss in prose, where 'both share property B' sounds like a connection between A and C.",
    method: "Substitute concrete classes that share a common superclass but do not overlap; if the premises come out true and the conclusion false, the form is invalid.",
    hints: ["Try A = cats, B = mammals, C = dogs.", "Does either premise tell you about all of B?"],
    commonErrors: [{ description: "Accepted the undistributed middle as valid, treating shared membership of B as a link between A and C.", category: "LOGIC_ERROR", pattern: "true" }],
    transfer: 0,
    minutes: 1,
    tags: ["syllogism", "undistributed-middle"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Formal fallacies                                                   */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-23",
    skill: "logic",
    subskill: "formal_fallacies",
    concepts: ["formal-fallacies", "conditionals-and-contrapositive"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "\"If the new pricing is working, revenue rises this quarter. Revenue rose this quarter. Therefore the new pricing is working.\" What is this?",
    options: ["Modus ponens (valid)", "Affirming the consequent (invalid)", "Denying the antecedent (invalid)", "Modus tollens (valid)"],
    answer: 1,
    solution:
      "The form is 'if P then Q; Q; therefore P': affirming the consequent. It is invalid because revenue could have risen for other reasons (a competitor's outage, seasonality, a large one-off order). The conditional says pricing success guarantees a rise; it does not say a rise guarantees pricing success. As probabilistic evidence, the rise may raise the odds that the pricing is working, and how much depends on how likely a rise would have been anyway. Presenting it as a proof is the fallacy. Modus ponens would run 'pricing is working, therefore revenue rises'; modus tollens 'revenue did not rise, therefore pricing is not working'.",
    method: "Letter the argument, identify which part of the conditional the second premise asserts, and match against the four forms.",
    hints: ["Which half of the conditional does the second premise assert: the 'if' part or the 'then' part?", "Could revenue rise even if the pricing were not working?"],
    commonErrors: [
      { description: "Mistook the argument for modus ponens; the second premise asserts the consequent, not the antecedent.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Named the other fallacy; nothing here is denied.", category: "KNOWLEDGE_GAP", optionIndex: 2 },
      { description: "Called it modus tollens; that form denies the consequent.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["fallacies", "affirming-consequent"],
    origin: "seeded",
  },
  {
    id: "it-logic-24",
    skill: "logic",
    subskill: "formal_fallacies",
    concepts: ["formal-fallacies", "conditionals-and-contrapositive"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A commentator writes: \"If the central bank raises rates, inflation will fall. The bank has decided not to raise rates. So inflation will not fall.\" Which fallacy, if any, is committed?",
    options: ["Affirming the consequent", "Denying the antecedent", "None: the argument is modus tollens and valid", "Post hoc ergo propter hoc"],
    answer: 1,
    solution:
      "The form is 'if P then Q; not P; therefore not Q': denying the antecedent. The conditional says a rate rise would bring inflation down; it does not say a rate rise is the only thing that could. Inflation might fall because energy prices drop, demand weakens or supply chains recover. Modus tollens (option 3) would need 'inflation did not fall, so the bank did not raise rates'. Post hoc is a causal error about sequence, not a conditional form. The commentator has, in effect, read the conditional as its inverse, 'if the bank does not raise rates, inflation will not fall', which is a separate and much stronger claim.",
    method: "Identify what the second premise denies. Denying the consequent is valid; denying the antecedent is not.",
    hints: ["Which part of the conditional is negated in the second premise?", "Are there other ways inflation could fall?", "Modus tollens denies the 'then' part. Does this argument do that?"],
    commonErrors: [
      { description: "Confused the two fallacies; nothing here is affirmed.", category: "KNOWLEDGE_GAP", optionIndex: 0 },
      { description: "Mistook denying the antecedent for modus tollens.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Reached for a causal fallacy where the defect is one of conditional form.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["fallacies", "denying-antecedent", "economics"],
    origin: "seeded",
  },
  {
    id: "it-logic-25",
    skill: "logic",
    subskill: "formal_fallacies",
    concepts: ["formal-fallacies", "propositional-logic"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "Exactly one of these arguments is valid. Which?",
    options: [
      "If the alarm was set, it rang at 7. It rang at 7. So the alarm was set.",
      "If the alarm was set, it rang at 7. It did not ring at 7. So the alarm was not set.",
      "If the alarm was set, it rang at 7. The alarm was not set. So it did not ring at 7.",
      "If the alarm was set, it rang at 7. So if it rang at 7, the alarm was set.",
    ],
    answer: 1,
    solution:
      "Option 2 is modus tollens: if setting the alarm guarantees a ring at 7, then no ring at 7 means it was not set. Option 1 affirms the consequent (a ring could have come from a different alarm or a manual test). Option 3 denies the antecedent (an unset alarm does not prevent something else ringing at 7). Option 4 infers the converse, which the original conditional does not contain. Note that all four share the same first premise; validity is decided entirely by what is done with it.",
    method: "For each argument, letter the form and check against modus ponens, modus tollens and their two fallacious counterparts.",
    hints: ["Two valid forms use a conditional: one affirms the antecedent, one denies the consequent.", "Which option denies the consequent?", "Option 4 asserts the converse; is that ever licensed by the conditional alone?"],
    commonErrors: [
      { description: "Chose affirming the consequent.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Chose denying the antecedent.", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Accepted the converse as following from the conditional.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["fallacies", "modus-tollens"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Informal fallacies                                                 */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-26",
    skill: "logic",
    subskill: "informal_fallacies",
    concepts: ["informal-fallacies"],
    level: "basic",
    difficulty: 2,
    format: "short",
    prompt: "A councillor argues that the town should reduce car use. An opponent replies: 'You drove here today, so your argument is worthless.' Name the fallacy.",
    answer: "tu quoque",
    accept: ["ad hominem", "ad hominem tu quoque", "appeal to hypocrisy", "hypocrisy", "you too"],
    solution:
      "This is tu quoque ('you too'), the variant of ad hominem that charges the arguer with hypocrisy. Whether the councillor drove is irrelevant to whether reducing car use is a good policy; the argument stands or falls on its premises about congestion, health, cost and so on. The reply may tell us something about the councillor's consistency, and inconsistency can be worth pointing out, but it is not a reason to reject the conclusion. Either 'ad hominem' or 'tu quoque' is an acceptable name; the second is more precise.",
    method: "Ask whether the reply engages the premises or the conclusion of the argument. If it targets the person, it is a form of ad hominem; if the charge is hypocrisy, it is tu quoque.",
    hints: ["Does the reply say anything about whether car use should be reduced?", "The reply attacks the speaker's behaviour rather than the argument. Which family of fallacies does that belong to, and which member alleges hypocrisy?"],
    commonErrors: [
      { description: "Named the straw man; the opponent has not misrepresented the position, only attacked the person.", category: "KNOWLEDGE_GAP", pattern: "straw" },
      { description: "Called it a false dilemma; no choice between two options is presented.", category: "KNOWLEDGE_GAP", pattern: "dilemma" },
    ],
    transfer: 0,
    minutes: 1,
    tags: ["fallacies", "ad-hominem"],
    origin: "seeded",
  },
  {
    id: "it-logic-27",
    skill: "logic",
    subskill: "informal_fallacies",
    concepts: ["informal-fallacies"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A proposes lowering the speed limit on one residential street to 20 mph. B replies: 'So A thinks nobody should be allowed to drive anywhere in this town. That is absurd.' Which fallacy does B commit?",
    options: ["Straw man", "Slippery slope", "False dilemma", "Ad hominem"],
    answer: 0,
    solution:
      "B has replaced A's proposal (one street, 20 mph) with a much weaker and more extreme position (no driving anywhere) and refuted that instead. This is a straw man. A slippery slope would argue that the 20 mph limit will lead, step by step, to a ban; B does not describe a sequence of steps, only a substitution. A false dilemma would present two options as the only ones. Ad hominem would attack A rather than the proposal. The distinctions matter because the correct reply differs: to a straw man, restate the actual proposal; to a slippery slope, ask for the mechanism between the steps.",
    method: "Compare what the opponent actually said with what is being refuted. A refutation aimed at a distorted version is a straw man.",
    hints: ["Did A propose what B refutes?", "B does not describe a chain of consequences; that would be a different fallacy."],
    commonErrors: [
      { description: "Chose slippery slope; B substitutes an extreme position rather than describing a chain of steps.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Chose false dilemma; no pair of exhaustive options is offered.", category: "KNOWLEDGE_GAP", optionIndex: 2 },
      { description: "Chose ad hominem; B attacks a distorted proposal, not A's character.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["fallacies", "straw-man"],
    origin: "seeded",
  },
  {
    id: "it-logic-28",
    skill: "logic",
    subskill: "informal_fallacies",
    concepts: ["informal-fallacies", "argument-reconstruction"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "\"This newspaper is reliable. It says so on its own front page, and a reliable newspaper would not print a false statement about itself.\" Which fallacy is this?",
    options: ["Begging the question", "Appeal to authority", "Hasty generalisation", "Equivocation"],
    answer: 0,
    solution:
      "The argument assumes its conclusion. Reconstructed: (1) the paper says it is reliable; (2) a reliable paper would not print a false statement about itself; therefore the paper is reliable. Premise 2 only delivers the conclusion if the paper is already assumed reliable, which is what was to be shown. That is begging the question in its technical sense (petitio principii): the premises depend on the conclusion. It resembles an appeal to authority because the paper is cited, but the defect is not that the authority is unqualified; it is that the authority's credibility is the very point at issue. No sample is involved (hasty generalisation) and no word shifts meaning (equivocation).",
    method: "Put the argument in standard form and check whether any premise can be accepted without already accepting the conclusion.",
    hints: ["Write the premises out. Which one is only true if the conclusion is?", "Citing a source is not itself a fallacy. What is special about citing a source on its own reliability?"],
    commonErrors: [
      { description: "Labelled it an appeal to authority; the defect is circularity, not the authority's qualifications.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Chose hasty generalisation; no sample is involved.", category: "KNOWLEDGE_GAP", optionIndex: 2 },
      { description: "Chose equivocation; 'reliable' keeps its meaning throughout.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["fallacies", "circularity"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Contradiction and consistency                                      */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-29",
    skill: "logic",
    subskill: "consistency",
    concepts: ["contradiction-and-consistency", "quantifiers"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "Exactly one of these sets of statements is inconsistent (they cannot all be true together). Which?",
    options: [
      "Every employee has a badge. Ana is an employee. Ana has no badge.",
      "Every employee has a badge. Ana has a badge. Ana is not an employee.",
      "Some employees have badges. Ana is an employee. Ana has no badge.",
      "No employee has a badge. Ana has a badge. Ana is a contractor.",
    ],
    answer: 0,
    solution:
      "Set 1 cannot hold together: if every employee has a badge and Ana is an employee, Ana has a badge, contradicting the third statement. Set 2 is consistent: 'every employee has a badge' does not say only employees have badges, so a badge-holding non-employee (a visitor, a contractor) is allowed; reading it otherwise is illicit conversion. Set 3 is consistent because 'some employees' leaves room for employees without badges. Set 4 is consistent: a contractor is not an employee, so Ana's badge does not conflict with the rule about employees. Consistency is a matter of whether a situation exists in which all the statements hold, not whether the statements are likely.",
    method: "For each set, try to describe one situation that makes every statement true. Failure after honest effort indicates inconsistency; success proves consistency.",
    hints: ["Which set contains a universal rule, a case that falls under it, and a denial of what the rule says about that case?", "Does 'every employee has a badge' say anything about non-employees?", "What does 'some' allow?"],
    commonErrors: [
      { description: "Converted 'every employee has a badge' into 'everyone with a badge is an employee'.", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Read 'some employees' as 'all employees'.", category: "MISREAD", optionIndex: 2 },
      { description: "Assumed a contractor counts as an employee.", category: "ASSUMPTION", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["consistency"],
    origin: "seeded",
  },
  {
    id: "it-logic-30",
    skill: "logic",
    subskill: "consistency",
    concepts: ["contradiction-and-consistency"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "True or false: two statements that are both false can still be consistent with each other.",
    answer: "true",
    solution:
      "True. Consistency concerns possibility: a set of statements is consistent if there is some situation in which all of them are true. 'The meeting is in Lisbon' and 'the meeting is on a Thursday' may both be false of an actual meeting held in Oslo on a Monday, yet they are consistent, since a Lisbon meeting on a Thursday is perfectly possible. Inconsistency requires that no such situation exists, as with 'the meeting is entirely in Lisbon' and 'the meeting is entirely in Oslo'. Confusing 'consistent' with 'true' is common; the two properties are independent.",
    method: "Recall that consistency is joint satisfiability, not joint truth; find a possible situation in which both false statements would hold.",
    hints: ["What does 'consistent' mean: both true, or both possibly true together?", "Think of two false claims about the same event that could have been true together."],
    commonErrors: [{ description: "Equated consistency with truth; consistency is about whether the statements could hold together.", category: "CONCEPTUAL_ERROR", pattern: "false" }],
    transfer: 0,
    minutes: 1,
    tags: ["consistency"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Reconstruction and steelmanning (free)                             */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-31",
    skill: "argument_analysis",
    subskill: "reconstruction",
    concepts: ["argument-reconstruction", "arguments-premises-conclusions", "deduction-vs-induction"],
    level: "intermediate",
    difficulty: 3,
    format: "free",
    prompt:
      "Reconstruct the following argument in standard form: numbered premises, then the conclusion. Add any unstated premise the argument needs, mark it as unstated, and say in one sentence where the argument is weakest.\n\n\"We should not build the bypass. Every bypass built in this county in the last thirty years has filled with traffic within five years, and this one will be no different. Meanwhile the money would fund the bus network for a decade.\"",
    solution:
      "Standard form:\n1. Every bypass built in this county in the last thirty years filled with traffic within five years.\n2. (From 1, inductively) The proposed bypass will fill with traffic within five years.\n3. (Unstated) A bypass that fills with traffic within five years does not deliver the benefit it is built for.\n4. The money for the bypass would fund the bus network for a decade.\n5. (Unstated) Funding the bus network for a decade would do more good than a bypass that fails within five years.\nConclusion: We should not build the bypass.\n\nThe argument has two strands: a prediction (1 → 2) and a comparison of uses of the money (4, 5). The weakest point is the inductive step from 1 to 2, which assumes the new bypass resembles the previous ones (same traffic growth, same lack of complementary measures); the county's past record makes the prediction plausible but not certain, and a critic would ask what differs this time. Premise 5 is the value judgement doing the real work, and it is the one a defender of the bypass would contest.",
    method: "Find the conclusion, list the reasons given, then ask what must be true for those reasons to support it and write those as unstated premises. Label the inference types (inductive, evaluative) and locate the weakest link.",
    hints: ["Which sentence is the conclusion? Which sentences give reasons for it?", "The prediction that 'this one will be no different' is inferred from what? Is that inference deductive or inductive?", "What must be assumed about a road that fills with traffic, and about the bus network, for the conclusion to follow?"],
    commonErrors: [
      { description: "Treated the prediction about the new bypass as a stated fact rather than an inductive inference from the past cases.", category: "CONCEPTUAL_ERROR", pattern: "will fill" },
      { description: "Omitted the evaluative premise that connects 'fills with traffic' to 'should not build'.", category: "ASSUMPTION", pattern: "therefore we should not" },
    ],
    transfer: 0,
    keyPoints: ["conclusion|should not build", "filled|fill with traffic|five years", "inductive|generalis|past|previous|record|induction", "bus|opportunity cost|alternative use|money", "unstated|hidden|implicit|assum", "weakest|weak|this one will be no different|resemble|same"],
    rubric: [
      { criterion: "Conclusion correctly identified and stated as a claim", weight: 2 },
      { criterion: "Both strands of support (prediction from past bypasses; alternative use of funds) represented as premises", weight: 3 },
      { criterion: "At least one unstated premise supplied and marked as such, chosen charitably", weight: 3 },
      { criterion: "Weakest link named with a reason (the inductive step or the evaluative premise)", weight: 2 },
    ],
    minutes: 8,
    tags: ["reconstruction"],
    origin: "seeded",
  },
  {
    id: "it-logic-32",
    skill: "argument_analysis",
    subskill: "reconstruction",
    concepts: ["argument-reconstruction", "validity-and-soundness", "necessary-and-sufficient"],
    level: "advanced",
    difficulty: 4,
    format: "free",
    prompt:
      "Reconstruct this chained argument in standard form, showing the intermediate conclusion. Then say whether each inference is valid and which premise you would challenge first.\n\n\"Since the drug reduced symptoms in the trial, and anything that reduces symptoms should be approved, the regulator must approve it. And once it is approved, insurers will have to cover it, so patients will get it.\"",
    solution:
      "Standard form:\n1. The drug reduced symptoms in the trial.\n2. Anything that reduces symptoms should be approved.\n3. (From 1, 2) The regulator should approve the drug. [intermediate conclusion]\n4. (Unstated) If the regulator approves a drug, insurers must cover it.\n5. (Unstated) If insurers must cover a drug, patients will get it.\nConclusion: Patients will get the drug.\n\nBoth inferences are valid in form: 1 and 2 give 3 by universal instantiation (a kind of modus ponens); 3 with 4 and 5 gives the conclusion by two further modus ponens steps, once 'should approve' is read as 'will approve', which is itself a slide from an evaluative claim to a prediction. Because the form is sound, disagreement must be with a premise. Premise 2 is the one to challenge first: it makes symptom reduction sufficient for approval, when regulators also require safety, effect size, comparison with existing treatments and manufacturing quality. Premise 4 is contestable in most health systems (coverage decisions are separate from approval), and premise 5 ignores cost and supply. The argument's rhetorical force comes from hiding premises 4 and 5 inside 'will have to' and 'so'.",
    method: "Locate the final conclusion and work backwards; identify the intermediate conclusion that serves as a premise later; supply the conditionals hidden in 'once … will have to' and 'so'; then check form and content separately.",
    hints: ["There are two conclusions in this passage, one of which becomes a premise. Which?", "'Once it is approved, insurers will have to cover it' hides a conditional premise. Write it out.", "The form is a chain of modus ponens; if you reject the conclusion, which premise carries the weight?"],
    commonErrors: [
      { description: "Missed the intermediate conclusion, running everything into one list.", category: "CONCEPTUAL_ERROR", pattern: "no intermediate" },
      { description: "Called the inference invalid because a premise is doubtful; the form is valid, the premise is false.", category: "CONCEPTUAL_ERROR", pattern: "invalid" },
      { description: "Failed to notice that 'reduces symptoms' is offered as sufficient for approval.", category: "LOGIC_ERROR", pattern: "necessary" },
    ],
    transfer: 1,
    keyPoints: ["intermediate|chain|sub-conclusion|then becomes a premise|3 is used", "approve|should be approved", "insurers|cover|unstated|hidden|implicit", "valid|modus ponens|form is fine|follows", "sufficient|anything that reduces symptoms|premise 2|safety|other requirements|challenge"],
    rubric: [
      { criterion: "Intermediate conclusion identified and reused as a premise", weight: 3 },
      { criterion: "Hidden conditionals about coverage and access supplied", weight: 2 },
      { criterion: "Form correctly judged valid and the evaluation moved to the premises", weight: 2 },
      { criterion: "Premise 2 (symptom reduction as sufficient) singled out with a reason", weight: 3 },
    ],
    minutes: 10,
    examEligible: true,
    tags: ["reconstruction", "chain"],
    origin: "seeded",
  },
  {
    id: "it-logic-33",
    skill: "argument_analysis",
    subskill: "steelman",
    concepts: ["steelmanning", "argument-reconstruction"],
    level: "advanced",
    difficulty: 4,
    format: "free",
    prompt:
      "You believe that cities should build much more housing to bring prices down. Residents of a street are opposing a new six-storey block at the end of it. Steelman their position: write the strongest case they could make, in a form they would recognise as their own, before saying anything against it. Finish with one sentence naming the precise point at which you disagree.",
    solution:
      "A steelman would include most of the following. The benefits of new housing are diffuse (spread across the whole city's future buyers and renters) while the costs are concentrated on the people already living on the street: years of construction noise and traffic, loss of light and privacy, pressure on a school, surgery and drains sized for the current population. A fair process should weigh concentrated costs seriously and compensate them, and the residents have had no say in the design. They can cite evidence that new market-rate blocks in a given neighbourhood raise nearby rents in the short run even if they lower them city-wide, so the local effect may run against the city-wide one. The values underneath are stability, community and procedural fairness, not selfishness, and the residents would accept the block if the infrastructure were funded and the design consulted on. Points of agreement: the city does need housing; the current price level harms young people; blanket refusal is not a policy. What the steelman has learnt: the opposition is largely to the process and the local infrastructure, not to housing as such. The precise disagreement, then, is over whether concentrated local costs should be able to veto diffuse city-wide benefits, or only entitle residents to mitigation and compensation; the steelmanner disagrees on the veto but concedes the compensation. (Rapoport's rules as given by Dennett: restate, agree, credit, then criticise.)",
    method: "State the position as its best defenders would; supply its strongest evidence and the value it protects; record points of agreement and what you learnt; only then locate the single premise you reject.",
    hints: ["What are the residents actually protecting: their house price, or something they would say aloud?", "Concentrated costs against diffuse benefits is a structure that appears in many disputes. Does it apply here?", "After writing their case, can you name one premise you reject rather than rejecting 'the residents'?"],
    commonErrors: [
      { description: "Restated the residents' position as pure self-interest, which they would not recognise as their own.", category: "EVIDENCE_ERROR", pattern: "selfish|nimby" },
      { description: "Skipped the points of agreement and the disagreement sentence, producing a summary rather than a steelman.", category: "PRECISION_ERROR", pattern: "in conclusion" },
    ],
    transfer: 2,
    keyPoints: ["concentrated|local cost|diffuse|bear the cost", "infrastructure|school|traffic|drain|light|noise|construction", "process|consult|say|fair|procedur", "agree|common ground|need housing|both", "disagree|reject|the point at which|veto|compensat"],
    rubric: [
      { criterion: "Position restated in a form its defenders would accept, with its strongest evidence", weight: 4 },
      { criterion: "Underlying value (fairness, stability, procedure) identified rather than imputed self-interest", weight: 2 },
      { criterion: "Points of agreement and something learnt recorded", weight: 2 },
      { criterion: "Disagreement narrowed to a single named premise", weight: 2 },
    ],
    minutes: 12,
    tags: ["steelman", "housing"],
    origin: "seeded",
  },
  {
    id: "it-logic-34",
    skill: "argument_analysis",
    subskill: "steelman",
    concepts: ["steelmanning", "argument-reconstruction", "informal-fallacies"],
    level: "synthesis",
    difficulty: 5,
    format: "free",
    prompt:
      "A scientific journal proposes to refuse any paper whose underlying data cannot be shared, even where the authors have genuine reasons for confidentiality (patient records, commercial partners, endangered-species locations). You think the policy is too rigid. Steelman the journal's position, then state the one premise you would contest and what evidence would settle it.",
    solution:
      "A strong version of the journal's case: unshared data cannot be checked, and the replication record of the last two decades shows that unchecked results are unreliable often enough to damage the literature; a rule with exceptions becomes a rule with a negotiation, and editors are poorly placed to judge whether a confidentiality claim is genuine; every exception granted weakens the incentive for authors to design studies whose data can be shared (de-identification, synthetic data, restricted-access repositories); the harm of a wrong result that cannot be audited is borne by later researchers and patients who never consented to it; and the authors retain the choice of another venue, so the rule restricts the journal, not the science. Points of agreement: replication matters, and confidentiality has been used as a shield. What the steelman learns: the journal's real premise is that exceptions cannot be administered honestly at scale. The premise to contest is exactly that one. The evidence that would settle it: the experience of journals and funders that operate tiered access (restricted repositories with vetted access) and whether their exception rates and post-publication correction rates differ from those of journals with blanket rules. If tiered access works in practice, the rigid policy loses its justification; if exception rates balloon and audits fail, the journal is right.",
    method: "Build the position from its strongest premises (verification, incentives, administrability), record agreement, isolate the load-bearing premise, and specify evidence that would decide it.",
    hints: ["The journal's case is not only about this paper; think about incentives across all future authors.", "Which premise, if false, would remove the need for a blanket rule?", "What comparison between journals would test that premise?"],
    commonErrors: [
      { description: "Presented the journal as bureaucratic or hostile to science, a straw man.", category: "EVIDENCE_ERROR", pattern: "bureaucra|hostile" },
      { description: "Contested several premises at once instead of isolating the load-bearing one.", category: "PRECISION_ERROR", pattern: "several|many problems" },
    ],
    transfer: 2,
    keyPoints: ["replicat|verif|check|audit", "incentive|exception|negotiat|administ|scale", "restricted|tiered|de-identif|repository|synthetic", "agree|common ground", "evidence|would settle|test|compare"],
    rubric: [
      { criterion: "Journal's position stated at full strength, including the incentive and administrability arguments", weight: 4 },
      { criterion: "Load-bearing premise isolated", weight: 3 },
      { criterion: "Evidence that would settle the disagreement specified concretely", weight: 3 },
    ],
    minutes: 15,
    examOnly: true,
    tags: ["steelman", "science"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Exam-only items                                                    */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-35",
    skill: "logic",
    subskill: "symbolic_validity",
    concepts: ["propositional-logic", "validity-and-soundness"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt: "Premises: P → (Q ∨ R); ¬Q; P. Which conclusion follows validly from all three?",
    options: ["R", "¬R", "Q", "Nothing follows; the premises are jointly inconsistent."],
    answer: 0,
    solution:
      "From P and P → (Q ∨ R), modus ponens gives Q ∨ R. From Q ∨ R and ¬Q, disjunctive syllogism gives R. So R follows. The premises are consistent: P true, Q false, R true satisfies all three. Q is ruled out by the second premise, and ¬R is contradicted by the derivation. The exercise tests whether the learner can chain two elementary forms rather than pattern-match on a single one.",
    method: "Apply modus ponens to detach the disjunction, then disjunctive syllogism to eliminate the negated disjunct.",
    hints: ["Which two premises combine by modus ponens?", "Once you have Q ∨ R and ¬Q, what remains?"],
    commonErrors: [
      { description: "Negated the wrong disjunct.", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Ignored the premise ¬Q.", category: "MISREAD", optionIndex: 2 },
      { description: "Judged the premises inconsistent without checking an assignment.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examOnly: true,
    tags: ["symbolic"],
    origin: "seeded",
  },
  {
    id: "it-logic-36",
    skill: "logic",
    subskill: "truth_tables",
    concepts: ["propositional-logic", "conditionals-and-contrapositive"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "In the four-row truth table for P and Q, in how many rows is (P → Q) ∧ (Q → P) true?",
    answer: 2,
    tolerance: 0,
    solution:
      "(P → Q) ∧ (Q → P) is the biconditional P ↔ Q, true exactly when P and Q have the same truth value: the rows (T,T) and (F,F). In (T,F) the first conjunct fails; in (F,T) the second fails. So the answer is 2. The item checks that a conditional and its converse together pin the two statements to each other, and that neither alone does.",
    method: "Recognise the conjunction of a conditional and its converse as the biconditional, which holds when both sides agree.",
    hints: ["What does 'P → Q and Q → P' say about the relation between P and Q?", "In which rows do P and Q have the same value?"],
    commonErrors: [
      { description: "Counted the rows where P → Q alone is true.", category: "MISREAD", value: 3 },
      { description: "Counted only the row where both are true, forgetting that two false statements also agree.", category: "CONCEPTUAL_ERROR", value: 1 },
      { description: "Counted every row.", category: "CONCEPTUAL_ERROR", value: 4 },
    ],
    transfer: 0,
    minutes: 2,
    examOnly: true,
    tags: ["truth-tables", "biconditional"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Lesson support: steelmanning and consistency                       */
  /* ---------------------------------------------------------------- */
  {
    id: "it-logic-37",
    skill: "argument_analysis",
    subskill: "steelman",
    concepts: ["steelmanning", "informal-fallacies"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt:
      "A colleague argues that the team should stop estimating tasks in hours: 'The estimates are always wrong and the estimation meetings waste half a day a week.' You disagree and intend to say so. Which of these restatements of the colleague's position is a steelman?",
    options: [
      "You think estimation is pointless because you personally are not good at it and would rather skip the meetings.",
      "Hour estimates carry false precision: the error on individual tasks is large and skewed, the meetings consume a good part of the time they are meant to save, and coarser methods such as counting tasks or relative sizing have been found to forecast delivery about as well at a fraction of the cost. So we should stop unless our estimates can be shown to beat those cheaper methods.",
      "You are right that the estimates are always wrong and the meetings are a waste, so we should drop them.",
      "You think the estimates are always wrong and the meetings waste half a day a week.",
    ],
    answer: 1,
    solution:
      "Option 2 is the steelman. It keeps the colleague's two complaints, gives each its strongest form (false precision and a skewed error distribution rather than 'always wrong'; a cost that eats the benefit rather than 'a waste'), adds the best evidence available to the position (cheaper methods that forecast comparably), and states the claim as a conditional the colleague would gladly sign. Option 1 is a straw man dressed as psychology: it replaces the argument with a motive, which the colleague would not accept as their view. Option 3 is agreement, not steelmanning; a steelman is a restatement you can still argue against, and it has surrendered the disagreement. Option 4 is a faithful repetition, which is a summary: nothing has been strengthened, so refuting it refutes only the colleague's rough first wording. The test is whether the other side would say 'yes, that, and put better than I put it'.",
    method: "Check each restatement against three tests: would the holder accept it as their own; has it been made stronger, not merely repeated; does it leave a position that can still be criticised.",
    hints: ["Which restatement would the colleague accept as their view?", "Two options fail for opposite reasons: one weakens the position, one gives it up. Which are they?", "Repeating the words exactly is a summary. What does a steelman add?"],
    commonErrors: [
      { description: "Chose the restatement that imputes a motive; the holder would not recognise it, so it is a straw man.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Confused steelmanning with agreeing; a steelman leaves a position to argue against.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Took a verbatim summary for a steelman; nothing has been strengthened.", category: "PRECISION_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["steelman", "straw-man"],
    origin: "seeded",
  },
  {
    id: "it-logic-38",
    skill: "argument_analysis",
    subskill: "steelman",
    concepts: ["steelmanning", "argument-reconstruction"],
    level: "advanced",
    difficulty: 4,
    format: "free",
    prompt:
      "You are convinced that a hospital should replace its paper drug charts with an electronic prescribing system, mainly because illegible and transcribed prescriptions cause avoidable harm. The senior nurses on the wards are resisting. Write the strongest case they could make, in a form they would recognise as their own, before saying anything against it. Then name, in one sentence, the single premise you reject and why.",
    solution:
      "A steelman of the nurses' position would contain most of the following. A paper chart shows the whole patient at a glance: every drug, dose, time and signature on one sheet that can be read at the bedside, at handover and during a resuscitation, whereas a screen shows one drug at a time behind a login and several clicks. Electronic systems fail: any outage becomes a ward-wide emergency unless a paper fallback is kept current, which doubles the work. The evidence is not one-sided: electronic prescribing reduces legibility and transcription errors but introduces new ones, such as selecting the wrong patient from a list, accepting a default dose or unit, and alert fatigue from warnings that fire so often that staff learn to dismiss them; a widely cited 2005 study of a United States teaching hospital catalogued twenty-two ways its order-entry system facilitated errors. Implementation is where harm concentrates: the months of dual running, retraining and workarounds fall on nurses, not on the people who chose the system. The value underneath is patient safety as practised at the bedside, not resistance to change, and the nurses would accept a system that was fast, visible and failure-tolerant. Points of agreement: illegible prescriptions do harm; transcription is a known error source; the status quo is not safe either. What the steelman learns: the real objection is to the design and the implementation, not to computerisation. The single premise to reject is that the new error types are as frequent or as harmful as the old ones; the evidence on net medication-error rates after well-implemented systems favours the change, and that is the claim worth settling with the hospital's own incident data.",
    method: "Restate the position at full strength with its evidence and the value it protects; list agreements and what you learnt; then isolate one premise and say what evidence bears on it.",
    hints: ["What does a paper chart do well that a screen does badly? Ask a nurse, or imagine a cardiac arrest.", "What new kinds of error could a system introduce that paper could not?", "After writing their case, which one factual claim would you want to test rather than argue about?"],
    commonErrors: [
      { description: "Restated the nurses as resistant to change or technophobic; they would not recognise this as their view.", category: "EVIDENCE_ERROR", pattern: "resistant to change|technophob|luddite|afraid of" },
      { description: "Produced a list of objections without the safety value underneath them, so the position looks like complaint rather than argument.", category: "PRECISION_ERROR", pattern: "they just|complain" },
      { description: "Ended without narrowing the disagreement to a single premise.", category: "PRECISION_ERROR", pattern: "in conclusion|overall" },
    ],
    transfer: 2,
    keyPoints: ["glance|whole chart|bedside|handover|one sheet|visible", "outage|downtime|fail|fallback|paper backup", "new error|wrong patient|default|alert fatigue|unit|click", "implement|training|workaround|dual running|burden", "safety|patient|value", "agree|common ground|illegible|transcription", "reject|premise|disagree|evidence|incident data"],
    rubric: [
      { criterion: "Position restated in a form the nurses would accept, including what paper does well and what screens do badly", weight: 3 },
      { criterion: "New error types and failure modes of electronic systems identified as evidence for the position", weight: 3 },
      { criterion: "Underlying value (bedside safety) identified rather than resistance imputed; agreements recorded", weight: 2 },
      { criterion: "Disagreement narrowed to one premise with the evidence that would bear on it", weight: 2 },
    ],
    minutes: 12,
    tags: ["steelman", "healthcare"],
    origin: "seeded",
  },
  {
    id: "it-logic-39",
    skill: "logic",
    subskill: "consistency",
    concepts: ["contradiction-and-consistency"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt:
      "A company's annual plan contains four commitments. Take revenue to be number of customers × units bought per customer × price per unit.\n(a) The price of every unit we sell will be unchanged.\n(b) Revenue will grow by 20 %.\n(c) We will not increase the number of customers we serve, to protect service quality.\n(d) No customer will buy more units than they do today.\nWhich is the smallest set of these commitments that cannot all be kept together?",
    options: ["(a) and (b)", "(b), (c) and (d)", "(a), (b) and (c)", "All four together, and no smaller set"],
    answer: 3,
    solution:
      "Revenue has three factors. Commitment (a) fixes price, (c) caps the number of customers and (d) caps units per customer. Any two of those caps leave one factor free: with (a) and (c), revenue can grow if customers buy more; with (a) and (d), if more customers arrive; with (c) and (d), if prices rise. So (a) and (b), (b) with (c) and (d), and (a), (b) and (c) are each consistent, because each leaves a route to 20 % growth. Only when all three caps hold at once is revenue fixed, and then (b) cannot be met. The inconsistency lives in the set as a whole, not in any pair, which is exactly why it survives in documents: each commitment is examined and approved on its own, and nobody puts the four side by side. The remedy is the consistency check itself: write the quantities down and ask whether a single situation satisfies every line.",
    method: "Express the constrained quantity as a product of its factors, note which commitments cap which factor, and find the smallest set of caps that leaves no factor free while a growth target remains.",
    hints: ["Revenue is a product of three factors. Which commitment caps which factor?", "For each candidate set, ask: is there still a factor that could grow?", "How many of the three factors must be capped before 20 % growth becomes impossible?"],
    commonErrors: [
      { description: "Assumed a price freeze alone rules out revenue growth; customers or volume could still rise.", category: "LOGIC_ERROR", optionIndex: 0 },
      { description: "Overlooked that price is still free to rise when (a) is not in the set.", category: "MISREAD", optionIndex: 1 },
      { description: "Overlooked that existing customers could buy more units when (d) is not in the set.", category: "LOGIC_ERROR", optionIndex: 2 },
    ],
    transfer: 2,
    minutes: 4,
    examEligible: true,
    tags: ["consistency", "strategy"],
    origin: "seeded",
  },
];
