/**
 * Practice items for mathematics. Ids: it-mathematics-<nn>. British spelling throughout.
 *
 * Numeric items carry a tolerance; mcq distractors encode real misconceptions and are mapped
 * to error categories in `commonErrors`. Items marked `examOnly` never appear in Train and
 * are not referenced by lessons.
 */
import type { PracticeItem } from "@/lib/v2/content-types";

type Draft = Omit<PracticeItem, "id" | "skill" | "origin">;

function item(n: number, draft: Draft): PracticeItem {
  return { id: `it-mathematics-${String(n).padStart(2, "0")}`, skill: "mathematics", origin: "seeded", ...draft };
}

export const ITEMS_MATHEMATICS: PracticeItem[] = [
  /* ---------------- Number sense ---------------- */
  item(1, {
    subskill: "mental_arithmetic",
    concepts: ["number-sense"],
    level: "foundation",
    difficulty: 1,
    format: "numeric",
    prompt: "A concert hall has 42 rows of 38 seats. Without a calculator, find the exact number of seats.",
    answer: 1596,
    tolerance: 0,
    solution:
      "Round to a convenient centre: 42 = 40 + 2 and 38 = 40 − 2. Then (40 + 2)(40 − 2) = 40² − 2² = 1600 − 4 = 1596. The estimate 'about 1,600' comes first and the exact answer confirms it; an answer of 1,604 would mean the correction went the wrong way.",
    method: "Estimate with a round number, then apply the difference of squares (a + b)(a − b) = a² − b² to correct.",
    hints: ["Both numbers are close to 40.", "Write 42 as 40 + 2 and 38 as 40 − 2, then expand.", "(a + b)(a − b) = a² − b²; the correction is subtracted."],
    commonErrors: [
      { description: "Added the correction instead of subtracting it: 1600 + 4", category: "ALGEBRA_ERROR", value: 1604 },
      { description: "Multiplied 40 × 38 and forgot the extra two rows", category: "MISREAD", value: 1520 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["estimation"],
  }),
  item(2, {
    subskill: "plausibility_check",
    concepts: ["number-sense", "units-and-dimensional-analysis"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt:
      "A report states that a country's 5.1 million households consumed 1.7 billion kWh of electricity last year. What does the implied consumption per household tell you?",
    options: [
      "About 330 kWh per household, which is far below typical annual use (a few thousand kWh), so a figure in the report is probably wrong or mislabelled",
      "About 3,300 kWh per household, which is plausible for a year",
      "About 330 kWh per household, which is plausible for a year",
      "About 33 kWh per household, which is implausibly low",
    ],
    answer: 0,
    solution:
      "1.7 × 10⁹ ÷ 5.1 × 10⁶ ≈ 0.333 × 10³ = 333 kWh. A European household uses roughly 3,000–4,000 kWh a year and an American one around 10,000, so 333 kWh is an order of magnitude too low. The arithmetic is right; the report is not. Perhaps the figure is monthly, or in GWh, or for one region.",
    method: "Do the division in scientific notation, then compare the result with a reference quantity you know before accepting it.",
    hints: ["Write both numbers as powers of ten before dividing.", "1.7 ÷ 5.1 is about one third; 10⁹ ÷ 10⁶ is 10³.", "Is a few hundred kWh a year believable for a household with a fridge, lighting and a washing machine?"],
    commonErrors: [
      { description: "Decimal-place slip: 10⁹ ÷ 10⁶ treated as 10⁴", category: "ALGEBRA_ERROR", optionIndex: 1 },
      { description: "Correct arithmetic but no plausibility check against a reference quantity", category: "KNOWLEDGE_GAP", optionIndex: 2 },
      { description: "Decimal-place slip in the other direction", category: "ALGEBRA_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["estimation", "sanity-check"],
  }),

  /* ---------------- Fractions, ratios, percentages ---------------- */
  item(3, {
    subskill: "successive_percentages",
    concepts: ["fractions-ratios-percentages"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A share price rises 40 % in one year and falls 30 % the next. What is the net percentage change over the two years? Give a negative number for a fall.",
    answer: -2,
    tolerance: 0.5,
    unit: "%",
    solution:
      "Percentage changes multiply. Start at 100: after +40 % the price is 140; after −30 % of 140 it is 140 × 0.7 = 98. The net change is 98 − 100 = −2, a 2 % fall. Adding the percentages (+10 %) ignores that the 30 % is taken from a larger base.",
    method: "Convert each change to a multiplier (1.4 and 0.7), multiply them, and read the net change from the product.",
    hints: ["Try it with a starting price of 100.", "The 30 % fall is 30 % of the new, higher price.", "Multiply 1.4 by 0.7."],
    commonErrors: [
      { description: "Added the percentages: +40 − 30 = +10", category: "CONCEPTUAL_ERROR", value: 10 },
      { description: "Gave the fall with the wrong sign", category: "ALGEBRA_ERROR", value: 2 },
      { description: "Reported the multiplier gap as a fraction (0.02) instead of a percentage", category: "PRECISION_ERROR", value: -0.02 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["percentages"],
  }),
  item(4, {
    subskill: "percentage_points",
    concepts: ["fractions-ratios-percentages", "rates-of-change"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "The unemployment rate rises from 4 % to 5 %. By what percent did the unemployment rate rise?",
    answer: 25,
    tolerance: 0.5,
    unit: "%",
    solution:
      "The rise is one percentage point, but the question asks for the relative change: (5 − 4) ÷ 4 = 0.25, a 25 % increase. Headlines that say 'unemployment up 1 %' and 'unemployment up 25 %' can describe the same event; the first is in points, the second in percent of the base.",
    method: "Relative change = (new − old) ÷ old, expressed as a percentage.",
    hints: ["The difference between the two rates is not the answer; that is percentage points.", "Relative change compares the difference with the starting value.", "Divide 1 by 4."],
    commonErrors: [
      { description: "Reported the percentage-point difference as a percent", category: "PRECISION_ERROR", value: 1 },
      { description: "Left the answer as a fraction (0.25) instead of a percentage", category: "PRECISION_ERROR", value: 0.25 },
      { description: "Divided by the new value instead of the old", category: "CONCEPTUAL_ERROR", value: 20 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["percentages"],
  }),
  item(5, {
    subskill: "ratios",
    concepts: ["fractions-ratios-percentages"],
    level: "foundation",
    difficulty: 1,
    format: "numeric",
    prompt: "A shortbread recipe uses flour, sugar and butter in the ratio 5 : 3 : 2 by mass. How many grams of sugar are in 1.5 kg of the mixture?",
    answer: 450,
    tolerance: 1,
    unit: "g",
    solution:
      "The ratio has 5 + 3 + 2 = 10 parts, so one part is 1,500 g ÷ 10 = 150 g. Sugar is 3 parts: 3 × 150 = 450 g. Check: flour 750 g, sugar 450 g, butter 300 g, total 1,500 g.",
    method: "Add the ratio parts to find the size of one part of the total, then multiply by the parts for the ingredient asked.",
    hints: ["How many parts are there in total?", "1.5 kg is 1,500 g; divide by the number of parts.", "Sugar is 3 of those parts."],
    commonErrors: [
      { description: "Took 3/5 of the total (ratio to flour, not to the whole)", category: "CONCEPTUAL_ERROR", value: 900 },
      { description: "Read the butter share instead of the sugar share", category: "MISREAD", value: 300 },
      { description: "Split the total equally between three ingredients", category: "CONCEPTUAL_ERROR", value: 500 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["ratios"],
  }),
  item(6, {
    subskill: "reverse_percentage",
    concepts: ["fractions-ratios-percentages", "algebraic-manipulation"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "After a 15 % discount, a jacket costs £51. What was the original price in pounds?",
    answer: 60,
    tolerance: 0.05,
    unit: "£",
    solution:
      "A 15 % discount leaves 85 % of the original, so 0.85 × original = 51 and original = 51 ÷ 0.85 = 60. Adding 15 % of £51 back (£58.65) fails because the 15 % was taken from the original £60, not from £51. Check: 60 × 0.85 = 51.",
    method: "Write the sale price as multiplier × original, then divide by the multiplier to undo the change.",
    hints: ["What fraction of the original price is left after the discount?", "0.85 × original = 51.", "Divide, do not add the percentage back."],
    commonErrors: [
      { description: "Added 15 % of the sale price back: 51 × 1.15", category: "CONCEPTUAL_ERROR", value: 58.65 },
      { description: "Applied the discount again instead of undoing it", category: "MISREAD", value: 43.35 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["percentages"],
  }),

  /* ---------------- Orders of magnitude ---------------- */
  item(7, {
    subskill: "scientific_notation",
    concepts: ["orders-of-magnitude"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Without a calculator, about how many seconds are there in a year?",
    options: ["About 3 × 10⁵", "About 5 × 10⁵", "About 3 × 10⁷", "About 3 × 10⁹"],
    answer: 2,
    solution:
      "60 s × 60 min × 24 h × 365 days. Group the factors: 60 × 60 = 3,600 ≈ 3.6 × 10³; × 24 ≈ 8.6 × 10⁴; × 365 ≈ 3.15 × 10⁷. A useful anchor: a year is about π × 10⁷ seconds. Dropping a factor of 60 gives 5 × 10⁵ (the number of minutes in a year).",
    method: "Multiply the conversion factors in scientific notation, tracking the exponent separately from the leading digits.",
    hints: ["Start from seconds per minute, minutes per hour, hours per day, days per year.", "60 × 60 × 24 is 86,400 seconds in a day.", "86,400 × 365 is a little over 3 × 10⁷."],
    commonErrors: [
      { description: "Dropped two factors (the number of hours in a year)", category: "ALGEBRA_ERROR", optionIndex: 0 },
      { description: "Dropped one factor of 60 (the number of minutes in a year)", category: "ALGEBRA_ERROR", optionIndex: 1 },
      { description: "Overshot by two orders of magnitude", category: "PRECISION_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["estimation"],
  }),
  item(8, {
    subskill: "scientific_notation",
    concepts: ["orders-of-magnitude", "units-and-dimensional-analysis"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "The Sun is about 1.5 × 10⁸ km from Earth and light travels at about 3 × 10⁵ km per second. How many minutes does sunlight take to reach Earth?",
    answer: 8.33,
    tolerance: 0.2,
    unit: "min",
    solution:
      "Time = distance ÷ speed = 1.5 × 10⁸ km ÷ 3 × 10⁵ km/s = 0.5 × 10³ s = 500 s. Convert: 500 ÷ 60 ≈ 8.3 minutes. The kilometres cancel, leaving seconds, which the question asks to be converted. With the more precise values 1.496 × 10⁸ km and 2.998 × 10⁵ km/s the answer is 8.32 minutes.",
    method: "Divide in scientific notation, cancel the units, then convert the remaining unit to the one requested.",
    hints: ["Time equals distance divided by speed.", "1.5 ÷ 3 = 0.5 and 10⁸ ÷ 10⁵ = 10³.", "The result is in seconds; the question asks for minutes."],
    commonErrors: [
      { description: "Left the answer in seconds", category: "PRECISION_ERROR", value: 500 },
      { description: "Decimal-place slip in the division", category: "ALGEBRA_ERROR", value: 83.3 },
      { description: "Converted to hours instead of minutes", category: "MISREAD", value: 0.139 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["units"],
  }),
  item(9, {
    subskill: "logarithmic_scales",
    concepts: ["orders-of-magnitude", "exponents-and-logarithms"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "On the moment-magnitude scale used for earthquakes, each whole-number step multiplies the measured ground-motion amplitude by 10. How many times larger is the amplitude of a magnitude 7 earthquake than a magnitude 5 one?",
    answer: 100,
    tolerance: 1,
    solution:
      "Two steps of magnitude means two multiplications by 10: 10 × 10 = 10² = 100. The scale is logarithmic, so equal steps are equal factors, not equal amounts. The energy released grows by roughly 31.6 per step, so the energy ratio is about 1,000; that is a different quantity from amplitude.",
    method: "On a logarithmic scale, convert the difference in scale units into a power of the base: 10^(difference).",
    hints: ["The scale is logarithmic, not linear.", "Each step is a factor of 10; how many steps?", "10 to the power of the number of steps."],
    commonErrors: [
      { description: "Treated the scale as linear: 7 ÷ 5 or 7 − 5", category: "CONCEPTUAL_ERROR", value: 2 },
      { description: "Gave the energy ratio (about 1,000) instead of the amplitude ratio", category: "MISREAD", value: 1000 },
      { description: "Added instead of multiplying the factors", category: "CONCEPTUAL_ERROR", value: 20 },
    ],
    transfer: 2,
    minutes: 2,
    examEligible: true,
    tags: ["logarithms"],
  }),

  /* ---------------- Units and dimensional analysis ---------------- */
  item(10, {
    subskill: "unit_conversion",
    concepts: ["units-and-dimensional-analysis", "fractions-ratios-percentages"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A car uses 6.5 litres of fuel per 100 km. It has 32 litres in the tank. How many kilometres can it travel before the tank is empty?",
    answer: 492,
    tolerance: 5,
    unit: "km",
    solution:
      "Write the consumption as a ratio with units: 6.5 L / 100 km. Distance = 32 L ÷ (6.5 L / 100 km) = 32 × 100 / 6.5 km ≈ 492 km. The litres cancel and kilometres remain, which is the check that the ratio was used the right way up. Multiplying 32 × 6.5 gives litres squared per hundred kilometres, which is not a distance.",
    method: "Set up the ratio with units, arrange it so the unwanted unit cancels, and let the surviving unit confirm the direction.",
    hints: ["Which way up must the ratio go for litres to cancel?", "Kilometres per litre is 100 ÷ 6.5.", "Multiply the litres in the tank by kilometres per litre."],
    commonErrors: [
      { description: "Inverted the ratio: 32 × 6.5", category: "CONCEPTUAL_ERROR", value: 208 },
      { description: "Forgot the 'per 100 km' factor", category: "PRECISION_ERROR", value: 4.92 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["units"],
  }),
  item(11, {
    subskill: "unit_conversion",
    concepts: ["units-and-dimensional-analysis", "geometry-and-scale"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A tap delivers 0.25 litres per second into an empty rectangular tank measuring 1.2 m by 0.8 m by 0.5 m. How many minutes does it take to fill?",
    answer: 32,
    tolerance: 0.5,
    unit: "min",
    solution:
      "Volume = 1.2 × 0.8 × 0.5 = 0.48 m³. One cubic metre is 1,000 litres, so the tank holds 480 L. Time = 480 L ÷ 0.25 L/s = 1,920 s. Convert to minutes: 1,920 ÷ 60 = 32 minutes. Two unit conversions (m³ to L, s to min) sit between the data and the answer; each is a factor a careless solution drops.",
    method: "Compute the volume, convert to the flow-rate's volume unit, divide by the rate, then convert the time unit.",
    hints: ["Find the volume in cubic metres first.", "1 m³ = 1,000 L.", "The division gives seconds; the question wants minutes."],
    commonErrors: [
      { description: "Left the answer in seconds", category: "PRECISION_ERROR", value: 1920 },
      { description: "Forgot that a cubic metre is 1,000 litres", category: "PRECISION_ERROR", value: 0.032 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["units", "volume"],
  }),
  item(12, {
    subskill: "dimensional_analysis",
    concepts: ["units-and-dimensional-analysis"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A pendulum of length L (metres) swings under gravity g (metres per second squared). Which of these formulae for its period T (seconds) could be dimensionally correct?",
    options: ["T = 2π √(L / g)", "T = 2π L / g", "T = 2π √(L g)", "T = 2π g / L"],
    answer: 0,
    solution:
      "Check the units of each candidate. L / g has units m ÷ (m/s²) = s², so its square root has units of seconds: T = 2π √(L/g) is consistent (and is in fact the small-angle formula). L / g alone gives s², √(Lg) gives √(m²/s²) = m/s, and g / L gives 1/s². Only the first can be a time. Dimensional analysis cannot supply the 2π, but it rules out three of four formulae without any physics.",
    method: "Substitute the units of each symbol into each formula and keep only those whose units match the quantity being described.",
    hints: ["Replace each symbol with its units: L → m, g → m/s².", "What are the units of L ÷ g?", "A square root halves the exponents on the units."],
    commonErrors: [
      { description: "Accepted L / g, which has units of seconds squared", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Accepted √(Lg), which has units of speed", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Accepted g / L, which has units of 1 / s²", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["units", "physics"],
  }),

  /* ---------------- Algebraic manipulation ---------------- */
  item(13, {
    subskill: "factorising",
    concepts: ["algebraic-manipulation"],
    level: "basic",
    difficulty: 2,
    format: "short",
    prompt: "Simplify (x² − 9) / (x − 3) for x ≠ 3.",
    answer: "x + 3",
    accept: ["x+3", "3 + x", "3+x", "(x + 3)", "(x+3)"],
    solution:
      "x² − 9 is a difference of squares: (x − 3)(x + 3). The fraction becomes (x − 3)(x + 3) / (x − 3), and the common factor (x − 3) cancels, leaving x + 3. Cancelling the x's alone (to get −9 / −3 = 3) is not allowed: cancellation applies to factors of the whole numerator and denominator, not to individual terms.",
    method: "Factorise numerator and denominator fully, then cancel common factors.",
    hints: ["x² − 9 is a difference of two squares.", "a² − b² = (a − b)(a + b).", "One factor of the numerator matches the denominator."],
    commonErrors: [
      { description: "Cancelled terms instead of factors, leaving x − 3 or a constant", category: "ALGEBRA_ERROR", pattern: "x - 3" },
      { description: "Cancelled only the x, leaving an x² term", category: "ALGEBRA_ERROR", pattern: "x^2" },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["algebra"],
  }),
  item(14, {
    subskill: "order_of_operations",
    concepts: ["algebraic-manipulation", "number-sense"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "Evaluate 8 − 2 × (1 − 4)² ÷ 3.",
    answer: 2,
    tolerance: 0,
    solution:
      "Brackets first: 1 − 4 = −3. Then the power: (−3)² = 9, positive because a negative squared is positive. Then multiplication and division left to right: 2 × 9 = 18, 18 ÷ 3 = 6. Finally the subtraction: 8 − 6 = 2. Working left to right from the start gives 18; treating (−3)² as −9 gives 14; subtracting before dividing gives −3⅓.",
    method: "Apply the order of operations strictly: brackets, powers, multiplication and division left to right, then addition and subtraction.",
    hints: ["Evaluate inside the bracket first.", "Squaring a negative number gives a positive.", "Do the multiplication and division before the subtraction."],
    commonErrors: [
      { description: "Treated (−3)² as −9, a sign error", category: "ALGEBRA_ERROR", value: 14 },
      { description: "Worked left to right, ignoring the order of operations", category: "ALGEBRA_ERROR", value: 18 },
      { description: "Subtracted before dividing", category: "ALGEBRA_ERROR", value: -3.33 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["algebra"],
  }),
  item(15, {
    subskill: "rearranging_formulae",
    concepts: ["algebraic-manipulation", "units-and-dimensional-analysis"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "The equation v² = u² + 2as relates final speed v, initial speed u, acceleration a and distance s. Rearrange it to find a, then evaluate with v = 20, u = 8 and s = 42 (SI units).",
    answer: 4,
    tolerance: 0.05,
    solution:
      "Subtract u² from both sides: v² − u² = 2as. Divide by 2s: a = (v² − u²) / (2s). Substitute: (400 − 64) / (2 × 42) = 336 / 84 = 4 m/s². Note that v² − u² is not (v − u)²: 400 − 64 = 336 while (20 − 8)² = 144.",
    method: "Isolate the unknown by undoing the operations around it in reverse order, then substitute values only at the end.",
    hints: ["Move u² to the other side first.", "Then divide by everything multiplying a.", "Square each speed separately before subtracting."],
    commonErrors: [
      { description: "Dropped the factor 2 when dividing", category: "ALGEBRA_ERROR", value: 8 },
      { description: "Added u² instead of subtracting it", category: "ALGEBRA_ERROR", value: 5.52 },
      { description: "Used (v − u)² instead of v² − u²", category: "ALGEBRA_ERROR", value: 1.71 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["algebra", "physics"],
  }),
  item(16, {
    subskill: "algebraic_laws",
    concepts: ["algebraic-manipulation"],
    level: "foundation",
    difficulty: 1,
    format: "short",
    prompt: "Which law of arithmetic justifies rewriting a(b + c) as ab + ac? Give its name.",
    answer: "distributive",
    accept: ["distributive law", "distributivity", "distributive property", "the distributive law", "the distributive property", "distribution"],
    solution:
      "The distributive law: multiplication distributes over addition, so a(b + c) = ab + ac. Read left to right it expands brackets; read right to left it factorises. The commutative law (ab = ba) and the associative law ((ab)c = a(bc)) concern the order and grouping of one operation, not the interaction of two.",
    method: "Recall the three basic laws (commutative, associative, distributive) and match the one that links multiplication to addition.",
    hints: ["It is the law about brackets.", "Multiplication is spread across the terms inside the bracket.", "Its name begins with 'd'."],
    commonErrors: [
      { description: "Named the commutative law, which concerns order, not brackets", category: "KNOWLEDGE_GAP", pattern: "commutative" },
      { description: "Named the associative law, which concerns grouping of one operation", category: "KNOWLEDGE_GAP", pattern: "associative" },
    ],
    transfer: 0,
    minutes: 1,
    tags: ["algebra"],
  }),

  /* ---------------- Linear equations ---------------- */
  item(17, {
    subskill: "break_even",
    concepts: ["linear-equations", "functions-and-graphs"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "Mobile plan A costs £12 a month plus 5p per minute of calls. Plan B costs £20 a month plus 2p per minute. At how many minutes per month do the two plans cost the same?",
    answer: 266.67,
    tolerance: 1,
    unit: "min",
    solution:
      "Let m be the minutes. Plan A: 12 + 0.05m. Plan B: 20 + 0.02m. Set them equal: 12 + 0.05m = 20 + 0.02m. Subtract 0.02m and 12 from both sides: 0.03m = 8, so m = 8 / 0.03 ≈ 266.7 minutes. Below that, A is cheaper; above it, B. Adding the rates (0.07) instead of subtracting them gives 114, which would mean the plans converge faster than they actually do.",
    method: "Write each cost as a linear function of usage, set them equal, and solve for the usage.",
    hints: ["Write the monthly cost of each plan as a formula in m.", "Set the two formulae equal.", "Collect the m terms on one side: the difference in per-minute rates is 3p."],
    commonErrors: [
      { description: "Added the per-minute rates instead of subtracting them", category: "ALGEBRA_ERROR", value: 114.29 },
      { description: "Ignored plan B's per-minute charge", category: "MISREAD", value: 160 },
      { description: "Divided the fixed-fee gap by plan B's rate only", category: "MISREAD", value: 400 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["algebra", "break-even"],
  }),
  item(18, {
    subskill: "simultaneous_equations",
    concepts: ["linear-equations"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A theatre sells adult tickets at £9 and child tickets at £4. One evening it sells 130 tickets for a total of £815. How many adult tickets were sold?",
    answer: 59,
    tolerance: 0,
    solution:
      "Let a be adult and c be child tickets. Then a + c = 130 and 9a + 4c = 815. From the first, c = 130 − a. Substitute: 9a + 4(130 − a) = 815, so 9a + 520 − 4a = 815, 5a = 295, a = 59. Then c = 71. Check: 9 × 59 + 4 × 71 = 531 + 284 = 815.",
    method: "Write one equation for the count and one for the revenue, eliminate one unknown by substitution, and check the solution in both equations.",
    hints: ["Two unknowns need two equations: one for tickets, one for money.", "Express the child count in terms of the adult count.", "Substitute into the revenue equation and solve."],
    commonErrors: [
      { description: "Reported the number of child tickets", category: "MISREAD", value: 71 },
      { description: "Assumed an equal split", category: "ASSUMPTION", value: 65 },
      { description: "Divided the revenue by the adult price, ignoring children", category: "MISREAD", value: 90.6 },
    ],
    transfer: 0,
    minutes: 3,
    examOnly: true,
    tags: ["algebra", "systems"],
  }),

  /* ---------------- Inequalities ---------------- */
  item(19, {
    subskill: "solving_inequalities",
    concepts: ["inequalities", "algebraic-manipulation"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Solve the inequality −3x + 7 > 22.",
    options: ["x < −5", "x > −5", "x < 5", "x > 5"],
    answer: 0,
    solution:
      "Subtract 7: −3x > 15. Divide by −3, which reverses the inequality: x < −5. Check with x = −6: −3(−6) + 7 = 25 > 22, true; with x = −4: 12 + 7 = 19, false. The direction flips only at the division by a negative; the earlier subtraction leaves it alone.",
    method: "Isolate x as for an equation, reversing the inequality sign whenever both sides are multiplied or divided by a negative number.",
    hints: ["Move the 7 first.", "You will divide by a negative number.", "Dividing by a negative reverses the direction; test a value to confirm."],
    commonErrors: [
      { description: "Did not reverse the inequality when dividing by −3", category: "ALGEBRA_ERROR", optionIndex: 1 },
      { description: "Lost the sign of the solution", category: "ALGEBRA_ERROR", optionIndex: 2 },
      { description: "Lost the sign and failed to reverse", category: "ALGEBRA_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["algebra"],
  }),
  item(20, {
    subskill: "constraints",
    concepts: ["inequalities", "fractions-ratios-percentages"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A freelancer needs at least £2,400 net each month. She charges £45 an hour, and 22 % of what she bills goes to tax and costs. What is the minimum number of whole hours she must bill?",
    answer: 69,
    tolerance: 0,
    unit: "hours",
    solution:
      "Net income per hour is 45 × (1 − 0.22) = £35.10. The constraint is 35.1h ≥ 2,400, so h ≥ 2,400 / 35.1 ≈ 68.4. Hours are whole and the requirement is a minimum, so round up: 69 hours (68 hours gives £2,386.80, short of the target). Dividing 45 by 1.22 instead of multiplying by 0.78 uses the wrong base for the 22 %.",
    method: "Convert the percentage to a net rate, write the requirement as an inequality, solve, and round in the direction the inequality demands.",
    hints: ["Work out how much of each £45 she keeps.", "Set net rate × hours ≥ 2,400.", "68.4 hours is not enough; a minimum is rounded up."],
    commonErrors: [
      { description: "Rounded down; 68 hours does not meet the minimum", category: "CONCEPTUAL_ERROR", value: 68 },
      { description: "Ignored the 22 % deduction", category: "MISREAD", value: 54 },
      { description: "Divided by 1.22 instead of multiplying by 0.78", category: "CONCEPTUAL_ERROR", value: 66 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["algebra", "percentages"],
  }),

  /* ---------------- Exponents and logarithms ---------------- */
  item(21, {
    subskill: "doubling_time",
    concepts: ["exponents-and-logarithms", "linear-vs-exponential-growth"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "An investment grows 6 % a year, compounded annually. How many years does it take to double? Give the answer to one decimal place (the rule-of-70 approximation is accepted).",
    answer: 11.9,
    tolerance: 0.3,
    unit: "years",
    solution:
      "Doubling means 1.06ⁿ = 2. Take logarithms: n ln 1.06 = ln 2, so n = 0.6931 / 0.05827 ≈ 11.9 years. The rule of 70 gives 70 / 6 ≈ 11.7 and the rule of 72 gives 12.0, both close. Linear thinking (100 / 6 ≈ 16.7 years) ignores the growth earned on earlier growth.",
    method: "Set (1 + r)ⁿ = 2 and solve with logarithms, or apply the rule of 70 as an approximation.",
    hints: ["Write the doubling condition as an equation in n.", "Logarithms bring the exponent down: n × ln(1.06) = ln(2).", "Or use 70 ÷ 6."],
    commonErrors: [
      { description: "Treated growth as linear: 100 ÷ 6", category: "CONCEPTUAL_ERROR", value: 16.67 },
      { description: "Halved the linear estimate without justification", category: "CONCEPTUAL_ERROR", value: 8.33 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["growth", "logarithms"],
  }),
  item(22, {
    subskill: "log_rules",
    concepts: ["exponents-and-logarithms"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "Evaluate log₁₀(1000) − log₁₀(0.01) + 2⁻³ × 8.",
    answer: 6,
    tolerance: 0,
    solution:
      "log₁₀(1000) = 3 because 10³ = 1000. log₁₀(0.01) = −2 because 10⁻² = 0.01. 2⁻³ = 1/8, so 2⁻³ × 8 = 1. Then 3 − (−2) + 1 = 6. The two traps are the sign of log(0.01) (subtracting a negative adds) and the negative exponent (a reciprocal, not a negative number).",
    method: "Evaluate each logarithm as 'ten to what power?', treat negative exponents as reciprocals, then combine.",
    hints: ["To what power must 10 be raised to give 0.01?", "A negative exponent means one over the power.", "Subtracting a negative number adds."],
    commonErrors: [
      { description: "Took log(0.01) as +2, losing the sign", category: "ALGEBRA_ERROR", value: 2 },
      { description: "Treated 2⁻³ as −8", category: "ALGEBRA_ERROR", value: -59 },
      { description: "Dropped the final term", category: "MISREAD", value: 5 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["logarithms"],
  }),
  item(23, {
    subskill: "log_rules",
    concepts: ["exponents-and-logarithms"],
    level: "basic",
    difficulty: 2,
    format: "true_false",
    prompt: "For positive numbers a and b, log(a + b) = log a + log b.",
    answer: "false",
    solution:
      "False. The rule is log(ab) = log a + log b: logarithms turn multiplication into addition. There is no rule that splits the logarithm of a sum. Check with a = b = 10: log(20) ≈ 1.30, while log 10 + log 10 = 2. The confusion comes from applying a rule about products to a sum.",
    method: "Test a suspected identity with concrete numbers before trusting it; recall which operation logarithms convert.",
    hints: ["Which operation do logarithms turn into addition?", "Try a = b = 10.", "log(ab), not log(a + b), equals log a + log b."],
    commonErrors: [{ description: "Confused the product rule log(ab) = log a + log b with a rule for sums", category: "CONCEPTUAL_ERROR" }],
    transfer: 0,
    minutes: 1,
    examEligible: true,
    tags: ["logarithms"],
  }),

  /* ---------------- Quadratics ---------------- */
  item(24, {
    subskill: "solving_quadratics",
    concepts: ["quadratics", "functions-and-graphs"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A ball is thrown upwards and its height in metres after t seconds is h(t) = 20t − 5t². After how many seconds does it return to the ground (t > 0)?",
    answer: 4,
    tolerance: 0.01,
    unit: "s",
    solution:
      "On the ground h = 0: 20t − 5t² = 0. Factorise: 5t(4 − t) = 0, so t = 0 (the throw) or t = 4 (the landing). The question asks for t > 0, so the answer is 4 seconds. The peak is at t = 2 (halfway, by symmetry) at a height of 20 m; neither of those is what was asked.",
    method: "Set the function equal to the target value, factorise, and select the root the question asks for.",
    hints: ["Height zero means h(t) = 0.", "Both terms contain t; factorise it out.", "One root is the moment of the throw; the other is the landing."],
    commonErrors: [
      { description: "Gave the time of maximum height", category: "MISREAD", value: 2 },
      { description: "Gave the maximum height instead of a time", category: "MISREAD", value: 20 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["quadratics"],
  }),
  item(25, {
    subskill: "solving_quadratics",
    concepts: ["quadratics", "geometry-and-scale"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A rectangular garden has an area of 84 m² and its length is 5 m more than its width. What is the width in metres?",
    answer: 7,
    tolerance: 0.01,
    unit: "m",
    solution:
      "Let the width be w; the length is w + 5. Area: w(w + 5) = 84, so w² + 5w − 84 = 0. Two numbers with product −84 and sum 5 are 12 and −7: (w + 12)(w − 7) = 0. The roots are −12 and 7; a width cannot be negative, so w = 7 m and the length is 12 m. Check: 7 × 12 = 84.",
    method: "Translate the words into a quadratic, factorise, and reject the root that has no physical meaning, stating why.",
    hints: ["Call the width w and write the length in terms of w.", "Area is width × length; set it equal to 84.", "Find two numbers that multiply to −84 and add to 5."],
    commonErrors: [
      { description: "Reported the magnitude of the rejected negative root, which is the length", category: "CONCEPTUAL_ERROR", value: 12 },
      { description: "Kept the negative root", category: "CONCEPTUAL_ERROR", value: -12 },
      { description: "Divided the area by the difference in sides", category: "MISREAD", value: 16.8 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["quadratics"],
  }),
  item(26, {
    subskill: "discriminant",
    concepts: ["quadratics"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "For which value of k does x² + 6x + k = 0 have exactly one real solution?",
    options: ["k = 9", "k = 3", "k = −9", "k = 36"],
    answer: 0,
    solution:
      "A quadratic has exactly one real root when its discriminant b² − 4ac is zero. Here a = 1, b = 6, c = k: 36 − 4k = 0, so k = 9. Equivalently, x² + 6x + 9 = (x + 3)², a perfect square with the single root x = −3. Taking k = 36 forgets the factor 4; k = 3 halves b instead of halving and squaring it.",
    method: "Set the discriminant b² − 4ac to zero and solve for the unknown coefficient, or complete the square.",
    hints: ["How many roots a quadratic has depends on b² − 4ac.", "One root means the discriminant is zero.", "36 − 4k = 0."],
    commonErrors: [
      { description: "Halved b but did not square it", category: "ALGEBRA_ERROR", optionIndex: 1 },
      { description: "Sign error in solving 36 − 4k = 0", category: "ALGEBRA_ERROR", optionIndex: 2 },
      { description: "Used b² alone, forgetting the 4ac", category: "ALGEBRA_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examOnly: true,
    tags: ["quadratics"],
  }),

  /* ---------------- Functions and graphs ---------------- */
  item(27, {
    subskill: "composition",
    concepts: ["functions-and-graphs"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "If f(x) = 2x + 1 and g(x) = x², what is f(g(3))?",
    answer: 19,
    tolerance: 0,
    solution:
      "Work from the inside out. g(3) = 3² = 9. Then f(9) = 2 × 9 + 1 = 19. The other order gives a different number: f(3) = 7 and g(7) = 49. Composition is not commutative, so the notation f(g(x)) always means apply g first.",
    method: "Evaluate the inner function first, then feed its output into the outer function.",
    hints: ["The inner function is applied first.", "Compute g(3).", "Now apply f to that result."],
    commonErrors: [
      { description: "Applied the functions in the wrong order: g(f(3))", category: "CONCEPTUAL_ERROR", value: 49 },
      { description: "Stopped at f(3)", category: "MISREAD", value: 7 },
      { description: "Stopped at g(3)", category: "MISREAD", value: 9 },
    ],
    transfer: 0,
    minutes: 1,
    examEligible: true,
    tags: ["functions"],
  }),

  /* ---------------- Linear versus exponential growth ---------------- */
  item(28, {
    subskill: "compound_growth",
    concepts: ["linear-vs-exponential-growth", "exponents-and-logarithms"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt:
      "Town A has 8,000 people and grows 3 % a year. Town B has 11,000 people and gains 200 people a year. After 20 years, what is the population of A minus the population of B? Give a negative number if B is larger.",
    answer: -551,
    tolerance: 15,
    solution:
      "A grows exponentially: 8,000 × 1.03²⁰. Since ln 1.03 ≈ 0.02956, 20 × 0.02956 ≈ 0.591 and e^0.591 ≈ 1.806, so A ≈ 14,449. B grows linearly: 11,000 + 20 × 200 = 15,000. A − B ≈ −551: B is still ahead after 20 years, though A overtakes it a few years later. Treating 3 % for 20 years as 60 % gives A = 12,800 and a gap of −2,200, badly understating compound growth.",
    method: "Model each town with the right growth type (multiplier for percentage growth, addition for fixed increments), compute both, then subtract.",
    hints: ["Which town's growth is a fixed number, and which is a fixed percentage?", "3 % a year for 20 years is 1.03 to the power 20, not 1 + 0.60.", "1.03²⁰ ≈ 1.806."],
    commonErrors: [
      { description: "Correct magnitude, wrong sign", category: "ALGEBRA_ERROR", value: 551 },
      { description: "Treated 3 % a year as 60 % over 20 years (linear)", category: "CONCEPTUAL_ERROR", value: -2200 },
    ],
    transfer: 1,
    minutes: 4,
    examEligible: true,
    tags: ["growth"],
  }),
  item(29, {
    subskill: "recognising_growth",
    concepts: ["linear-vs-exponential-growth", "functions-and-graphs"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A quantity is measured once a year: 40, 60, 90, 135, 202.5. Which model fits the data?",
    options: ["Exponential growth: multiplied by 1.5 each year", "Linear growth: 20 added each year", "Exponential growth: 20 % a year", "Linear growth: about 40 added each year"],
    answer: 0,
    solution:
      "Check the differences: 20, 30, 45, 67.5. They are not constant, so growth is not linear. Check the ratios: 60/40 = 1.5, 90/60 = 1.5, 135/90 = 1.5, 202.5/135 = 1.5. Constant ratio means exponential growth of 50 % a year. The first difference (20) looks linear only if you stop after one step.",
    method: "Compute successive differences and successive ratios; constant differences mean linear, constant ratios mean exponential.",
    hints: ["Look at the differences between consecutive values.", "If they are not constant, look at the ratios.", "Each value divided by the previous one."],
    commonErrors: [
      { description: "Took the first difference as the pattern", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Identified exponential growth but misread the rate (a ratio of 1.5 is 50 %, not 20 %)", category: "PRECISION_ERROR", optionIndex: 2 },
      { description: "Averaged the differences", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["growth"],
  }),

  /* ---------------- Rates of change ---------------- */
  item(30, {
    subskill: "average_rate",
    concepts: ["rates-of-change", "units-and-dimensional-analysis"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A tank reads 140 litres at 2:00 pm and 95 litres at 2:30 pm. What is the average rate of change of volume in litres per hour? Give a negative number for a decrease.",
    answer: -90,
    tolerance: 0.5,
    unit: "L/h",
    solution:
      "Change in volume: 95 − 140 = −45 L. Change in time: 30 minutes = 0.5 h. Rate = −45 L ÷ 0.5 h = −90 L/h. The sign is negative because the tank is draining; the time must be in hours before dividing because the answer is per hour.",
    method: "Rate = (final − initial) ÷ elapsed time, with the time converted to the unit named in the answer before dividing.",
    hints: ["Subtract the earlier reading from the later one, keeping the sign.", "How many hours is 30 minutes?", "Divide the change by 0.5."],
    commonErrors: [
      { description: "Dropped the sign of a decrease", category: "ALGEBRA_ERROR", value: 90 },
      { description: "Gave litres per half-hour, forgetting to convert to hours", category: "PRECISION_ERROR", value: -45 },
      { description: "Gave litres per minute", category: "PRECISION_ERROR", value: -1.5 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["rates"],
  }),
  item(31, {
    subskill: "level_vs_rate",
    concepts: ["rates-of-change"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A news report says: 'Inflation fell from 6 % to 4 % last year.' Which statement is correct?",
    options: [
      "Prices still rose over the year, but more slowly than the year before",
      "Prices fell over the year",
      "Prices fell by 2 % over the year",
      "Prices returned to where they were two years earlier",
    ],
    answer: 0,
    solution:
      "Inflation is a rate: the percentage by which the price level rises in a year. Inflation of 4 % means prices rose 4 % last year; the fall from 6 % is a fall in the rate of increase, not in prices. Over the two years prices rose by roughly 1.06 × 1.04 − 1 ≈ 10 %. Saying prices fell confuses the derivative with the level.",
    method: "Ask whether the reported number is a level or a rate; a falling rate means the level is still rising if the rate is positive.",
    hints: ["Is inflation a price or a speed of price change?", "A positive rate means the quantity is still increasing.", "A car slowing from 60 to 40 is still moving forward."],
    commonErrors: [
      { description: "Confused a falling rate with a falling level", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Read the change in the rate as a change in prices", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Assumed the rate change undid earlier rises", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 2,
    examEligible: true,
    tags: ["rates", "economics"],
  }),

  /* ---------------- Geometry and scale ---------------- */
  item(32, {
    subskill: "scale_factors",
    concepts: ["geometry-and-scale", "units-and-dimensional-analysis"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "An architect's model is built at a scale of 1 : 50. The model's floor area is 240 cm². What is the floor area of the real building, in square metres?",
    answer: 60,
    tolerance: 0.5,
    unit: "m²",
    solution:
      "A length scale of 50 means an area scale of 50² = 2,500. Real area = 240 × 2,500 = 600,000 cm². One square metre is 100 × 100 = 10,000 cm², so 600,000 cm² = 60 m². Multiplying the area by 50 (giving 1.2 m²) scales it as if it were a length.",
    method: "Square the linear scale factor for areas, apply it, then convert the unit remembering that 1 m² = 10,000 cm².",
    hints: ["Lengths scale by 50; how do areas scale?", "Area scale factor is 50² = 2,500.", "1 m² = 10,000 cm²."],
    commonErrors: [
      { description: "Scaled the area by the linear factor 50", category: "CONCEPTUAL_ERROR", value: 1.2 },
      { description: "Correct in cm² but not converted to m²", category: "PRECISION_ERROR", value: 600000 },
      { description: "Converted cm² to m² by dividing by 100 instead of 10,000", category: "PRECISION_ERROR", value: 6000 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["scale", "area"],
  }),
  item(33, {
    subskill: "square_cube_law",
    concepts: ["geometry-and-scale"],
    level: "transfer",
    difficulty: 4,
    format: "mcq",
    prompt:
      "An animal's heat production is roughly proportional to its volume, and its heat loss to its surface area. If an animal were scaled up to twice its size in every linear dimension, what would happen?",
    options: [
      "Heat produced rises about 8-fold while the surface that sheds it rises about 4-fold, so the larger animal retains heat more easily",
      "Both rise 2-fold, so the balance between production and loss is unchanged",
      "Both rise 4-fold, so the balance between production and loss is unchanged",
      "Heat produced rises 4-fold while surface rises 8-fold, so the larger animal loses heat faster",
    ],
    answer: 0,
    solution:
      "Doubling every length multiplies areas by 2² = 4 and volumes by 2³ = 8. Heat production (volume) rises 8-fold; the surface available to lose it rises only 4-fold, so the larger animal has half the surface per unit volume and keeps its heat. This is why small mammals eat constantly and large ones are found in cold climates (Bergmann's rule, an empirical tendency rather than a law).",
    method: "Assign each quantity its dimension (length, area, volume), raise the linear scale factor to the matching power, and compare.",
    hints: ["Which quantity is an area and which is a volume?", "Doubling lengths multiplies areas by 2² and volumes by 2³.", "Compare 8 with 4."],
    commonErrors: [
      { description: "Scaled everything linearly", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Scaled volume as if it were area", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Swapped the area and volume exponents", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["scale", "biology"],
  }),
  item(34, {
    subskill: "volume",
    concepts: ["geometry-and-scale", "units-and-dimensional-analysis"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A cylindrical water tank has a diameter of 1.6 m and a height of 2 m. How many litres does it hold when full?",
    answer: 4021,
    tolerance: 25,
    unit: "L",
    solution:
      "Volume of a cylinder is πr²h with the radius, not the diameter. r = 0.8 m, so V = π × 0.8² × 2 = π × 1.28 ≈ 4.021 m³. One cubic metre is 1,000 litres, so the tank holds about 4,020 litres. Using the diameter in place of the radius quadruples the answer to roughly 16,000 litres.",
    method: "Halve the diameter to get the radius, apply πr²h, then convert cubic metres to litres.",
    hints: ["The formula needs the radius.", "V = π r² h.", "1 m³ = 1,000 L."],
    commonErrors: [
      { description: "Used the diameter as the radius", category: "CONCEPTUAL_ERROR", value: 16085 },
      { description: "Left the answer in cubic metres", category: "PRECISION_ERROR", value: 4.02 },
      { description: "Computed the curved surface 2πrh instead of the volume", category: "CONCEPTUAL_ERROR", value: 10053 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["volume"],
  }),
  item(35, {
    subskill: "scale_factors",
    concepts: ["geometry-and-scale"],
    level: "foundation",
    difficulty: 1,
    format: "true_false",
    prompt: "Doubling the radius of a circle doubles its area.",
    answer: "false",
    solution:
      "False. Area is πr², so doubling r multiplies the area by 2² = 4. Only the circumference (2πr), a length, doubles. The general rule: lengths scale by k, areas by k², volumes by k³.",
    method: "Identify the dimension of the quantity (length, area or volume) and raise the scale factor to that power.",
    hints: ["Write down the formula for the area of a circle.", "What happens to r² when r doubles?", "Lengths double; areas do something else."],
    commonErrors: [{ description: "Scaled area linearly with the radius", category: "CONCEPTUAL_ERROR" }],
    transfer: 0,
    minutes: 1,
    examOnly: true,
    tags: ["scale"],
  }),

  /* ---------------- Further mathematics: calculus ---------------- */
  item(36, {
    subskill: "marginal_analysis",
    concepts: ["derivative-intuition", "rates-of-change"],
    level: "intermediate",
    difficulty: 4,
    format: "numeric",
    prompt: "A firm's total cost of producing q units is C(q) = 0.5q² + 20q + 1,000 pounds. What is the marginal cost (the cost of one more unit, taken as the derivative) at q = 40?",
    answer: 60,
    tolerance: 0.5,
    unit: "£",
    solution:
      "Marginal cost is the derivative of total cost. C′(q) = 0.5 × 2q + 20 = q + 20, so C′(40) = 60. This is not the total cost (C(40) = 800 + 800 + 1,000 = 2,600) nor the average cost (2,600 / 40 = 65). Marginal cost is what the 41st unit adds; average cost is what each unit has cost so far. Check: C(41) − C(40) = 60.5, close to 60 as expected.",
    method: "Differentiate the cost function term by term with the power rule and evaluate at the given quantity.",
    hints: ["Marginal means the rate of change of total cost.", "Differentiate: the derivative of 0.5q² is q, of 20q is 20, of a constant is 0.", "Evaluate q + 20 at q = 40."],
    commonErrors: [
      { description: "Gave the total cost C(40)", category: "CONCEPTUAL_ERROR", value: 2600 },
      { description: "Gave the average cost C(40) / 40", category: "CONCEPTUAL_ERROR", value: 65 },
      { description: "Dropped the derivative of the linear term", category: "ALGEBRA_ERROR", value: 40 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["calculus", "economics"],
  }),
  item(37, {
    subskill: "area_under_curve",
    concepts: ["integral-intuition", "rates-of-change"],
    level: "basic",
    difficulty: 3,
    format: "numeric",
    prompt: "A car accelerates uniformly from rest to 20 m/s over 10 seconds, then holds 20 m/s for a further 15 seconds. How far does it travel in total, in metres?",
    answer: 400,
    tolerance: 1,
    unit: "m",
    solution:
      "Distance is the area under the speed–time graph. The acceleration phase is a triangle: ½ × 10 s × 20 m/s = 100 m. The constant phase is a rectangle: 15 s × 20 m/s = 300 m. Total 400 m. Multiplying the final speed by the total time (20 × 25 = 500 m) treats the car as if it had been at full speed throughout.",
    method: "Sketch the rate against time and add up the areas of the shapes; area under a rate is accumulated quantity.",
    hints: ["Sketch speed against time.", "What shape is the first ten seconds? What is its area?", "Add the rectangle for the constant-speed phase."],
    commonErrors: [
      { description: "Used final speed × total time, ignoring the acceleration phase", category: "CONCEPTUAL_ERROR", value: 500 },
      { description: "Ignored the distance covered while accelerating", category: "MISREAD", value: 300 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["calculus"],
  }),

  /* ---------------- Further mathematics: linear algebra ---------------- */
  item(38, {
    subskill: "dot_product",
    concepts: ["vectors-and-matrices"],
    level: "basic",
    difficulty: 3,
    format: "numeric",
    prompt: "Compute the dot product of a = (3, −1, 2) and b = (2, 4, −1).",
    answer: 0,
    tolerance: 0,
    solution:
      "Multiply matching components and add: 3 × 2 + (−1) × 4 + 2 × (−1) = 6 − 4 − 2 = 0. A zero dot product means the vectors are perpendicular. The commonest slip is losing the sign on the last product, giving 6 − 4 + 2 = 4.",
    method: "Sum the products of corresponding components, keeping every sign.",
    hints: ["Pair the components: first with first, second with second, third with third.", "Multiply each pair, then add.", "Two of the three products are negative."],
    commonErrors: [
      { description: "Lost the sign of the third product", category: "ALGEBRA_ERROR", value: 4 },
      { description: "Lost the sign of the second product", category: "ALGEBRA_ERROR", value: 8 },
      { description: "Ignored all signs", category: "ALGEBRA_ERROR", value: 12 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["linear-algebra"],
  }),
  item(39, {
    subskill: "matrix_vector_product",
    concepts: ["vectors-and-matrices", "linear-transformations"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "The matrix M = [[2, 1], [0, 3]] (rows listed first) acts on the vector v = (4, −2). What is the second component of Mv?",
    answer: -6,
    tolerance: 0,
    solution:
      "Each component of Mv is the dot product of a row of M with v. First component: 2 × 4 + 1 × (−2) = 6. Second component: 0 × 4 + 3 × (−2) = −6. So Mv = (6, −6). Using the columns instead of the rows gives (8, −2), which is vᵀM, a different product.",
    method: "Take the dot product of each row of the matrix with the vector; the second row gives the second component.",
    hints: ["Use the rows of M, not the columns.", "Second row is (0, 3).", "0 × 4 + 3 × (−2)."],
    commonErrors: [
      { description: "Lost the sign", category: "ALGEBRA_ERROR", value: 6 },
      { description: "Used the columns of M instead of the rows", category: "CONCEPTUAL_ERROR", value: -2 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["linear-algebra"],
  }),
  item(40, {
    subskill: "geometric_interpretation",
    concepts: ["linear-transformations", "vectors-and-matrices"],
    level: "intermediate",
    difficulty: 4,
    format: "mcq",
    prompt: "What does the matrix [[0, −1], [1, 0]] (rows listed first) do to the plane?",
    options: ["Rotates it 90° anticlockwise", "Reflects it in the x-axis", "Rotates it 90° clockwise", "Reflects it in the line y = x"],
    answer: 0,
    solution:
      "Read the columns as the images of the basis vectors. (1, 0) goes to the first column (0, 1): the x-axis turns to point up. (0, 1) goes to the second column (−1, 0): the y-axis turns to point left. Up then left is a 90° anticlockwise rotation. A clockwise rotation would send (1, 0) to (0, −1). Neither reflection matches: reflection in the x-axis fixes (1, 0), and reflection in y = x swaps the two basis vectors without any sign change.",
    method: "Apply the matrix to (1, 0) and (0, 1) and picture where the axes land; that determines the transformation.",
    hints: ["Where does (1, 0) go? It becomes the first column.", "Where does (0, 1) go?", "Sketch the two images and see how the axes have turned."],
    commonErrors: [
      { description: "Reflection would fix one axis; this fixes neither", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Rotation direction reversed: sign error in reading the columns", category: "ALGEBRA_ERROR", optionIndex: 2 },
      { description: "Ignored the sign change in the second column", category: "ALGEBRA_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["linear-algebra"],
  }),

  /* ---------------- Further mathematics: discrete ---------------- */
  item(41, {
    subskill: "combinations",
    concepts: ["sets-and-counting"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A club has 12 members. How many different committees of 3 can it form?",
    answer: 220,
    tolerance: 0,
    solution:
      "Order does not matter in a committee, so this is a combination: C(12, 3) = 12! / (3! × 9!) = (12 × 11 × 10) / (3 × 2 × 1) = 1,320 / 6 = 220. The 1,320 counts ordered selections (permutations); each committee appears 6 times among them, once for each ordering of its three members.",
    method: "Decide whether order matters; if not, count ordered selections and divide by the number of orderings.",
    hints: ["Does the order in which members are chosen matter?", "There are 12 × 11 × 10 ordered choices.", "Each committee is counted 3! = 6 times among them."],
    commonErrors: [
      { description: "Counted ordered selections (permutations)", category: "CONCEPTUAL_ERROR", value: 1320 },
      { description: "Multiplied 12 by 3", category: "CONCEPTUAL_ERROR", value: 36 },
      { description: "Allowed repeats: 12³", category: "CONCEPTUAL_ERROR", value: 1728 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["counting"],
  }),
  item(42, {
    subskill: "inclusion_exclusion",
    concepts: ["sets-and-counting"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "In a year group of 80 students, 45 study French, 38 study German and 15 study both. How many study neither language?",
    answer: 12,
    tolerance: 0,
    solution:
      "Students studying at least one language: |F ∪ G| = |F| + |G| − |F ∩ G| = 45 + 38 − 15 = 68. Neither: 80 − 68 = 12. Adding 45 and 38 without subtracting the overlap counts the 15 bilingual students twice and gives 83, more than the year group.",
    method: "Use inclusion–exclusion to count the union, then subtract from the total.",
    hints: ["45 + 38 is more than 80; why?", "The 15 who study both have been counted twice.", "Subtract the overlap once, then subtract from 80."],
    commonErrors: [
      { description: "Did not subtract the overlap: 80 − 83", category: "CONCEPTUAL_ERROR", value: -3 },
      { description: "Ignored German entirely", category: "MISREAD", value: 35 },
      { description: "Subtracted the overlap twice", category: "ALGEBRA_ERROR", value: 27 },
    ],
    transfer: 0,
    minutes: 2,
    examOnly: true,
    tags: ["counting", "sets"],
  }),
  item(43, {
    subskill: "induction",
    concepts: ["proof-and-induction"],
    level: "intermediate",
    difficulty: 4,
    format: "mcq",
    prompt: "Claim: for every whole number n ≥ 1, 1 + 3 + 5 + … + (2n − 1) = n². Which plan would prove it?",
    options: [
      "Show it holds for n = 1, then show that whenever it holds for n = k it also holds for n = k + 1",
      "Check it for every n from 1 to 100 with a computer",
      "Assume it holds for all n, and show that it then holds for n = k + 1",
      "Show that whenever it holds for n = k + 1 it also holds for n = k",
    ],
    answer: 0,
    solution:
      "Induction needs a base case and an inductive step running upwards. The step: if 1 + 3 + … + (2k − 1) = k², then adding the next odd number gives k² + (2k + 1) = (k + 1)². Checking to 100 supports the claim but proves nothing about 101. Assuming the claim for all n is circular. A step from k + 1 down to k never gets started from the base case.",
    method: "Identify the base case and an inductive step from k to k + 1; reject plans that enumerate, assume the conclusion or run the implication backwards.",
    hints: ["A universal claim needs an argument that covers every n at once.", "What are the two parts of a proof by induction?", "The step must go from k to k + 1, and must not assume the whole claim."],
    commonErrors: [
      { description: "Treated many confirming cases as a proof", category: "LOGIC_ERROR", optionIndex: 1 },
      { description: "Assumed the conclusion (circular reasoning)", category: "LOGIC_ERROR", optionIndex: 2 },
      { description: "Ran the implication in the wrong direction", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["proof"],
  }),
  item(44, {
    subskill: "proof_by_contradiction",
    concepts: ["proof-and-induction"],
    level: "advanced",
    difficulty: 5,
    format: "ordering",
    prompt: "Put the steps of the classical proof that √2 is irrational into the correct order.",
    options: [
      "Suppose, for contradiction, that √2 = p/q with p and q whole numbers sharing no common factor.",
      "Square both sides and rearrange: p² = 2q², so p² is even.",
      "Since p² is even, p must be even; write p = 2m.",
      "Substitute: 4m² = 2q², so q² = 2m² and q is also even.",
      "Both p and q are even, contradicting the assumption that they share no common factor.",
      "Therefore no such p and q exist, and √2 is irrational.",
    ],
    solution:
      "The proof assumes the opposite (√2 rational, in lowest terms), squares to obtain p² = 2q², deduces that p is even, substitutes p = 2m to deduce that q is even too, and finds a contradiction with 'lowest terms'. The contradiction discharges the assumption. Each step depends on the one before it: the substitution step cannot come before p = 2m has been established, and the conclusion must follow the contradiction.",
    method: "Trace the logical dependencies: the assumption first, each deduction after the fact it uses, the contradiction, then the conclusion.",
    hints: ["A proof by contradiction begins by assuming the claim is false.", "You cannot substitute p = 2m before showing p is even.", "The contradiction comes just before the conclusion."],
    commonErrors: [
      { description: "Placed the substitution before establishing that p is even", category: "LOGIC_ERROR" },
      { description: "Placed the conclusion before the contradiction that justifies it", category: "LOGIC_ERROR" },
    ],
    transfer: 0,
    minutes: 4,
    examEligible: true,
    tags: ["proof"],
  }),
  item(45, {
    subskill: "handshake_lemma",
    concepts: ["graphs-and-networks-math"],
    level: "basic",
    difficulty: 3,
    format: "numeric",
    prompt: "A network has six nodes. Four of them have degree 3 and two have degree 2. How many edges does the network have?",
    answer: 8,
    tolerance: 0,
    solution:
      "Every edge contributes one to the degree of each of its two endpoints, so the sum of all degrees is twice the number of edges. Degree sum: 4 × 3 + 2 × 2 = 12 + 4 = 16. Edges: 16 / 2 = 8. Forgetting to halve gives 16; assuming every pair is joined gives C(6, 2) = 15, which the degrees rule out.",
    method: "Apply the handshake lemma: number of edges = (sum of degrees) ÷ 2.",
    hints: ["Add up all the degrees.", "Each edge has two ends, so it is counted twice in that sum.", "Halve the degree sum."],
    commonErrors: [
      { description: "Did not halve the degree sum", category: "CONCEPTUAL_ERROR", value: 16 },
      { description: "Assumed a complete graph on six nodes", category: "ASSUMPTION", value: 15 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["networks"],
  }),
  item(46, {
    subskill: "euler_circuits",
    concepts: ["graphs-and-networks-math"],
    level: "intermediate",
    difficulty: 4,
    format: "mcq",
    prompt: "A postal worker wants to walk every street in a district exactly once and finish where she started. Treating intersections as nodes and streets as edges, what must be true of the network?",
    options: [
      "It is connected and every intersection has an even number of streets",
      "It is connected and exactly two intersections have an odd number of streets",
      "It is connected and has an even number of streets",
      "Every intersection has an odd number of streets",
    ],
    answer: 0,
    solution:
      "A closed walk that uses every edge once is an Euler circuit. Each time the walk passes through an intersection it uses one street in and one out, so every intersection must have even degree; and the network must be connected so that every street is reachable. Exactly two odd-degree intersections allows an Euler trail that starts at one and ends at the other, but not a return to the start. The parity of the number of streets is irrelevant. This is the reasoning Euler applied to the seven bridges of Königsberg in 1736.",
    method: "Translate the route condition into a degree condition: a closed walk needs even degree everywhere and connectivity.",
    hints: ["Each pass through an intersection uses two of its streets.", "What does that say about the number of streets at each intersection?", "Two odd intersections would allow an open walk only."],
    commonErrors: [
      { description: "Stated the condition for an open Euler trail, not a circuit", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Confused the parity of edge count with the parity of degrees", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Reversed the parity condition", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["networks"],
  }),

  /* ---------------- Further mathematics: optimisation ---------------- */
  item(47, {
    subskill: "constrained_optimisation",
    concepts: ["optimisation", "quadratics"],
    level: "advanced",
    difficulty: 4,
    format: "numeric",
    prompt: "A farmer has 60 m of fencing to enclose a rectangular pen against a long straight wall, so only three sides need fencing. What is the largest area she can enclose, in square metres?",
    answer: 450,
    tolerance: 1,
    unit: "m²",
    solution:
      "Let x be the length of each side perpendicular to the wall and y the side parallel to it. Constraint: 2x + y = 60, so y = 60 − 2x. Area A = xy = x(60 − 2x) = 60x − 2x². This quadratic peaks at x = −b / 2a = 60 / 4 = 15 (or set A′ = 60 − 4x = 0). Then y = 30 and A = 450 m². A square pen of 20 m sides (60 / 3) gives only 400 m²; the optimum is not symmetric because the constraint is not.",
    method: "Use the constraint to write the area as a function of one variable, then find its maximum at the vertex or where the derivative is zero.",
    hints: ["Only three sides use fencing: 2x + y = 60.", "Write the area in terms of x alone.", "A = 60x − 2x² is a downward parabola; find its vertex."],
    commonErrors: [
      { description: "Fenced all four sides: a 15 m square", category: "CONCEPTUAL_ERROR", value: 225 },
      { description: "Assumed three equal sides of 20 m", category: "CONCEPTUAL_ERROR", value: 400 },
      { description: "Used 30 m for both dimensions, exceeding the fencing", category: "MISREAD", value: 900 },
    ],
    transfer: 1,
    minutes: 4,
    examEligible: true,
    tags: ["calculus", "optimisation"],
  }),
];
