import type { PracticeItem } from "@/lib/v2/content-types";

/**
 * Probability practice items, part B: random variables, expected value, variance,
 * distributions, the law of large numbers and Monte Carlo reasoning, plus the exam-only
 * items. Ids it-probability-24 … it-probability-46.
 */
export const ITEMS_PROBABILITY_B: PracticeItem[] = [
  {
    id: "it-probability-24",
    skill: "probability",
    subskill: "random_variables",
    concepts: ["random-variables", "expected-value"],
    level: "foundation",
    difficulty: 1,
    format: "true_false",
    prompt: "True or false: the expected value of a random variable must be one of the values the variable can actually take.",
    answer: "false",
    solution:
      "False. The expected value is a probability-weighted average, and averages need not be attainable. A fair die has expected value (1 + 2 + 3 + 4 + 5 + 6)/6 = 3.5, which no roll can show; a household has 1.9 children on average without any household having 1.9 children. The expected value is the long-run average per trial, the balance point of the distribution, not a prediction of any single outcome. Reading it as \"what will happen\" leads to mistakes such as planning for the average demand when the average never occurs.",
    method: "Recall the definition: a weighted average, hence a balance point, not necessarily an outcome.",
    hints: ["What is the expected value of one roll of a fair die?", "Can a die show 3.5?"],
    commonErrors: [{ description: "Read the expected value as a typical or most likely outcome.", category: "CONCEPTUAL_ERROR", pattern: "true" }],
    transfer: 0,
    minutes: 1,
    tags: ["expected-value", "definition"],
    origin: "seeded",
  },
  {
    id: "it-probability-25",
    skill: "probability",
    subskill: "expected_value",
    concepts: ["expected-value", "random-variables"],
    level: "foundation",
    difficulty: 2,
    format: "numeric",
    prompt: "A random variable X takes the value 0 with probability 0.1, 1 with probability 0.3, 2 with probability 0.4 and 3 with probability 0.2. What is E[X]?",
    answer: 1.7,
    tolerance: 0.01,
    solution:
      "E[X] = Σ x · P(X = x) = 0 × 0.1 + 1 × 0.3 + 2 × 0.4 + 3 × 0.2 = 0 + 0.3 + 0.8 + 0.6 = 1.7. Check that the probabilities add to 1 (0.1 + 0.3 + 0.4 + 0.2 = 1) before trusting the sum. The unweighted midpoint of the values, 1.5, is not the expected value because the values are not equally likely; the mode, 2, is the most probable value but not the average. If you imagine 10 draws, roughly one 0, three 1s, four 2s and two 3s, their total is 17 and their mean 1.7.",
    method: "Multiply each value by its probability and add; verify the probabilities sum to one.",
    hints: ["Write each value next to its probability.", "Multiply pairs and add the four products.", "0 + 0.3 + 0.8 + 0.6."],
    commonErrors: [
      { description: "Averaged the four values with equal weights (0 + 1 + 2 + 3)/4.", category: "CONCEPTUAL_ERROR", value: 1.5 },
      { description: "Reported the most likely value, the mode, instead of the mean.", category: "CONCEPTUAL_ERROR", value: 2 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["expected-value"],
    origin: "seeded",
  },
  {
    id: "it-probability-26",
    skill: "probability",
    subskill: "variance",
    concepts: ["variance-and-spread", "expected-value"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A random variable X takes the value 0 with probability 0.1, 1 with probability 0.3, 2 with probability 0.4 and 3 with probability 0.2. Its mean is 1.7. What is the variance of X?",
    answer: 0.81,
    tolerance: 0.01,
    solution:
      "Variance is the expected squared distance from the mean. Directly: Var(X) = Σ (x − 1.7)² P(x) = 2.89 × 0.1 + 0.49 × 0.3 + 0.09 × 0.4 + 1.69 × 0.2 = 0.289 + 0.147 + 0.036 + 0.338 = 0.81. Or by the shortcut Var(X) = E[X²] − (E[X])²: E[X²] = 0 + 0.3 + 1.6 + 1.8 = 3.7, so Var(X) = 3.7 − 2.89 = 0.81. The standard deviation is √0.81 = 0.9, in the same units as X; the variance is in squared units. A common slip is to report E[X²] = 3.7 and forget the subtraction, or to give the standard deviation when the variance was asked.",
    method: "Either average the squared deviations directly or use E[X²] − (E[X])²; take the square root only if the standard deviation is wanted.",
    hints: ["Variance is the average of (x − mean)², weighted by probability.", "Alternatively compute E[X²] first: 0 × 0.1 + 1 × 0.3 + 4 × 0.4 + 9 × 0.2.", "Subtract the square of the mean: 3.7 − 1.7²."],
    commonErrors: [
      { description: "Reported E[X²] without subtracting the squared mean.", category: "ALGEBRA_ERROR", value: 3.7 },
      { description: "Gave the standard deviation instead of the variance.", category: "PRECISION_ERROR", value: 0.9 },
    ],
    transfer: 0,
    minutes: 4,
    examEligible: true,
    tags: ["variance"],
    origin: "seeded",
  },
  {
    id: "it-probability-27",
    skill: "probability",
    subskill: "expected_value",
    concepts: ["expected-value", "base-rates", "random-variables"],
    level: "transfer",
    difficulty: 3,
    format: "numeric",
    prompt:
      "In the 1720s an underwriter at Lloyd's coffee house in London is asked to insure a merchant ship and cargo worth £10,000 for a voyage to the Baltic. His records show that on this route about 1 ship in 20 has been lost in the past decade, and he takes that as the chance of loss on this voyage. He charges a premium of £800. What is his expected profit on the policy, in pounds?",
    answer: 300,
    tolerance: 1,
    unit: "£",
    solution:
      "The underwriter receives £800 for certain. With probability 1/20 = 0.05 he pays out £10,000, so his expected payout is 0.05 × 10,000 = £500. Expected profit = 800 − 500 = £300. The premium that would make the policy fair (zero expected profit) is £500, so £800 carries a margin of £300, which covers the uncertainty in the 1-in-20 estimate, the cost of capital, and the fact that a single loss would cost twenty policies' worth of premium. Historically, marine insurance is where expected-value reasoning first became a trade: the underwriter's skill lay in the base rate, learned from shipping lists, not in the arithmetic. A premium quoted as 8% of value against a 5% loss rate is the same calculation in the language of the time.",
    method: "Expected profit = premium − (probability of loss × amount at risk). Identify the base rate first.",
    hints: ["What does the underwriter receive for certain, and what might he have to pay?", "Expected payout is the probability of loss times the sum insured.", "800 − 0.05 × 10,000."],
    commonErrors: [
      { description: "Subtracted 5 instead of 5% of £10,000, confusing a percentage with an amount.", category: "PRECISION_ERROR", value: 795 },
      { description: "Reported the expected payout (the fair premium) rather than the profit.", category: "MISREAD", value: 500 },
      { description: "Subtracted the whole sum insured, as if the loss were certain.", category: "CONCEPTUAL_ERROR", value: -9200 },
    ],
    transfer: 3,
    minutes: 4,
    examEligible: true,
    tags: ["insurance", "history", "expected-value"],
    origin: "seeded",
  },
  {
    id: "it-probability-28",
    skill: "probability",
    subskill: "expected_value",
    concepts: ["expected-value", "random-variables"],
    level: "transfer",
    difficulty: 5,
    format: "numeric",
    prompt:
      "A bakery bakes sourdough loaves each morning at a cost of £1 per loaf and sells them for £2.50. Unsold loaves are thrown away at the end of the day. Daily demand is 80 loaves with probability 0.3, 100 with probability 0.5 and 120 with probability 0.2.\n\nIf the bakery bakes 100 loaves, what is its expected daily profit from sourdough, in pounds?",
    answer: 135,
    tolerance: 0.5,
    unit: "£",
    solution:
      "Cost is fixed once the decision is made: 100 × £1 = £100. Revenue depends on demand, but sales cannot exceed the 100 loaves baked. Demand 80: sell 80, revenue £200. Demand 100: sell 100, £250. Demand 120: still sell only 100, £250. Expected revenue = 0.3 × 200 + 0.5 × 250 + 0.2 × 250 = 60 + 125 + 50 = £235. Expected profit = 235 − 100 = £135. The trap is to compute profit at the expected demand (98 loaves) or to let revenue follow demand above 100; both give £145 and both ignore that the bakery's payoff is capped by its own decision. For comparison, baking 80 yields £120 for certain and baking 120 yields an expected £125, so 100 is the best of the three. This is the newsvendor structure: an asymmetric loss, wasted loaves against lost sales, evaluated under a demand distribution.",
    method: "Fix the decision, work out the payoff in every demand scenario with the sales cap applied, weight by probability, subtract cost.",
    hints: ["Cost does not depend on demand; revenue does. Write revenue for each of the three demand levels.", "If demand is 120 but only 100 loaves were baked, how many are sold?", "Expected revenue = 0.3 × 200 + 0.5 × 250 + 0.2 × 250; then subtract £100."],
    commonErrors: [
      { description: "Let revenue rise with demand above the 100 loaves baked, or computed profit at the average demand; both ignore the cap.", category: "CONCEPTUAL_ERROR", value: 145 },
      { description: "Reported expected revenue without subtracting the £100 cost.", category: "MISREAD", value: 235 },
      { description: "Computed the expected profit for baking 120 loaves.", category: "MISREAD", value: 125 },
    ],
    transfer: 2,
    minutes: 6,
    tags: ["business", "newsvendor", "expected-value"],
    origin: "seeded",
  },
  {
    id: "it-probability-29",
    skill: "probability",
    subskill: "linearity_of_expectation",
    concepts: ["expected-value", "random-variables"],
    level: "advanced",
    difficulty: 5,
    format: "numeric",
    prompt: "Ten guests leave their hats at a party. On leaving, each guest takes a hat at random (a uniformly random permutation of the hats). What is the expected number of guests who get their own hat back?",
    answer: 1,
    tolerance: 0.01,
    solution:
      "Let Iₖ be 1 if guest k gets their own hat and 0 otherwise. Guest k's hat is one of ten equally likely hats, so P(Iₖ = 1) = 1/10 and E[Iₖ] = 0.1. The number of correct hats is I₁ + … + I₁₀, and expectation is linear whether or not the terms are independent (they are not: if nine guests get their own hats, the tenth must too). So E[total] = 10 × 0.1 = 1. The answer does not depend on the number of guests. Linearity is the most useful property of expectation precisely because it sidesteps the dependence that would make the full distribution hard to compute; the full distribution here is the classic derangement problem, but the mean needs none of it.",
    method: "Write the count as a sum of indicator variables and use linearity of expectation, which needs no independence.",
    hints: ["For one particular guest, what is the probability of getting their own hat?", "Define an indicator for each guest and add them up.", "Expectation of a sum is the sum of expectations, even when the parts are dependent."],
    commonErrors: [
      { description: "Gave the probability for a single guest rather than the expected count over ten.", category: "CONCEPTUAL_ERROR", value: 0.1 },
      { description: "Reasoned that dependence between guests makes the expected value zero or undefined.", category: "CONCEPTUAL_ERROR", value: 0 },
      { description: "Assumed everyone gets their own hat back on average.", category: "CONCEPTUAL_ERROR", value: 10 },
    ],
    transfer: 1,
    minutes: 5,
    examEligible: true,
    tags: ["linearity", "indicators"],
    origin: "seeded",
  },
  {
    id: "it-probability-30",
    skill: "probability",
    subskill: "variance",
    concepts: ["variance-and-spread", "expected-value"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt:
      "Investment A returns 5% for certain. Investment B returns 15% with probability 0.5 and −5% with probability 0.5. Both have the same expected return of 5%. What is the standard deviation of B's return, in percentage points?",
    answer: 10,
    tolerance: 0.1,
    solution:
      "B's return deviates from its mean of 5 by +10 or −10, each with probability 0.5. Variance = 0.5 × 10² + 0.5 × (−10)² = 100 (percentage points squared), so the standard deviation is √100 = 10 percentage points. A has standard deviation 0. The two investments are indistinguishable by expected value; what separates them is spread, which is why expected value alone cannot rank risky choices and why finance treats standard deviation of returns as a first measure of risk. Reporting 100 answers a different question (variance), and 20 is the range, which ignores the probabilities.",
    method: "Compute deviations from the mean, square them, weight by probability, then take the square root.",
    hints: ["How far is each of B's outcomes from the mean of 5?", "Square those distances and average them with their probabilities.", "Take the square root of the variance."],
    commonErrors: [
      { description: "Reported the variance (100) instead of the standard deviation.", category: "PRECISION_ERROR", value: 100 },
      { description: "Reported the range 15 − (−5) = 20.", category: "CONCEPTUAL_ERROR", value: 20 },
      { description: "Reported the mean.", category: "MISREAD", value: 5 },
    ],
    transfer: 1,
    minutes: 3,
    tags: ["finance", "risk"],
    origin: "seeded",
  },
  {
    id: "it-probability-31",
    skill: "probability",
    subskill: "variance_of_sums",
    concepts: ["variance-and-spread", "independence"],
    level: "advanced",
    difficulty: 4,
    format: "numeric",
    prompt: "A machine part is made by joining two components end to end. Each component's length has a standard deviation of 3 mm, and the two lengths are independent. What is the standard deviation of the total length, in millimetres?",
    answer: 4.243,
    tolerance: 0.01,
    unit: "mm",
    solution:
      "For independent variables, variances add but standard deviations do not. Each component has variance 3² = 9 mm², so the total has variance 9 + 9 = 18 mm² and standard deviation √18 ≈ 4.24 mm. Adding the standard deviations to get 6 mm overstates the spread, because independent errors partly cancel: a long first component is as likely to be paired with a short second one as with a long one. This is the same fact that makes the standard deviation of an average shrink like 1/√n, and the same fact that fails when errors are correlated: if both components came from the same miscalibrated cutter, the deviations would move together and 6 mm would be closer to the truth.",
    method: "Convert to variances, add them (independence), convert back with a square root.",
    hints: ["Which quantity adds for independent variables: the variance or the standard deviation?", "Variance of each component is 9. Add them.", "Take the square root of 18."],
    commonErrors: [
      { description: "Added the standard deviations directly.", category: "CONCEPTUAL_ERROR", value: 6 },
      { description: "Reported the variance of the total rather than its standard deviation.", category: "PRECISION_ERROR", value: 18 },
      { description: "Assumed the spread is unchanged by adding a second component.", category: "CONCEPTUAL_ERROR", value: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["manufacturing", "variance"],
    origin: "seeded",
  },
  {
    id: "it-probability-32",
    skill: "probability",
    subskill: "binomial",
    concepts: ["distributions", "combinatorics", "independence"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A fair coin is tossed 10 times. What is the probability of exactly 5 heads? Give a decimal.",
    answer: 0.2461,
    tolerance: 0.003,
    solution:
      "Each specific sequence of 10 tosses has probability (1/2)^10 = 1/1024. The number of sequences with exactly 5 heads is C(10,5) = 252, so P(exactly 5 heads) = 252/1024 ≈ 0.246. This is the binomial formula P(k) = C(n,k) p^k (1−p)^(n−k) with n = 10, p = 0.5, k = 5. Two intuitions fail here. \"Half the time\" confuses the expected proportion with the probability of hitting it exactly; five heads is the single most likely count, yet it happens less than a quarter of the time. And 1/1024 is the probability of one particular sequence, forgetting that many sequences share the same count.",
    method: "Count the sequences with the required number of successes (a combination) and multiply by the probability of any one such sequence.",
    hints: ["How many sequences of ten tosses are there in total?", "How many of them contain exactly five heads? That is a combination.", "252 / 1024."],
    commonErrors: [
      { description: "Assumed that the expected outcome (half heads) occurs with probability one half.", category: "CONCEPTUAL_ERROR", value: 0.5 },
      { description: "Gave the probability of one specific sequence, forgetting to count the sequences.", category: "CONCEPTUAL_ERROR", value: 0.000977 },
    ],
    transfer: 0,
    minutes: 4,
    examEligible: true,
    tags: ["binomial"],
    origin: "seeded",
  },
  {
    id: "it-probability-33",
    skill: "probability",
    subskill: "binomial",
    concepts: ["distributions", "independence", "probability-rules"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A salesperson closes a sale on 20% of cold calls, independently from call to call. If she makes 8 calls this afternoon, what is the probability that she makes at least one sale? Give a decimal.",
    answer: 0.832,
    tolerance: 0.005,
    solution:
      "\"At least one\" invites the complement. P(no sale in 8 calls) = 0.8^8 ≈ 0.168, so P(at least one sale) = 1 − 0.168 ≈ 0.832. The binomial distribution with n = 8 and p = 0.2 gives the full picture (the expected number of sales is 1.6, the most likely count is 1), but the complement shortcut answers this question without it. Adding 0.2 eight times gives 1.6, which is the expected number of sales, not a probability; the fact that it exceeds 1 is the signal that addition was the wrong operation for overlapping events.",
    method: "Compute the probability of zero successes with the multiplication rule and subtract from one.",
    hints: ["What is the probability that one call yields no sale?", "What is the probability that all eight yield no sale?", "Subtract from 1."],
    commonErrors: [
      { description: "Reported the probability of no sale, forgetting the complement.", category: "MISREAD", value: 0.168 },
      { description: "Added 0.2 eight times; the result is the expected number of sales, not a probability.", category: "CONCEPTUAL_ERROR", value: 1.6 },
      { description: "Gave the single-call probability.", category: "CONCEPTUAL_ERROR", value: 0.2 },
    ],
    transfer: 1,
    minutes: 3,
    tags: ["binomial", "business"],
    origin: "seeded",
  },
  {
    id: "it-probability-34",
    skill: "probability",
    subskill: "normal",
    concepts: ["distributions", "variance-and-spread"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "Adult male heights in a population are approximately normally distributed with mean 175 cm and standard deviation 7 cm. What proportion of men are taller than 189 cm? Give a decimal probability.",
    answer: 0.0228,
    tolerance: 0.004,
    solution:
      "189 cm is (189 − 175)/7 = 2 standard deviations above the mean. For a normal distribution about 95% of values lie within 2 standard deviations of the mean, leaving 5% in the two tails together and 2.5% in the upper tail; the exact figure from the standard normal table is 0.0228. So roughly 2.3% of men are taller than 189 cm. The standardisation step, distance from the mean measured in standard deviations, is what makes one table serve every normal distribution. The answer 5% counts both tails, men shorter than 161 cm as well, which the question did not ask for.",
    method: "Standardise (z = (x − mean)/sd), then use the 68–95–99.7 rule or a normal table for the one-tailed probability.",
    hints: ["How many standard deviations above the mean is 189 cm?", "What share of a normal distribution lies within 2 standard deviations of the mean?", "The remainder is split equally between the two tails."],
    commonErrors: [
      { description: "Used both tails (5%) rather than the upper tail alone.", category: "CONCEPTUAL_ERROR", value: 0.05 },
      { description: "Used the one-standard-deviation tail (16%).", category: "MISREAD", value: 0.16 },
      { description: "Reported the proportion below 189 cm.", category: "CONCEPTUAL_ERROR", value: 0.977 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["normal", "z-score"],
    origin: "seeded",
  },
  {
    id: "it-probability-35",
    skill: "probability",
    subskill: "model_assumptions",
    concepts: ["distributions", "independence"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt:
      "A public-health analyst models the number of households on a street of 40 that report a stomach illness in a given week as Binomial(40, p). In which situation is this model most likely to be seriously wrong?",
    options: [
      "When the illness spreads between neighbouring households through shared water or contact",
      "When p is small, say 0.02",
      "When the number of households is large",
      "When each household either reports illness or does not, with no third option",
    ],
    answer: 0,
    solution:
      "The binomial distribution assumes a fixed number of trials, a constant probability of success, and independence between trials. Transmission between neighbours breaks independence: one case raises the probability of others, so the count will show more weeks with zero cases and more weeks with many cases than the binomial predicts (over-dispersion). Small p and large n are the binomial's normal working conditions, and a binary outcome is exactly what it models. Choosing a distribution is choosing a set of assumptions; the practical skill is to name the one most likely to fail in the setting at hand, and in contagion, finance and any social process, that is usually independence.",
    method: "List the binomial's assumptions (fixed n, constant p, independent trials) and test each against the setting.",
    hints: ["What three assumptions define a binomial count?", "Which of them does contagion violate?", "Small p, large n and binary outcomes are all fine for the binomial."],
    commonErrors: [
      { description: "Assumed the binomial fails for rare events; it handles small p correctly.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Assumed large n breaks the model; the binomial holds for any n.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Mistook the binary outcome, which the binomial requires, for a problem.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    tags: ["binomial", "assumptions", "epidemiology"],
    origin: "seeded",
  },
  {
    id: "it-probability-36",
    skill: "probability",
    subskill: "law_of_large_numbers",
    concepts: ["law-of-large-numbers", "independence"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A fair coin has been tossed 1,000 times and shown 530 heads. It will be tossed 9,000 more times. Which statement about the next 9,000 tosses is correct?",
    options: [
      "About 4,500 heads are expected; the overall proportion moves towards 0.5 while the excess of 30 heads is not cancelled",
      "Fewer than 4,500 heads are expected, so that the early excess is balanced out",
      "More than 4,500 heads are expected, because the coin is running hot",
      "The proportion of heads will stay near 0.53, since that is what the coin has shown",
    ],
    answer: 0,
    solution:
      "Each future toss is independent with P(heads) = 0.5, so 9,000 tosses are expected to give 4,500 heads regardless of the past. After 10,000 tosses the expected total is 530 + 4,500 = 5,030 heads, a proportion of 0.503; after a million, the same 30-head excess is a proportion of 0.50003. The law of large numbers works by swamping, not by correcting: the absolute excess stays, the proportion shrinks. Option 2 is the gambler's fallacy, option 3 the hot-hand belief, and option 4 mistakes a sample proportion from 1,000 tosses (530 heads is well within normal variation) for the coin's true probability.",
    method: "Separate the count from the proportion. Independence fixes the expected count of future tosses; division by a growing n drives the proportion to the true value.",
    hints: ["Do the next tosses know anything about the first 1,000?", "Compute the expected number of heads in 9,000 independent fair tosses.", "What happens to 30 extra heads when divided by 10,000, then by 1,000,000?"],
    commonErrors: [
      { description: "Expected future tosses to compensate for the past: the gambler's fallacy.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Expected the streak to continue: the hot-hand belief applied to a fair coin.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Took a sample proportion from 1,000 tosses as the coin's true probability.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["law-of-large-numbers", "gambler's-fallacy"],
    origin: "seeded",
  },
  {
    id: "it-probability-37",
    skill: "probability",
    subskill: "law_of_large_numbers",
    concepts: ["law-of-large-numbers", "variance-and-spread", "distributions"],
    level: "advanced",
    difficulty: 5,
    format: "numeric",
    prompt:
      "An insurer covers 10,000 houses against fire. Each house has a 1% chance of a claim in a year, independently of the others. The expected number of claims is 100. What is the standard deviation of the number of claims? Give a number to one decimal place.",
    answer: 9.95,
    tolerance: 0.1,
    solution:
      "The number of claims is Binomial(10,000, 0.01), whose variance is n p (1 − p) = 10,000 × 0.01 × 0.99 = 99, so the standard deviation is √99 ≈ 9.9. Relative to the mean of 100, that is about 10%: the insurer can be fairly confident of between roughly 80 and 120 claims. For a single house the outcome is all or nothing; for the pool it is a stable figure. This is the law of large numbers as a business model: pooling many independent risks turns unpredictable individual losses into a predictable total, and the premium can be set close to the expected loss plus a margin scaled to that standard deviation. The word doing the work is independent; a wildfire or a flood that hits many houses together destroys the pooling and can produce hundreds of claims in one event.",
    method: "Recognise a binomial count, apply Var = n p (1 − p), take the square root, and compare it with the mean.",
    hints: ["The number of claims is a binomial random variable. What is its variance formula?", "Compute 10,000 × 0.01 × 0.99.", "Take the square root."],
    commonErrors: [
      { description: "Reported the expected number of claims rather than the standard deviation.", category: "MISREAD", value: 100 },
      { description: "Reported the variance rather than its square root.", category: "PRECISION_ERROR", value: 99 },
    ],
    transfer: 2,
    minutes: 4,
    examEligible: true,
    tags: ["insurance", "binomial", "pooling"],
    origin: "seeded",
  },
  {
    id: "it-probability-38",
    skill: "probability",
    subskill: "monte_carlo",
    concepts: ["simulation-monte-carlo", "law-of-large-numbers", "variance-and-spread"],
    level: "advanced",
    difficulty: 4,
    format: "numeric",
    prompt:
      "A Monte Carlo simulation of a project schedule is run 10,000 times; in 1,340 runs the project misses its deadline, so the estimated probability of missing it is 0.134 with a standard error of about 0.0034. How many runs in total would be needed to halve that standard error?",
    answer: 40000,
    tolerance: 0,
    solution:
      "The standard error of a simulated proportion is √(p(1−p)/n), which shrinks with the square root of the number of runs, not with the number itself. Halving the error therefore needs four times the runs: 40,000. Check: √(0.134 × 0.866 / 40,000) ≈ 0.0017, half of 0.0034. This square-root law is the practical face of the law of large numbers and sets the economics of simulation: each extra decimal place of precision costs a hundred times more computation. It also means that the first few thousand runs deliver most of the value, and that if the answer is still uncertain after a million runs the problem is the model, not the sample size.",
    method: "Standard error scales as 1/√n; to divide it by k, multiply n by k².",
    hints: ["How does the standard error of a proportion depend on the number of runs?", "It falls with the square root of n.", "To halve √-scaled error, multiply n by 4."],
    commonErrors: [
      { description: "Doubled the runs, as if error fell in proportion to n.", category: "CONCEPTUAL_ERROR", value: 20000 },
      { description: "Quartered the runs, inverting the relationship.", category: "CONCEPTUAL_ERROR", value: 2500 },
    ],
    transfer: 1,
    minutes: 3,
    tags: ["monte-carlo", "standard-error"],
    origin: "seeded",
  },
  {
    id: "it-probability-39",
    skill: "probability",
    subskill: "monte_carlo",
    concepts: ["simulation-monte-carlo", "expected-value", "distributions"],
    level: "transfer",
    difficulty: 4,
    format: "mcq",
    prompt:
      "A project has three tasks done one after another. For each task the planner's most likely duration is 10 days, but each can overrun, occasionally by a lot; none can take less than 8 days. The planner adds the most likely durations and promises 30 days. A Monte Carlo simulation that samples each task's duration from its skewed distribution gives a median total of 36 days and a mean of 38. What best explains the gap?",
    options: [
      "Each task's mean exceeds its most likely value because of the long right tail; the mean of the sum is the sum of the means, so it sits above the sum of the modes",
      "The simulation is biased by random error and should be discarded",
      "The tasks must be dependent on each other for the total to exceed 30",
      "The planner's figure is right; the simulation simply used too few runs",
    ],
    answer: 0,
    solution:
      "For a right-skewed distribution the mode is below the mean; if each task's mean is about 12.7 days the total's mean is 3 × 12.7 ≈ 38, and its median falls a little below that. Adding modes is not a valid operation on random variables (the mode of a sum is not the sum of the modes), whereas expected values add exactly. The planner's 30 days is not an estimate of the total at all; it is the total in the single scenario where nothing overruns. Monte Carlo makes this visible by generating the whole distribution of outcomes rather than one hopeful path. Dependence between tasks would widen the spread but is not needed to move the centre, and more runs would sharpen the same answer, not change it.",
    method: "Check which summary statistics add across random variables (means do, modes do not) and whether the planner's number is a scenario rather than a statistic.",
    hints: ["For a distribution with a long right tail, which is larger: the mode or the mean?", "Which summary of a sum equals the sum of the summaries: mode, median or mean?", "What scenario does '10 + 10 + 10' actually describe?"],
    commonErrors: [
      { description: "Distrusted the simulation rather than the arithmetic of adding modes.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Invoked dependence, which affects the spread of the total but is not needed to shift its centre.", category: "ASSUMPTION", optionIndex: 2 },
      { description: "Assumed more runs would recover the planner's number; the simulation is estimating a different quantity.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 4,
    examEligible: true,
    tags: ["monte-carlo", "project-management", "skew"],
    origin: "seeded",
  },
  {
    id: "it-probability-40",
    skill: "probability",
    subskill: "monte_carlo",
    concepts: ["simulation-monte-carlo", "law-of-large-numbers"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt:
      "To estimate π, a program picks 10,000 points uniformly at random in the unit square (0 ≤ x ≤ 1, 0 ≤ y ≤ 1) and counts how many fall inside the quarter circle x² + y² ≤ 1. It finds 7,850. What estimate of π does this give?",
    answer: 3.14,
    tolerance: 0.01,
    solution:
      "The quarter circle has area π/4 and the square has area 1, so a uniform point lands inside with probability π/4. The observed fraction 7,850/10,000 = 0.785 estimates π/4, hence π ≈ 4 × 0.785 = 3.14. This is Monte Carlo integration in its simplest form: turn a deterministic quantity into the probability of an event, then estimate the probability by sampling. The estimate improves like 1/√n; 10,000 points give roughly ±0.03, which is why the method is used not for π but for problems in many dimensions where no other integration is feasible.",
    method: "Express the target as a probability (area ratio), estimate the probability by the sample fraction, and invert.",
    hints: ["What fraction of the square's area does the quarter circle occupy?", "The sample fraction 0.785 estimates that area ratio.", "Multiply by 4."],
    commonErrors: [
      { description: "Reported the sample fraction, forgetting to multiply by 4.", category: "ALGEBRA_ERROR", value: 0.785 },
      { description: "Multiplied by 2 instead of 4, as if the region were a half circle.", category: "ALGEBRA_ERROR", value: 1.57 },
    ],
    transfer: 1,
    minutes: 2,
    tags: ["monte-carlo", "integration"],
    origin: "seeded",
  },
  {
    id: "it-probability-41",
    skill: "probability",
    subskill: "monte_carlo",
    concepts: ["simulation-monte-carlo", "distributions", "independence"],
    level: "advanced",
    difficulty: 4,
    format: "free",
    prompt:
      "A colleague has built a Monte Carlo simulation of next year's cash flow for a small business and is about to present the results to its owner. In four to six sentences, explain to the owner what the simulation can tell them that a single forecast cannot, and what it cannot fix. Mention what the output looks like, what the result depends on, and how much to trust the numbers.",
    solution:
      "A strong answer says that the simulation produces a distribution of outcomes rather than one number, so the owner can read off a range, the probability of falling below a cash threshold, and the size of the bad tail. It says the result is only as good as the input assumptions: the distributions chosen for sales, costs and timing, and the correlations between them (a downturn hits sales and collections together, and simulating them as independent understates the risk). It notes that sampling error shrinks with the number of runs and is usually negligible next to model error, so more runs will not rescue bad assumptions. And it advises reading the output as a map of what could happen under the stated assumptions, to be revisited as real data arrives, not as a prediction.",
    method: "Distinguish output (a distribution, tails, threshold probabilities) from validity (assumptions, correlations) and from precision (runs, sampling error).",
    hints: ["What does a single forecast hide that a distribution shows?", "Where do the simulation's random inputs come from, and what happens if two of them move together in reality?", "Does running the model more times fix a wrong assumption?"],
    commonErrors: [{ description: "Presented the simulation's average as the forecast, discarding the distribution it exists to provide.", category: "CONCEPTUAL_ERROR", pattern: "the average is the forecast" }],
    transfer: 2,
    keyPoints: ["distribution|range of outcomes|spread of outcomes", "tail|worst case|probability of falling below|chance of running out", "assumption|inputs|garbage", "correlat|move together|independent", "runs|sampling error|more simulations|number of trials"],
    rubric: [
      { criterion: "Explains that the output is a distribution with tails and threshold probabilities, not a point forecast", weight: 0.35 },
      { criterion: "Identifies dependence on input assumptions and on correlations between inputs", weight: 0.35 },
      { criterion: "Separates sampling error (fixable by runs) from model error (not)", weight: 0.2 },
      { criterion: "Plain, calm language suitable for a non-specialist owner", weight: 0.1 },
    ],
    minutes: 8,
    tags: ["monte-carlo", "business", "explanation"],
    origin: "seeded",
  },
  {
    id: "it-probability-42",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem", "base-rates", "conditional-probability"],
    level: "intermediate",
    difficulty: 4,
    format: "numeric",
    prompt:
      "A factory makes bolts on two machines. Machine A produces 60% of output with a 2% defect rate; machine B produces 40% with a 5% defect rate. A bolt drawn at random from the day's output is found to be defective. What is the probability that it came from machine B? Give a decimal.",
    answer: 0.625,
    tolerance: 0.005,
    solution:
      "Of 1,000 bolts, A makes 600 and B makes 400. Defects: 0.02 × 600 = 12 from A and 0.05 × 400 = 20 from B, 32 in all. P(B | defective) = 20/32 = 0.625. B's higher defect rate outweighs its smaller share of output, so most defective bolts trace back to it, but not overwhelmingly: A still contributes three of every eight. Note the two different questions in this setting: P(defective | B) = 5% describes the machine, P(B | defective) = 62.5% describes where a found defect probably came from.",
    method: "Natural frequencies: split output by machine, count defects from each, take the share from the machine in question.",
    hints: ["Of 1,000 bolts, how many come from each machine?", "How many defective bolts does each machine contribute?", "B's defects divided by all defects."],
    commonErrors: [
      { description: "Answered with B's defect rate, P(defective | B), rather than P(B | defective).", category: "CONCEPTUAL_ERROR", value: 0.05 },
      { description: "Ignored the defect and gave B's share of output.", category: "BASE_RATE_NEGLECT", value: 0.4 },
      { description: "Stopped at the joint probability 0.4 × 0.05.", category: "CONCEPTUAL_ERROR", value: 0.02 },
    ],
    transfer: 1,
    minutes: 4,
    examOnly: true,
    tags: ["bayes", "quality-control"],
    origin: "seeded",
  },
  {
    id: "it-probability-43",
    skill: "probability",
    subskill: "binomial",
    concepts: ["distributions", "combinatorics", "randomness-and-sample-spaces"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A fair coin is tossed 4 times. What is the probability of exactly 2 heads? Give a decimal.",
    answer: 0.375,
    tolerance: 0.005,
    solution:
      "There are 2^4 = 16 equally likely sequences. Those with exactly two heads number C(4,2) = 6: HHTT, HTHT, HTTH, THHT, THTH, TTHH. So P(exactly 2 heads) = 6/16 = 0.375. The most likely count is not a certainty: even for the balanced outcome the probability is under 40%, and the remaining 62.5% is split between one head or three (4/16 each) and none or four (1/16 each).",
    method: "Count sequences with the required number of heads (a combination) over all 2^n sequences.",
    hints: ["How many sequences of four tosses are there?", "List or count the sequences with exactly two heads.", "6 out of 16."],
    commonErrors: [
      { description: "Assumed the balanced outcome has probability one half.", category: "CONCEPTUAL_ERROR", value: 0.5 },
      { description: "Gave the probability of one specific sequence, 1/16.", category: "CONCEPTUAL_ERROR", value: 0.0625 },
    ],
    transfer: 0,
    minutes: 2,
    examOnly: true,
    tags: ["binomial", "coins"],
    origin: "seeded",
  },
  {
    id: "it-probability-44",
    skill: "probability",
    subskill: "expected_value",
    concepts: ["expected-value", "random-variables"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A lottery sells exactly 1,000,000 tickets at £2 each and pays a single prize of £1,000,000 to one ticket drawn at random. What is the expected profit of buying one ticket, in pounds?",
    answer: -1,
    tolerance: 0.01,
    unit: "£",
    solution:
      "The expected prize is 1,000,000 × (1/1,000,000) = £1. The ticket costs £2, so the expected profit is 1 − 2 = −£1: on average the buyer loses half the stake. The lottery keeps £2,000,000 in sales and pays out £1,000,000, so its expected profit per ticket is the mirror image, +£1. As with the roulette bet, the expected value describes the average over many tickets, not what happens to any one buyer, who almost certainly loses £2 and very rarely gains £999,998.",
    method: "Expected prize = prize × probability; subtract the cost of the ticket.",
    hints: ["What is the probability of winning, and what is the prize?", "Multiply them to get the expected prize.", "Subtract the £2 cost."],
    commonErrors: [
      { description: "Reported the expected prize without subtracting the ticket price.", category: "MISREAD", value: 1 },
      { description: "Reported the cost as the loss, ignoring the prize entirely.", category: "CONCEPTUAL_ERROR", value: -2 },
    ],
    transfer: 0,
    minutes: 2,
    examOnly: true,
    tags: ["expected-value", "lottery"],
    origin: "seeded",
  },
  {
    id: "it-probability-45",
    skill: "probability",
    subskill: "permutations_with_repetition",
    concepts: ["combinatorics"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "How many distinct arrangements are there of the letters of the word LEVEL?",
    answer: 30,
    tolerance: 0,
    solution:
      "Five letters give 5! = 120 orderings if all were different, but LEVEL has two Ls and two Es. Swapping the two Ls produces the same word, and so does swapping the two Es, so each distinct arrangement has been counted 2! × 2! = 4 times. The number of distinct arrangements is 120 / 4 = 30. The general form is n! divided by the product of the factorials of the repetition counts. Dividing by only one of the 2!s (giving 60) is the usual slip; the check is to ask, for each repeated letter separately, how many ways its copies could be permuted without changing the word.",
    method: "Count all orderings, then divide by the factorial of each group of identical items.",
    hints: ["How many orderings would there be if all five letters were different?", "Which letters repeat, and how many times each?", "Divide 120 by 2! × 2!."],
    commonErrors: [
      { description: "Treated all five letters as distinct.", category: "CONCEPTUAL_ERROR", value: 120 },
      { description: "Divided by 2! only once, correcting for one repeated letter but not the other.", category: "ALGEBRA_ERROR", value: 60 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["permutations", "repetition"],
    origin: "seeded",
  },
  {
    id: "it-probability-46",
    skill: "probability",
    subskill: "counting_probability",
    concepts: ["combinatorics", "randomness-and-sample-spaces"],
    level: "intermediate",
    difficulty: 4,
    format: "numeric",
    prompt: "Five cards are dealt from a well-shuffled standard 52-card deck. What is the probability that all five are of the same suit? Give a decimal to three significant figures.",
    answer: 0.00198,
    tolerance: 0.0001,
    solution:
      "Every five-card hand is equally likely, and there are C(52,5) = 2,598,960 of them. Hands entirely within one particular suit number C(13,5) = 1,287; there are four suits, so 4 × 1,287 = 5,148 hands are single-suited. The probability is 5,148 / 2,598,960 ≈ 0.00198, about 1 in 505. The same answer comes from sequential conditioning: the first card can be anything, then 12/51 × 11/50 × 10/49 × 9/48 for the rest to match its suit. Forgetting the factor of 4 answers the question \"all five hearts\", not \"all five the same suit\"; (1/4)^5 assumes replacement, which dealing does not allow.",
    method: "Count favourable hands with combinations, multiply by the number of suits, divide by the total number of hands; cross-check by sequential conditioning.",
    hints: ["How many five-card hands are there in total? How many use only hearts?", "The hand can be any of the four suits.", "4 × C(13,5) / C(52,5)."],
    commonErrors: [
      { description: "Counted hands of one specific suit, forgetting the four suits.", category: "CONCEPTUAL_ERROR", value: 0.000495 },
      { description: "Used (1/4)^5, treating the deals as independent with replacement.", category: "CONCEPTUAL_ERROR", value: 0.000977 },
    ],
    transfer: 0,
    minutes: 4,
    examEligible: true,
    tags: ["cards", "combinations"],
    origin: "seeded",
  },
];
