import type { PracticeItem } from "@/lib/v2/content-types";

/**
 * Probability practice items, part A: sample spaces, rules, combinatorics, conditional
 * probability, independence and Bayes. Ids it-probability-01 … it-probability-23.
 *
 * Numeric answers are decimals unless a unit is given. Every commonErrors value is the
 * number a named mistake actually produces, so the classifier can attribute it.
 */
export const ITEMS_PROBABILITY_A: PracticeItem[] = [
  {
    id: "it-probability-01",
    skill: "probability",
    subskill: "sample_spaces",
    concepts: ["randomness-and-sample-spaces", "probability-rules"],
    level: "foundation",
    difficulty: 1,
    format: "numeric",
    prompt: "Two fair six-sided dice are rolled. What is the probability that the two numbers add up to 7? Give the answer as a decimal.",
    answer: 0.1667,
    tolerance: 0.005,
    solution:
      "List the sample space as ordered pairs (first die, second die): there are 6 × 6 = 36 equally likely outcomes. The pairs that sum to 7 are (1,6), (2,5), (3,4), (4,3), (5,2), (6,1): six of them. So P(sum = 7) = 6/36 = 1/6 ≈ 0.167. Two things matter here. First, the outcomes must be equally likely before you count them, which is why we use ordered pairs rather than the eleven possible sums. Second, (3,4) and (4,3) are different outcomes even though they look the same to someone reading the total.",
    method: "Write down a sample space of equally likely outcomes (ordered pairs), count the favourable ones, divide by the total.",
    hints: ["How many equally likely outcomes are there when two dice are rolled? Think of the dice as a red one and a blue one.", "List every ordered pair (red, blue) whose sum is 7. Is (3,4) the same outcome as (4,3)?", "Count the favourable pairs and divide by 36."],
    commonErrors: [
      { description: "Treated the eleven possible sums (2 to 12) as equally likely and answered 1/11.", category: "CONCEPTUAL_ERROR", value: 0.0909 },
      { description: "Counted unordered pairs only (three of them) out of 36, forgetting that (3,4) and (4,3) are distinct outcomes.", category: "CONCEPTUAL_ERROR", value: 0.0833 },
      { description: "Divided the target sum by 36 (7/36) rather than counting outcomes.", category: "CONCEPTUAL_ERROR", value: 0.1944 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["dice", "sample-space"],
    origin: "seeded",
  },
  {
    id: "it-probability-02",
    skill: "probability",
    subskill: "complement_rule",
    concepts: ["probability-rules", "independence"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A fair die is rolled four times. What is the probability of getting at least one six? Give the answer as a decimal.",
    answer: 0.518,
    tolerance: 0.005,
    solution:
      "\"At least one\" is the complement of \"none\". The probability of no six on a single roll is 5/6, and the rolls are independent, so P(no six in four rolls) = (5/6)^4 = 625/1296 ≈ 0.482. Therefore P(at least one six) = 1 − 0.482 ≈ 0.518. The tempting shortcut 4 × (1/6) = 0.667 is wrong because it adds the probabilities of events that can overlap (two sixes are possible); the addition rule only works without correction for mutually exclusive events. Note that the true value is a little over one half, which is why the old gambling wager \"at least one six in four rolls\" was profitable for the person offering it.",
    method: "Compute the complement (no successes) with the multiplication rule for independent trials, then subtract from 1.",
    hints: ["Is it easier to count the ways of getting at least one six, or the ways of getting none?", "Probability of no six on one roll is 5/6. What is it across four independent rolls?", "P(at least one) = 1 − (5/6)^4."],
    commonErrors: [
      { description: "Added 1/6 four times. The events overlap, so simple addition over-counts.", category: "CONCEPTUAL_ERROR", value: 0.6667 },
      { description: "Reported the probability of no six, forgetting to subtract from 1.", category: "MISREAD", value: 0.482 },
      { description: "Computed (1/6)^4, the probability of four sixes rather than at least one.", category: "CONCEPTUAL_ERROR", value: 0.00077 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["complement", "dice"],
    origin: "seeded",
  },
  {
    id: "it-probability-03",
    skill: "probability",
    subskill: "addition_rule",
    concepts: ["probability-rules", "randomness-and-sample-spaces"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt: "In a class of 30 students, 18 study French, 12 study German and 5 study both. A student is picked at random. What is the probability that the student studies French or German (or both)?",
    options: ["25/30", "30/30", "20/30", "13/30"],
    answer: 0,
    solution:
      "The general addition rule: P(F or G) = P(F) + P(G) − P(F and G). Counting students: 18 + 12 − 5 = 25, so the probability is 25/30 ≈ 0.833. The subtraction removes the five students who were counted twice, once as French and once as German. If you draw the two overlapping circles you can see the 25 directly: 13 French only, 5 both, 7 German only. The answer 30/30 would mean every student studies at least one language, which the numbers do not say; 13/30 is French only, not French or German.",
    method: "Apply P(A or B) = P(A) + P(B) − P(A and B); check with a two-circle diagram.",
    hints: ["Draw two overlapping circles. How many students are in the overlap?", "If you add 18 and 12, how many students have you counted twice?", "Subtract the overlap once: 18 + 12 − 5."],
    commonErrors: [
      { description: "Added 18 + 12 without subtracting the overlap, treating the events as mutually exclusive.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Subtracted the overlap twice (18 + 12 − 10).", category: "ALGEBRA_ERROR", optionIndex: 2 },
      { description: "Answered with the number who study French only.", category: "MISREAD", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["addition-rule", "venn"],
    origin: "seeded",
  },
  {
    id: "it-probability-04",
    skill: "probability",
    subskill: "probability_rules",
    concepts: ["probability-rules", "independence", "conditional-probability"],
    level: "basic",
    difficulty: 2,
    format: "multi_select",
    prompt: "Which of these statements hold for every pair of events A and B (no special assumptions)? Select all that apply.",
    options: [
      "P(A or B) = P(A) + P(B) − P(A and B)",
      "P(A and B) = P(A) × P(B)",
      "P(not A) = 1 − P(A)",
      "P(A | B) = P(B | A)",
      "If A and B are mutually exclusive, then P(A and B) = 0",
    ],
    answer: [0, 2, 4],
    solution:
      "The general addition rule (option 1), the complement rule (option 3) and the definition of mutual exclusivity (option 5) hold always. Option 2 is the multiplication rule for independent events; in general P(A and B) = P(A) × P(B | A), and only when B does not depend on A does that reduce to P(A) × P(B). Option 4 is false in general and is the single most consequential confusion in applied probability: the probability that a test is positive given disease is not the probability of disease given a positive test. The two are linked by Bayes' theorem through the base rates P(A) and P(B), and they can differ by orders of magnitude.",
    method: "Separate the rules that are definitions or always-true identities from those that need an assumption (independence) or are simply inversions.",
    hints: ["Which rule requires independence to be true?", "Think of a medical test: is P(positive | ill) the same as P(ill | positive)?", "Three of the five statements always hold."],
    commonErrors: [
      { description: "Selected the multiplication rule as universal; it requires independence.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Selected P(A | B) = P(B | A): the inverse-conditional confusion.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["rules"],
    origin: "seeded",
  },
  {
    id: "it-probability-05",
    skill: "probability",
    subskill: "combinations",
    concepts: ["combinatorics"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A committee of 3 people is to be chosen from 8 candidates. How many different committees are possible?",
    answer: 56,
    tolerance: 0,
    solution:
      "A committee has no order: choosing Ada, Ben and Cara is the same committee as choosing Cara, Ada and Ben. So this is a combination, C(8,3) = 8! / (3! × 5!) = (8 × 7 × 6) / (3 × 2 × 1) = 336 / 6 = 56. The 336 in the numerator counts ordered selections (8 choices, then 7, then 6); dividing by 3! = 6 removes the orderings of each group of three. The test for whether to divide is always the same: does swapping the order of the chosen items produce a different outcome? For a committee it does not.",
    method: "Decide whether order matters. It does not, so use C(n,k) = n! / (k!(n−k)!).",
    hints: ["Does the order in which committee members are picked matter?", "Count ordered picks first: 8 × 7 × 6. Each committee has been counted how many times?", "Divide 336 by 3! = 6."],
    commonErrors: [
      { description: "Counted ordered selections (8 × 7 × 6 = 336) without dividing out the orderings.", category: "CONCEPTUAL_ERROR", value: 336 },
      { description: "Computed 8^3, allowing the same person to be picked more than once.", category: "CONCEPTUAL_ERROR", value: 512 },
      { description: "Multiplied 8 × 3.", category: "CONCEPTUAL_ERROR", value: 24 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["combinations"],
    origin: "seeded",
  },
  {
    id: "it-probability-06",
    skill: "probability",
    subskill: "permutations",
    concepts: ["combinatorics"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A code consists of 4 different letters of the English alphabet (26 letters), in order, with no letter repeated. How many such codes are there?",
    answer: 358800,
    tolerance: 0,
    solution:
      "Order matters (ABCD and DCBA are different codes) and repetition is forbidden, so this is a permutation: 26 × 25 × 24 × 23 = 358,800. Each factor is the number of letters still available for that position. If repetition were allowed the count would be 26^4 = 456,976; if order did not matter it would be C(26,4) = 14,950, which is 358,800 divided by the 4! = 24 orderings of each set of four letters. Reading the problem for the two questions, does order matter and can items repeat, settles which formula applies before any arithmetic starts.",
    method: "Order matters and no repetition: multiply the shrinking number of choices, P(n,k) = n!/(n−k)!.",
    hints: ["Does ABCD count as the same code as DCBA?", "How many choices for the first letter? For the second, once one is used?", "Multiply 26 × 25 × 24 × 23."],
    commonErrors: [
      { description: "Used combinations, ignoring that the order of letters distinguishes codes.", category: "CONCEPTUAL_ERROR", value: 14950 },
      { description: "Allowed repeated letters (26^4) despite the problem forbidding them.", category: "MISREAD", value: 456976 },
    ],
    transfer: 0,
    minutes: 2,
    tags: ["permutations"],
    origin: "seeded",
  },
  {
    id: "it-probability-07",
    skill: "probability",
    subskill: "complement_and_counting",
    concepts: ["combinatorics", "probability-rules", "independence"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A room contains 23 people, birthdays independent and equally likely across 365 days. Which is closest to the probability that at least two of them share a birthday?",
    options: ["About 6%", "About 25%", "About 50%", "About 99%"],
    answer: 2,
    solution:
      "Work through the complement: the probability that all 23 birthdays are different. The second person avoids the first with probability 364/365, the third avoids both with 363/365, and so on down to 343/365 for the 23rd. The product of these 22 fractions is about 0.493, so the probability of at least one shared birthday is about 0.507. The intuition that says 6% (23 out of 365) is counting the wrong thing: it estimates the chance that someone shares a birthday with one specific person. What matters is the number of pairs, C(23,2) = 253, each of which is a chance for a match.",
    method: "Compute the complement (all different) as a product of shrinking fractions, then subtract from 1. Reason about pairs, not people.",
    hints: ["Is it easier to compute the probability that all 23 birthdays differ?", "How many pairs of people are there among 23? Each pair is a chance for a match.", "Multiply 364/365 × 363/365 × … × 343/365 and subtract from 1."],
    commonErrors: [
      { description: "Estimated 23/365, the chance of matching one fixed person rather than any pair.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Sensed the true value is higher than 6% but underestimated how quickly the number of pairs grows.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Overshot: 23 people is nowhere near enough for near-certainty (that takes about 60).", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 4,
    examEligible: true,
    tags: ["birthday-problem", "complement"],
    origin: "seeded",
  },
  {
    id: "it-probability-08",
    skill: "probability",
    subskill: "conditional_probability",
    concepts: ["conditional-probability"],
    level: "foundation",
    difficulty: 2,
    format: "numeric",
    prompt:
      "A survey of 200 commuters recorded how they travelled and whether they arrived late.\n\nCar: 120 commuters, of whom 30 were late.\nTrain: 80 commuters, of whom 12 were late.\n\nA commuter is picked at random and turns out to have travelled by train. What is the probability that this commuter was late? Give a decimal.",
    answer: 0.15,
    tolerance: 0.005,
    solution:
      "Conditioning on \"train\" shrinks the world to the 80 train commuters. Of those, 12 were late, so P(late | train) = 12/80 = 0.15. The denominator is the size of the condition, not the whole survey. Two neighbouring quantities are easy to confuse with this one: P(late and train) = 12/200 = 0.06 is the joint probability across everyone, and P(train | late) = 12/42 ≈ 0.29 answers the reverse question (given someone was late, how likely did they travel by train?). Writing the table out and putting a finger on the row you are conditioning on prevents both.",
    method: "Restrict the table to the conditioning row, then divide the favourable count by that row's total.",
    hints: ["Once you know the commuter took the train, how many people are still in play?", "Of those 80, how many were late?", "12 divided by 80."],
    commonErrors: [
      { description: "Computed P(train | late) = 12/42 instead of P(late | train): the inverse conditional.", category: "CONCEPTUAL_ERROR", value: 0.2857 },
      { description: "Divided by the whole survey (12/200), giving the joint probability rather than the conditional.", category: "CONCEPTUAL_ERROR", value: 0.06 },
      { description: "Reported the overall lateness rate 42/200.", category: "MISREAD", value: 0.21 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["table", "conditional"],
    origin: "seeded",
  },
  {
    id: "it-probability-09",
    skill: "probability",
    subskill: "conditional_probability",
    concepts: ["conditional-probability", "bayes-theorem"],
    level: "basic",
    difficulty: 3,
    format: "numeric",
    prompt:
      "A subscription business had 500 customers at the start of the year: 300 signed up through the mobile app and 200 through the website. During the year 45 of the app customers and 50 of the web customers cancelled.\n\nThe retention team pulls one cancelled customer's file at random. What is the probability that this customer had signed up through the app? Give a decimal.",
    answer: 0.4737,
    tolerance: 0.005,
    solution:
      "The condition is \"cancelled\", so the denominator is the number of cancellations: 45 + 50 = 95. Of those, 45 came from the app, so P(app | cancelled) = 45/95 ≈ 0.474. It is worth noticing that the app channel has the lower cancellation rate (45/300 = 15% against 50/200 = 25%) yet still supplies nearly half the cancellations, because it supplies more customers in the first place. That is the difference between P(cancelled | app), a rate that describes the channel, and P(app | cancelled), a share that describes the pile of cancelled files. A retention team that wanted to fix the worse channel would look at the first; one deciding where the cancellations come from would look at the second.",
    method: "Identify which event is the condition, build its total, and take the share of the target within it; distinguish rate-by-channel from share-of-outcome.",
    hints: ["What is given: that the customer cancelled. How many customers cancelled in total?", "How many of the cancellations came from the app?", "45 divided by 95."],
    commonErrors: [
      { description: "Computed the app's cancellation rate 45/300 = P(cancelled | app) instead of P(app | cancelled).", category: "CONCEPTUAL_ERROR", value: 0.15 },
      { description: "Divided by all 500 customers, giving the joint probability.", category: "CONCEPTUAL_ERROR", value: 0.09 },
      { description: "Reported the web channel's cancellation rate.", category: "MISREAD", value: 0.25 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["table", "business"],
    origin: "seeded",
  },
  {
    id: "it-probability-10",
    skill: "probability",
    subskill: "multiplication_rule",
    concepts: ["conditional-probability", "probability-rules"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "Two cards are drawn from a well-shuffled standard 52-card deck without replacement. What is the probability that both are aces? Give a decimal to four significant figures.",
    answer: 0.004525,
    tolerance: 0.0002,
    solution:
      "Use the general multiplication rule, P(A and B) = P(A) × P(B | A). The first card is an ace with probability 4/52. Given that, three aces remain among 51 cards, so the second is an ace with probability 3/51. The product is 12/2652 = 1/221 ≈ 0.00452. Squaring 4/52 (≈ 0.00592) would be right only if the first card were put back, which makes the draws independent; without replacement the second probability must be updated. The same structure, a probability that changes once the first outcome is known, appears whenever items are drawn from a finite pool: defective parts from a batch, names from a hat, patients from a ward.",
    method: "Multiply the first probability by the conditional probability of the second given the first.",
    hints: ["After one ace is drawn, how many aces and how many cards remain?", "Does the second draw have the same probability as the first?", "Multiply 4/52 by 3/51."],
    commonErrors: [
      { description: "Squared 4/52, treating the draws as independent as if the first card were replaced.", category: "CONCEPTUAL_ERROR", value: 0.005917 },
      { description: "Added the two probabilities instead of multiplying them.", category: "CONCEPTUAL_ERROR", value: 0.1357 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["cards", "without-replacement"],
    origin: "seeded",
  },
  {
    id: "it-probability-11",
    skill: "probability",
    subskill: "independence",
    concepts: ["independence", "probability-rules"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "Events A and B each have positive probability and cannot both occur (they are mutually exclusive). Which statement is correct?",
    options: [
      "A and B are never independent: learning that A occurred tells you B did not.",
      "A and B are always independent, because they have nothing to do with each other.",
      "A and B are independent only if P(A) = P(B).",
      "Whether they are independent cannot be judged without more information.",
    ],
    answer: 0,
    solution:
      "Independence means P(A and B) = P(A) × P(B), equivalently that learning A leaves the probability of B unchanged. For mutually exclusive events with positive probability, P(A and B) = 0 while P(A) × P(B) > 0, so the equation fails and the events are dependent, strongly so: once A happens, B is impossible. The everyday phrase \"nothing to do with each other\" is what misleads people; exclusivity is a very strong form of dependence, not the absence of one. Independence is about information, not about whether events can coincide.",
    method: "Test the definition P(A and B) = P(A)P(B) directly; do not rely on the ordinary-language sense of \"unrelated\".",
    hints: ["Write down what independence means as an equation.", "For mutually exclusive events, what is P(A and B)?", "Can 0 equal P(A) × P(B) when both are positive?"],
    commonErrors: [
      { description: "Confused mutually exclusive with independent; exclusivity is a strong dependence.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Invented a condition on equal probabilities; the definition involves the joint probability, not equality of marginals.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Did not recognise that the given facts determine the answer.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["independence", "mutually-exclusive"],
    origin: "seeded",
  },
  {
    id: "it-probability-12",
    skill: "probability",
    subskill: "independence",
    concepts: ["independence", "probability-rules"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A data centre has two backup generators. During a mains outage each generator fails to start with probability 0.05, and the two are assumed to fail independently. What is the probability that at least one generator starts? Give a decimal to four decimal places.",
    answer: 0.9975,
    tolerance: 0.0005,
    solution:
      "\"At least one starts\" is the complement of \"both fail\". With independence, P(both fail) = 0.05 × 0.05 = 0.0025, so P(at least one starts) = 1 − 0.0025 = 0.9975. Redundancy multiplies small failure probabilities together, which is why a second unit turns a 1-in-20 risk into a 1-in-400 risk. The assumption carrying that result is independence. If both generators share a fuel supply, a control circuit or a maintenance contractor who skipped the same test, the failures are correlated and the true risk is closer to the single-unit figure. Engineers call this common-cause failure; in probability terms it is the multiplication rule being applied where it does not hold.",
    method: "Find the probability of total failure by multiplying independent failure probabilities, then take the complement; state the independence assumption.",
    hints: ["What has to happen for no generator to start?", "Multiply the two failure probabilities if they are independent.", "Subtract that product from 1."],
    commonErrors: [
      { description: "Ignored redundancy and gave the single-generator success probability.", category: "CONCEPTUAL_ERROR", value: 0.95 },
      { description: "Added the failure probabilities (1 − 0.10), as if the failures were mutually exclusive.", category: "CONCEPTUAL_ERROR", value: 0.9 },
      { description: "Computed the probability that both start (0.95²) rather than at least one.", category: "MISREAD", value: 0.9025 },
    ],
    transfer: 1,
    minutes: 3,
    tags: ["reliability", "redundancy"],
    origin: "seeded",
  },
  {
    id: "it-probability-13",
    skill: "probability",
    subskill: "conditional_probability",
    concepts: ["conditional-probability", "independence", "probability-rules"],
    level: "advanced",
    difficulty: 5,
    format: "numeric",
    prompt:
      "In tennis a game at deuce is won by the first player to lead by two points. Suppose the server wins each point independently with probability 0.6. Starting from deuce, what is the probability that the server wins the game? Give a decimal to three decimal places.",
    answer: 0.6923,
    tolerance: 0.005,
    solution:
      "From deuce, consider the next two points. The server wins both with probability 0.6 × 0.6 = 0.36 and takes the game; loses both with probability 0.4 × 0.4 = 0.16 and loses the game; and with probability 2 × 0.6 × 0.4 = 0.48 they split and the game returns to deuce, where the situation is exactly as before. Let W be the probability the server wins from deuce. Then W = 0.36 + 0.48 × W, so W(1 − 0.48) = 0.36 and W = 0.36 / 0.52 ≈ 0.692. Equivalently W = p² / (p² + q²), the chance of winning conditional on the game ending in the next two points. A 60% point-winner becomes a 69% game-winner from deuce; the structure of the game amplifies small edges, which is the same reason best-of-five matches favour the stronger player more than single sets do.",
    method: "Condition on the next two points; the split case returns to the same state, so write a self-referential equation and solve it.",
    hints: ["What are the three possible results of the next two points, and their probabilities?", "One of the three outcomes brings the game back to deuce, the same situation you started in.", "Write W = 0.36 + 0.48 × W and solve for W."],
    commonErrors: [
      { description: "Gave the single-point probability; the game structure changes the odds.", category: "CONCEPTUAL_ERROR", value: 0.6 },
      { description: "Stopped at the probability of winning the next two points, forgetting that a split returns to deuce.", category: "CONCEPTUAL_ERROR", value: 0.36 },
      { description: "Assumed deuce makes the game a coin toss.", category: "ASSUMPTION", value: 0.5 },
    ],
    transfer: 2,
    minutes: 6,
    examEligible: true,
    tags: ["sport", "recursion"],
    origin: "seeded",
  },
  {
    id: "it-probability-14",
    skill: "probability",
    subskill: "independence",
    concepts: ["independence", "randomness-and-sample-spaces"],
    level: "foundation",
    difficulty: 1,
    format: "short",
    prompt: "A roulette wheel has come up red seven times in a row. A player doubles their stake on black because black is \"due\". What is the name of the reasoning error?",
    answer: "gambler's fallacy",
    accept: ["gamblers fallacy", "the gambler's fallacy", "gambler fallacy", "the gamblers fallacy", "monte carlo fallacy"],
    solution:
      "This is the gambler's fallacy (sometimes the Monte Carlo fallacy, after a famous 1913 run of 26 blacks at the Monte Carlo casino). Each spin is independent: the wheel has no memory, so the probability of black on the next spin is the same as on any spin, about 18/37 on a European wheel. The law of large numbers says the proportion of reds will approach its long-run value over many spins, but it does so by dilution, not by compensation; there is no force that makes black more likely after a run of reds. The opposite error, betting on red because it is \"hot\", is equally unfounded when spins are independent.",
    method: "Ask whether the trials are independent; if they are, past outcomes carry no information about the next one.",
    hints: ["Does the wheel remember previous spins?", "The name comes from casinos."],
    commonErrors: [{ description: "Named the hot-hand fallacy, which is the opposite error (expecting the run to continue).", category: "CONCEPTUAL_ERROR", pattern: "hot hand" }],
    transfer: 0,
    minutes: 1,
    tags: ["fallacy"],
    origin: "seeded",
  },
  {
    id: "it-probability-15",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem", "base-rates", "conditional-probability"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt:
      "A disease affects 1% of the population. A screening test detects the disease in 90% of people who have it (sensitivity 90%) and gives a negative result for 90% of people who do not have it (specificity 90%). A person from this population tests positive. What is the probability that they actually have the disease? Give a decimal.",
    answer: 0.0833,
    tolerance: 0.003,
    solution:
      "Take 10,000 people. About 100 have the disease; the test catches 90 of them (true positives). About 9,900 do not; the test wrongly flags 10% of them, 990 false positives. Total positives: 90 + 990 = 1,080. The probability of disease given a positive test is 90 / 1,080 ≈ 0.083, about 1 in 12. In formula form: P(D | +) = P(+ | D)P(D) / [P(+ | D)P(D) + P(+ | not D)P(not D)] = (0.9 × 0.01) / (0.009 + 0.099). The test is genuinely informative, raising the probability from 1% to 8%, but the rare condition means false positives outnumber true ones eleven to one. Confusing the 90% sensitivity with the answer is the classic base-rate neglect; the sensitivity is P(+ | D), which is not the question asked.",
    method: "Use natural frequencies: pick a population, split by disease status, apply the test to each group, and take true positives over all positives.",
    hints: ["Imagine 10,000 people. How many have the disease? How many do not?", "How many true positives does the test produce? How many false positives from the healthy group?", "Divide true positives by all positives: 90 / (90 + 990)."],
    commonErrors: [
      { description: "Answered with the sensitivity, ignoring the 1% base rate.", category: "BASE_RATE_NEGLECT", value: 0.9 },
      { description: "Stopped at the joint probability P(disease and positive) = 0.009 without dividing by P(positive).", category: "CONCEPTUAL_ERROR", value: 0.009 },
      { description: "Divided by the false-positive rate alone (0.009 / 0.1), leaving true positives out of the denominator.", category: "ALGEBRA_ERROR", value: 0.09 },
      { description: "Multiplied sensitivity by specificity.", category: "CONCEPTUAL_ERROR", value: 0.81 },
    ],
    transfer: 0,
    minutes: 5,
    examEligible: true,
    tags: ["bayes", "medical-test", "natural-frequencies"],
    origin: "seeded",
  },
  {
    id: "it-probability-16",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem", "base-rates"],
    level: "intermediate",
    difficulty: 4,
    format: "numeric",
    prompt:
      "A city's taxis are 85% green and 15% blue. A taxi was involved in a hit-and-run at night. A witness says the taxi was blue. Tested under similar conditions, the witness correctly identifies the colour 80% of the time and is wrong 20% of the time. What is the probability that the taxi was in fact blue? Give a decimal.",
    answer: 0.4138,
    tolerance: 0.005,
    solution:
      "Two routes lead to the witness saying \"blue\": the taxi was blue and the witness was right (0.15 × 0.8 = 0.12), or the taxi was green and the witness was wrong (0.85 × 0.2 = 0.17). The probability of the report is 0.12 + 0.17 = 0.29, and the share of it that comes from an actually blue taxi is 0.12 / 0.29 ≈ 0.41. So despite a witness who is right four times out of five, the taxi is more likely green than blue, because there are so many more green taxis to be mistaken about. This is Kahneman and Tversky's cab problem; most people answer close to 80%, using the witness's reliability and discarding the base rate. The base rate is not a technicality: it is the prior that the evidence updates.",
    method: "Enumerate both ways the evidence could arise (hypothesis true and witness right; hypothesis false and witness wrong), then take the share from the true-hypothesis path.",
    hints: ["Out of 100 taxis, how many are blue and how many green?", "How many of the 15 blue taxis would the witness call blue? How many of the 85 green taxis would the witness wrongly call blue?", "Divide correct blue reports by all blue reports: 12 / (12 + 17)."],
    commonErrors: [
      { description: "Answered with the witness's reliability, neglecting that 85% of taxis are green.", category: "BASE_RATE_NEGLECT", value: 0.8 },
      { description: "Stopped at the joint probability 0.15 × 0.8 = 0.12.", category: "CONCEPTUAL_ERROR", value: 0.12 },
      { description: "Ignored the witness entirely and gave the base rate.", category: "ASSUMPTION", value: 0.15 },
      { description: "Gave the witness's error rate, P(says blue | green).", category: "CONCEPTUAL_ERROR", value: 0.2 },
    ],
    transfer: 1,
    minutes: 5,
    examEligible: true,
    tags: ["bayes", "cab-problem"],
    origin: "seeded",
  },
  {
    id: "it-probability-17",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem", "conditional-probability"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt:
      "In a mail system 20% of incoming messages are spam. The word \"offer\" appears in 60% of spam messages and in 5% of legitimate messages. A new message contains the word \"offer\". What is the probability that it is spam? Give a decimal.",
    answer: 0.75,
    tolerance: 0.005,
    solution:
      "Out of 1,000 messages, 200 are spam and 800 legitimate. \"Offer\" appears in 0.6 × 200 = 120 spam messages and in 0.05 × 800 = 40 legitimate ones. Among the 160 messages containing the word, 120 are spam: P(spam | offer) = 120/160 = 0.75. The word moves the probability from a prior of 20% to a posterior of 75%, a strong but not conclusive signal; a real filter combines many such words, updating the odds with each one. The number to avoid is 60%, which is P(offer | spam), the frequency of the word in spam, not the probability of spam given the word. That inversion is the same mistake as reading a test's sensitivity as its predictive value.",
    method: "Convert to natural frequencies, count the messages carrying the word in each class, and take the spam share of that count.",
    hints: ["Of 1,000 messages, how many are spam and how many legitimate?", "How many in each group contain the word?", "Spam with the word divided by all messages with the word."],
    commonErrors: [
      { description: "Answered P(offer | spam) = 0.6 instead of P(spam | offer): the inverse conditional.", category: "CONCEPTUAL_ERROR", value: 0.6 },
      { description: "Stopped at the joint probability 0.2 × 0.6 = 0.12.", category: "CONCEPTUAL_ERROR", value: 0.12 },
      { description: "Took 1 − 0.05, the probability a legitimate message lacks the word.", category: "CONCEPTUAL_ERROR", value: 0.95 },
      { description: "Ignored the evidence and gave the base rate.", category: "ASSUMPTION", value: 0.2 },
    ],
    transfer: 1,
    minutes: 4,
    tags: ["bayes", "spam-filter"],
    origin: "seeded",
  },
  {
    id: "it-probability-18",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem", "base-rates", "conditional-probability"],
    level: "transfer",
    difficulty: 5,
    format: "numeric",
    prompt:
      "An auction house receives letters attributed to a famous eighteenth-century general. From long experience, about 10% of such letters offered to it are forgeries. Its expert declares a letter \"genuine\" for 95% of genuine letters and declares \"forgery\" for 70% of forgeries.\n\nThe expert has just declared a newly arrived letter a forgery. What is the probability that the letter is in fact genuine? Give a decimal.",
    answer: 0.3913,
    tolerance: 0.005,
    solution:
      "Take 1,000 letters. 900 are genuine and 100 are forgeries. The expert wrongly calls 5% of the genuine ones forgeries: 45. The expert correctly calls 70% of the forgeries forgeries: 70. So 115 letters receive a \"forgery\" verdict, and 45 of them, about 39%, are genuine. Even a good expert, applied to a population where genuine letters dominate nine to one, produces a \"forgery\" pile that is nearly two-fifths authentic. The historian's lesson is the same as the physician's: a verdict is evidence, not a fact, and its weight depends on how common each hypothesis was before the verdict. The 5% figure, P(\"forgery\" | genuine), is not P(genuine | \"forgery\"); the second requires the base rate and the total number of forgery verdicts.",
    method: "Set up the four cells (genuine/forgery × verdict) with natural frequencies, then take the genuine share of the \"forgery\" column.",
    hints: ["Of 1,000 letters, how many are genuine? How many of those does the expert wrongly call forgeries?", "How many actual forgeries does the expert correctly call forgeries?", "Genuine-but-called-forgery divided by all called-forgery: 45 / (45 + 70)."],
    commonErrors: [
      { description: "Answered 0.05, the rate of forgery verdicts among genuine letters, rather than the genuine share of forgery verdicts.", category: "CONCEPTUAL_ERROR", value: 0.05 },
      { description: "Stopped at the joint probability 0.9 × 0.05 = 0.045.", category: "CONCEPTUAL_ERROR", value: 0.045 },
      { description: "Ignored the verdict and gave the base rate of genuine letters.", category: "ASSUMPTION", value: 0.9 },
      { description: "Used the expert's miss rate on forgeries, P(\"genuine\" | forgery) = 0.3.", category: "MISREAD", value: 0.3 },
    ],
    transfer: 3,
    minutes: 6,
    examEligible: true,
    tags: ["bayes", "history", "attribution"],
    origin: "seeded",
  },
  {
    id: "it-probability-19",
    skill: "probability",
    subskill: "bayes",
    concepts: ["bayes-theorem"],
    level: "basic",
    difficulty: 2,
    format: "ordering",
    prompt: "Put the steps of a Bayesian update in the order an expert would carry them out.",
    options: [
      "State the prior probability of each hypothesis (the base rate)",
      "For each hypothesis, find the probability of observing the evidence if that hypothesis were true (the likelihood)",
      "Multiply each prior by its likelihood",
      "Add the products to get the total probability of the evidence",
      "Divide each product by the total to get the posterior probabilities",
      "Check the posteriors against a natural-frequency sketch before acting on them",
    ],
    solution:
      "The order is prior, likelihood, product, normalise, posterior, check. The prior comes first because the likelihoods are meaningless without something to weight: P(E | H) tells you how expected the evidence is under H, not how probable H is. Multiplying prior by likelihood gives the joint probability of each (hypothesis, evidence) pair; the sum of those joints is P(E), and dividing by it turns joints into conditional probabilities that add to one. The final check is not decoration: most Bayes errors are arithmetic slips or inverted conditionals, and a quick sketch with 1,000 imagined cases catches both.",
    method: "Prior → likelihood → joint → normalise → posterior → sanity check.",
    hints: ["What must you know before evidence can update anything?", "Normalising means dividing by the total probability of the evidence."],
    commonErrors: [{ description: "Placed the likelihood before the prior, reflecting the habit of starting from the evidence and forgetting the base rate.", category: "BASE_RATE_NEGLECT" }],
    transfer: 0,
    minutes: 2,
    tags: ["bayes", "procedure"],
    origin: "seeded",
  },
  {
    id: "it-probability-20",
    skill: "probability",
    subskill: "bayes_vocabulary",
    concepts: ["bayes-theorem", "base-rates"],
    level: "foundation",
    difficulty: 1,
    format: "short",
    prompt: "In Bayes' theorem, what is the name for the probability assigned to a hypothesis before the evidence is taken into account?",
    answer: "prior",
    accept: ["prior probability", "the prior", "prior belief", "base rate", "the base rate"],
    solution:
      "It is the prior (prior probability). When the hypothesis is membership of a category, such as \"has the disease\" or \"is spam\", the prior is usually estimated from the base rate, the frequency of that category in the relevant population. The evidence updates the prior into the posterior through the likelihood ratio. Naming the parts matters because base-rate neglect is precisely the habit of dropping the prior and reasoning from the likelihood alone.",
    method: "Recall the vocabulary: prior, likelihood, posterior.",
    hints: ["The word contrasts with 'posterior'.", "It comes from the Latin for 'before'."],
    commonErrors: [{ description: "Named the posterior, which is the probability after the evidence.", category: "CONCEPTUAL_ERROR", pattern: "posterior" }],
    transfer: 0,
    minutes: 1,
    tags: ["vocabulary"],
    origin: "seeded",
  },
  {
    id: "it-probability-21",
    skill: "probability",
    subskill: "sample_size",
    concepts: ["law-of-large-numbers", "variance-and-spread", "distributions"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt:
      "A town has two hospitals. In the larger one about 45 babies are born each day; in the smaller one about 15. Overall, half of babies are boys, but the exact proportion varies from day to day. For a year, each hospital records the days on which more than 60% of the babies born were boys. Which hospital recorded more such days?",
    options: ["The larger hospital (45 births a day)", "The smaller hospital (15 births a day)", "About the same for both"],
    answer: 1,
    solution:
      "The smaller hospital. A day's proportion of boys is an average over that day's births, and averages over fewer cases fluctuate more: the standard deviation of a proportion from n births is roughly 0.5/√n, about 0.13 for 15 births and 0.075 for 45. A proportion above 60% is an excursion of 0.1 above the mean, which is under one standard deviation for the small hospital and well over one for the large one, so the small hospital crosses the line far more often. This is the law of large numbers seen from the other side: large samples hug the true rate, small samples wander. In Kahneman and Tversky's original study most respondents answered \"about the same\", judging by the representativeness of 60% rather than the size of the sample.",
    method: "Ask how variable a daily proportion is as a function of the number of cases; smaller n means larger swings.",
    hints: ["Which is more surprising: 9 boys out of 15 births, or 27 out of 45?", "Averages over more cases vary less from day to day.", "The standard deviation of a proportion shrinks like 1/√n."],
    commonErrors: [
      { description: "Chose the larger hospital, perhaps reasoning that more births give more chances for an extreme day; but the proportion, not the count, is what is being judged.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Judged that sample size makes no difference to the variability of a proportion.", category: "STATISTICAL_ERROR", optionIndex: 2 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["sample-size", "kahneman-tversky"],
    origin: "seeded",
  },
  {
    id: "it-probability-22",
    skill: "probability",
    subskill: "base_rates",
    concepts: ["base-rates", "bayes-theorem"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt:
      "In a rural county there are 20 male farmers for every male librarian. A man from the county is described as shy, tidy and fond of reading. Suppose that description fits about 40% of the librarians and about 5% of the farmers. Is the man more likely to be a farmer or a librarian?",
    options: [
      "A librarian, because the description fits a librarian much better",
      "A farmer: the description is 8 times more typical of librarians, but farmers outnumber librarians 20 to 1",
      "Equally likely, since the description points one way and the numbers the other",
      "It cannot be said without knowing how common shyness is in the general population",
    ],
    answer: 1,
    solution:
      "Take 21 men in the ratio given: 20 farmers and 1 librarian. The description fits 0.05 × 20 = 1 farmer and 0.4 × 1 = 0.4 librarians. Among men fitting the description, farmers outnumber librarians 1 to 0.4, so the man is a farmer with probability 1 / 1.4 ≈ 71%. The description is real evidence, and it moves the odds from 20:1 to 2.5:1, but not far enough to overturn the base rate. This is Kahneman and Tversky's \"Steve\" problem; people answer \"librarian\" because they judge by resemblance to the stereotype (representativeness) and the base rate never enters. The general rule: posterior odds = prior odds × likelihood ratio, and a likelihood ratio of 8 does not beat prior odds of 20.",
    method: "Multiply prior odds by the likelihood ratio; compare the result with 1.",
    hints: ["Of 21 men, how many are farmers and how many librarians?", "How many of each fit the description?", "Compare 20 × 0.05 with 1 × 0.4."],
    commonErrors: [
      { description: "Judged by resemblance to the stereotype and ignored the 20-to-1 base rate.", category: "BASE_RATE_NEGLECT", optionIndex: 0 },
      { description: "Treated two opposing considerations as cancelling instead of multiplying odds by the likelihood ratio.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Asked for information not needed: the likelihoods for each group are already given.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["base-rates", "representativeness"],
    origin: "seeded",
  },
  {
    id: "it-probability-23",
    skill: "probability",
    subskill: "expected_value",
    concepts: ["expected-value", "random-variables"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A European roulette wheel has 37 pockets (0 and 1 to 36). A £1 bet on a single number pays 35 to 1: if the number comes up you keep your £1 and receive £35, otherwise you lose the £1. What is the expected profit of this bet, in pounds? Give a decimal (negative if the bet loses on average).",
    answer: -0.027,
    tolerance: 0.0005,
    unit: "£",
    solution:
      "The profit is a random variable with two values: +35 with probability 1/37 and −1 with probability 36/37. Its expected value is 35 × (1/37) − 1 × (36/37) = (35 − 36)/37 = −1/37 ≈ −£0.027, a loss of 2.7 pence per pound staked. The payout of 35 to 1 is set just below the fair odds of 36 to 1, and that single missing unit is the house edge. Expected value does not describe any particular spin, on which you either win £35 or lose £1; it describes the average per bet over a long run, which is what the casino, but not the individual gambler, experiences.",
    method: "List outcomes with probabilities, multiply value by probability, add.",
    hints: ["What are the two possible profits, and with what probabilities?", "Multiply each profit by its probability and add.", "35/37 − 36/37."],
    commonErrors: [
      { description: "Assumed the bet is fair because the payout looks proportionate.", category: "CONCEPTUAL_ERROR", value: 0 },
      { description: "Counted only the winning branch (35/37), leaving out the loss term.", category: "ALGEBRA_ERROR", value: 0.9459 },
      { description: "Used 38 pockets, the American wheel, whose two zeros give −2/38.", category: "MISREAD", value: -0.0526 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["expected-value", "gambling"],
    origin: "seeded",
  },
];
