import type { PracticeItem } from "@/lib/v2/content-types";

/**
 * Practice items for statistics. Ids: it-statistics-<nn>. British spelling throughout.
 *
 * 01–04 describing data and correlation; 05–08 sampling, bias and standard error; 09–10 confidence
 * intervals; 11–12 tests and p-values; 13–15 effect sizes and power; 16–17 regression reading;
 * 18 multiple comparisons; 19–21 regression to the mean, Simpson's paradox and reading a study;
 * 22–23 charts and study design; 27–32 items written for lesson transfer steps.
 * 24–26 are exam-only and never appear in Train or in a lesson.
 *
 * Every numeric commonErrors value is the number a named mistake actually produces, so the
 * classifier can attribute it. Numeric answers are decimals unless a unit is given.
 */
export const ITEMS_STATISTICS: PracticeItem[] = [
  /* ---------------------------------------------------------------- */
  /* Describing data                                                    */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-01",
    skill: "statistics",
    subskill: "standard_deviation",
    concepts: ["descriptive-statistics", "variance-and-spread"],
    level: "foundation",
    difficulty: 1,
    format: "numeric",
    prompt: "Five measurements: 4, 8, 6, 5, 7. Compute the sample standard deviation (divide the sum of squared deviations by n − 1). Give two decimal places.",
    answer: 1.58,
    tolerance: 0.02,
    solution:
      "Mean = (4 + 8 + 6 + 5 + 7)/5 = 30/5 = 6. Deviations from the mean: −2, 2, 0, −1, 1. Squared: 4, 4, 0, 1, 1, which sum to 10. Sample variance = 10/(n − 1) = 10/4 = 2.5. Standard deviation = √2.5 ≈ 1.58. Two checks: the deviations sum to zero (they always do, which is why they are squared rather than averaged), and the answer is in the original units, between the smallest and largest deviation, as a standard deviation should be. Dividing by n instead gives √2 ≈ 1.41, the population formula; for a sample it slightly understates the spread because deviations are measured from the sample's own mean.",
    method: "Mean, then deviations, then squares, then divide by n − 1, then square root.",
    hints: ["Start with the mean. It is a whole number here.", "Subtract the mean from each value, square each difference, and add them up.", "Divide the sum of squares by 4 (n − 1), then take the square root."],
    commonErrors: [
      { description: "Divided by n rather than n − 1, giving the population standard deviation the prompt did not ask for.", category: "MISREAD", value: 1.41 },
      { description: "Stopped at the variance and did not take the square root.", category: "ALGEBRA_ERROR", value: 2.5 },
      { description: "Population variance: divided by n and did not take the square root.", category: "ALGEBRA_ERROR", value: 2 },
      { description: "Averaged the absolute deviations (mean absolute deviation) instead of squaring.", category: "CONCEPTUAL_ERROR", value: 1.2 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["descriptive", "spread"],
    origin: "seeded",
  },
  {
    id: "it-statistics-02",
    skill: "statistics",
    subskill: "centre_and_skew",
    concepts: ["descriptive-statistics"],
    level: "foundation",
    difficulty: 1,
    format: "mcq",
    prompt: "A report on household incomes in a town gives a mean of £41,000 and a median of £31,000. Which statement follows from these two numbers alone?",
    options: [
      "The distribution is right-skewed: a minority of high incomes pulls the mean above the median.",
      "The distribution is left-skewed: a minority of very low incomes pulls the median below the mean.",
      "More than half of households earn above £41,000.",
      "The mean is the better figure for a typical household because it uses every value.",
    ],
    answer: 0,
    solution:
      "The median is the value half the households sit below. The mean is the balance point and moves with every value, so a long tail of high incomes drags it upward while leaving the median alone. Mean above median therefore means a right tail: a right-skewed distribution, which is what incomes, house prices and waiting times usually show. Option 2 has the direction backwards: very low incomes would pull the mean down, not the median. Option 3 is contradicted directly: half of households earn below £31,000, so fewer than half can be above £41,000. Option 4 is a matter of purpose, not of arithmetic; for 'a typical household' the median is the honest figure precisely because it does not respond to the tail.",
    method: "Compare mean and median; the mean sits on the side of the longer tail. Read 'median' as 'half are below'.",
    hints: ["Which of the two statistics does one very high income move, and which does it leave alone?", "If the mean sits above the median, on which side is the long tail?", "Half of households earn below the median. Can more than half earn above the mean?"],
    commonErrors: [
      { description: "Reversed the direction of skew, reading the low median as evidence of a low tail.", category: "CONCEPTUAL_ERROR", optionIndex: 1 },
      { description: "Treated the mean as the halfway point of the distribution.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Preferred the mean as 'typical' because it uses all the data, which is exactly why it is not typical here.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["descriptive", "skew"],
    origin: "seeded",
  },
  {
    id: "it-statistics-03",
    skill: "statistics",
    subskill: "correlation_interpretation",
    concepts: ["correlation", "correlation-vs-causation"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Across the twelve months of a year, a coastal town's ice-cream sales and its number of drownings have a correlation of r = 0.85. Which is the best reading of that figure?",
    options: [
      "The two series move together strongly and roughly linearly across months; the figure says nothing about whether either causes the other.",
      "About 85 % of drownings are attributable to ice-cream consumption.",
      "Ice-cream sales explain 85 % of the variation in drownings.",
      "Each additional unit of ice-cream sales is associated with 0.85 additional drownings.",
    ],
    answer: 0,
    solution:
      "r measures how tightly two variables move together along a straight line, from −1 to +1. A value of 0.85 is a strong positive linear association: months with high sales tend to be months with many drownings. That is all it says. Both series rise in summer because more people are outdoors and in the water, so a third variable (season, temperature) accounts for the co-movement; r cannot tell you that, but it cannot rule it out either. Option 2 reads r as an attributable fraction, which it is not. Option 3 confuses r with r²: the share of variance shared is 0.85² ≈ 0.72, and even that is a description, not an explanation. Option 4 confuses r with a regression slope, which has units (drownings per unit of sales) and can be any size at all for a given r.",
    method: "State what r measures (strength and direction of a linear association), then separate it from slope, from r² and from any causal reading.",
    hints: ["What is the range of r, and does it carry units?", "What happens to both series in July, and why?", "Which option is a claim about association only?"],
    commonErrors: [
      { description: "Read the correlation as a causal share.", category: "CAUSAL_ERROR", optionIndex: 1 },
      { description: "Confused r with r², the proportion of variance shared.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Confused the correlation coefficient with a regression slope.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["correlation"],
    origin: "seeded",
  },
  {
    id: "it-statistics-04",
    skill: "statistics",
    subskill: "correlation_and_r_squared",
    concepts: ["correlation"],
    level: "foundation",
    difficulty: 1,
    format: "numeric",
    prompt: "Two variables have a correlation of r = −0.6. What proportion of the variance in one is accounted for by a straight-line relationship with the other? Give a decimal.",
    answer: 0.36,
    tolerance: 0.005,
    solution:
      "The share of variance accounted for by the linear fit is r², so (−0.6)² = 0.36. The sign disappears in the squaring: a negative correlation of −0.6 is exactly as strong as a positive one of 0.6, just in the opposite direction. Note how much smaller 0.36 is than 0.6. A correlation that sounds respectable leaves nearly two-thirds of the variance unaccounted for, which is why r alone flatters a relationship and why the squared figure is worth computing before being impressed.",
    method: "Square the correlation coefficient; ignore the sign.",
    hints: ["The quantity asked for is r², not r.", "Squaring removes the minus sign.", "0.6 × 0.6."],
    commonErrors: [
      { description: "Reported r itself rather than r².", category: "CONCEPTUAL_ERROR", value: 0.6 },
      { description: "Reported −0.36, keeping the sign after squaring.", category: "ALGEBRA_ERROR", value: -0.36 },
      { description: "Took the square root instead of the square.", category: "ALGEBRA_ERROR", value: 0.77 },
      { description: "Computed 1 − r, treating the correlation as a share.", category: "CONCEPTUAL_ERROR", value: 0.4 },
    ],
    transfer: 0,
    minutes: 1,
    examEligible: false,
    tags: ["correlation"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Sampling, bias, standard error                                     */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-05",
    skill: "statistics",
    subskill: "sampling_bias",
    concepts: ["sampling-and-bias", "selection-bias"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A city council places a survey link on its cycling web page asking whether residents support a new cycle lane. It receives 3,400 responses, 82 % in favour, and reports that residents strongly support the lane. What is the principal weakness of this conclusion?",
    options: [
      "Respondents selected themselves from people who visit a cycling page and cared enough to answer; a larger sample of the same kind would not remove that bias.",
      "The sample is too small: a city of 400,000 needs at least 10,000 responses before any conclusion is possible.",
      "There is no serious weakness: with n = 3,400 the margin of error is about ±1.3 percentage points, so 82 % is a precise estimate.",
      "The survey should have used a paper questionnaire, since online surveys always exclude older residents.",
    ],
    answer: 0,
    solution:
      "The 3,400 people who answered are not a random draw from the city. They are people who visited a cycling page and chose to respond, and both filters select for interest in cycling. Whatever the true level of support, this sample is systematically tilted toward it, and that tilt does not shrink as more of the same people respond; it is a property of who was reached, not of how many. Option 2 treats the problem as one of size; sample size governs random error, and even 100 well-chosen respondents would be more informative than 3,400 self-selected ones. Option 3 computes the margin of error correctly for a random sample and then applies it to a sample that is not random, which is the mistake the 1936 Literary Digest poll made with 2.4 million replies. Option 4 diagnoses a real but secondary issue (the frame) and offers a fix that would introduce its own frame problems; the self-selection is the larger flaw.",
    method: "Ask who was in the frame and who chose to answer before asking how many answered. Bias does not shrink with n.",
    hints: ["Who sees the council's cycling page, and who among them bothers to answer?", "Would 34,000 responses gathered the same way fix the problem?", "Separate random error (which n controls) from systematic bias (which it does not)."],
    commonErrors: [
      { description: "Treated a biased sample as a problem of size.", category: "STATISTICAL_ERROR", optionIndex: 1 },
      { description: "Applied a random-sampling margin of error to a self-selected sample.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Focused on the survey mode and missed the self-selection.", category: "ASSUMPTION", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["sampling", "bias"],
    origin: "seeded",
  },
  {
    id: "it-statistics-06",
    skill: "statistics",
    subskill: "bias_vs_variance",
    concepts: ["sampling-and-bias", "sampling-variability"],
    level: "intermediate",
    difficulty: 3,
    format: "multi_select",
    prompt: "A survey of household spending is being planned. Which of the following changes would reduce systematic bias in the estimate, as opposed to merely reducing random sampling error? Select all that apply.",
    options: [
      "Drawing households at random from a complete address register rather than from a panel of volunteers.",
      "Doubling the number of households surveyed.",
      "Visiting non-responding households a second and third time to raise the response rate.",
      "Weighting responses so that the age and region mix matches the census.",
      "Recruiting a much larger online panel of volunteers.",
    ],
    answer: [0, 2, 3],
    solution:
      "Bias is a gap between the people reached and the people meant to be described; random error is the sample-to-sample wobble around whatever the sample is estimating. A random draw from a complete register (option 1) fixes the frame so that every household has a known chance of selection. Chasing non-responders (option 3) narrows the gap between those who answered and those who were asked, which matters because non-responders differ systematically from responders in income, time and trust. Weighting to the census (option 4) corrects imbalance on the dimensions weighted, which removes part of the bias, though not any bias on dimensions that were not weighted. Doubling n (option 2) halves nothing about bias; it shrinks the standard error by a factor of √2. A larger volunteer panel (option 5) is a larger biased sample, which estimates the wrong number more precisely.",
    method: "For each change, ask whether it alters who is reached (bias) or only how many are reached (variance).",
    hints: ["Which changes alter who ends up in the sample, rather than how many?", "Doubling n reduces which kind of error?", "Three of the five reduce bias."],
    commonErrors: [
      { description: "Selected doubling the sample size as a bias reduction.", category: "STATISTICAL_ERROR", optionIndex: 1 },
      { description: "Selected a larger volunteer panel, confusing size with representativeness.", category: "STATISTICAL_ERROR", optionIndex: 4 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["sampling", "bias"],
    origin: "seeded",
  },
  {
    id: "it-statistics-07",
    skill: "statistics",
    subskill: "standard_error",
    concepts: ["sampling-variability", "variance-and-spread"],
    level: "foundation",
    difficulty: 2,
    format: "numeric",
    prompt: "A random sample of 64 customers has a mean spend of £38 with a sample standard deviation of £12. What is the standard error of the mean? Give the answer in pounds.",
    answer: 1.5,
    tolerance: 0.01,
    unit: "£",
    solution:
      "SE = s/√n = 12/√64 = 12/8 = 1.5. The standard deviation, £12, describes how much individual customers vary; the standard error, £1.50, describes how much the sample mean would vary from one random sample of 64 to another. The square root is the whole story of why precision is expensive: 64 customers have shrunk the noise by a factor of 8, not 64, and getting to £0.75 would take 256 customers. The mean of £38 is not needed for the calculation, which is a reminder that the standard error depends on the spread of the data and the sample size, not on the estimate's value.",
    method: "Divide the sample standard deviation by the square root of the sample size.",
    hints: ["The formula has a square root in it. Of what?", "√64 = 8.", "12 divided by 8."],
    commonErrors: [
      { description: "Divided by n instead of √n.", category: "CONCEPTUAL_ERROR", value: 0.1875 },
      { description: "Reported the standard deviation, which describes the data rather than the estimate.", category: "CONCEPTUAL_ERROR", value: 12 },
      { description: "Multiplied by √n instead of dividing.", category: "ALGEBRA_ERROR", value: 96 },
      { description: "Divided the mean rather than the standard deviation by √n.", category: "MISREAD", value: 4.75 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["standard-error"],
    origin: "seeded",
  },
  {
    id: "it-statistics-08",
    skill: "statistics",
    subskill: "standard_error_scaling",
    concepts: ["sampling-variability", "law-of-large-numbers"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A poll of 200 people gives a standard error of 3.5 percentage points. Keeping everything else the same, how many people must be polled to halve the standard error?",
    answer: 800,
    tolerance: 0,
    solution:
      "The standard error falls with the square root of the sample size. To halve it, √n must double, so n must quadruple: 4 × 200 = 800. Check: 3.5 × √(200/800) = 3.5 × 0.5 = 1.75. The same rule read the other way explains why the last decimal place of precision is so expensive: cutting the standard error to a tenth needs a hundred times the sample. Doubling to 400 would give 3.5/√2 ≈ 2.47 points, a reduction of about 30 %, not 50 %.",
    method: "SE ∝ 1/√n, so scale n by the square of the factor you want the SE to shrink by.",
    hints: ["SE is proportional to 1/√n, not 1/n.", "If √n must double, what must n do?", "Quadruple the sample."],
    commonErrors: [
      { description: "Doubled the sample, treating SE as proportional to 1/n.", category: "CONCEPTUAL_ERROR", value: 400 },
      { description: "Halved the sample, reading the question backwards.", category: "MISREAD", value: 100 },
      { description: "Squared n instead of multiplying it by four.", category: "ALGEBRA_ERROR", value: 40000 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: false,
    tags: ["standard-error"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Confidence intervals                                               */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-09",
    skill: "statistics",
    subskill: "confidence_interval_calculation",
    concepts: ["confidence-intervals", "sampling-variability"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A random sample of 36 batteries has a mean life of 52.4 hours with a sample standard deviation of 9 hours. Using the multiplier 1.96, what is the upper limit of the 95 % confidence interval for the mean life? Give two decimal places.",
    answer: 55.34,
    tolerance: 0.05,
    unit: "hours",
    solution:
      "First the standard error: SE = s/√n = 9/√36 = 9/6 = 1.5 hours. Then the half-width: 1.96 × 1.5 = 2.94 hours. Upper limit = 52.4 + 2.94 = 55.34 hours; the lower limit is 49.46. The interval is a statement about the population mean, not about individual batteries: it says the data are compatible with a mean life between about 49.5 and 55.3 hours. Individual batteries range far more widely, which is what the standard deviation of 9 hours describes. With only 36 observations the exact multiplier from the t distribution is 2.03 rather than 1.96, which would widen the interval slightly (to 55.45); the prompt fixes 1.96 to keep the answer unambiguous.",
    method: "SE = s/√n; half-width = multiplier × SE; add to the mean.",
    hints: ["The interval is mean ± 1.96 × SE. First find SE.", "SE = 9/6 = 1.5. Multiply by 1.96.", "Add 2.94 to 52.4."],
    commonErrors: [
      { description: "Used the standard deviation instead of the standard error, giving an interval about individual batteries rather than the mean.", category: "CONCEPTUAL_ERROR", value: 70.04 },
      { description: "Used ± 1 SE rather than ± 1.96 SE.", category: "CONCEPTUAL_ERROR", value: 53.9 },
      { description: "Reported the lower limit.", category: "MISREAD", value: 49.46 },
      { description: "Used the one-sided multiplier 1.645.", category: "PRECISION_ERROR", value: 54.87 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["confidence-interval"],
    origin: "seeded",
  },
  {
    id: "it-statistics-10",
    skill: "statistics",
    subskill: "confidence_interval_interpretation",
    concepts: ["confidence-intervals"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A random poll of 1,000 voters reports 51 % support for a proposal with a 95 % confidence interval of 48 % to 54 %. Which statement is correct?",
    options: [
      "There is a 95 % probability that true support lies between 48 % and 54 %.",
      "If the poll were repeated many times, about 95 % of the intervals built this way would contain the true level of support; this particular interval either does or does not.",
      "95 % of voters have a level of support between 48 % and 54 %.",
      "A second poll of 1,000 voters would have a 95 % chance of giving a result between 48 % and 54 %.",
    ],
    answer: 1,
    solution:
      "The 95 % attaches to the method, not to the interval in hand. The procedure 'estimate ± 1.96 SE' captures the true value in 95 % of samples; once a sample is drawn, the true support is a fixed number and the interval either contains it or does not. Option 1 is the sentence everyone wants to say, and it is the Bayesian credible interval's sentence, which requires a prior; under the frequentist construction it is not licensed, though the interval remains the range of values the data are compatible with. Option 3 confuses a statement about a population parameter with a statement about individuals. Option 4 is closer to a prediction interval, and it is wrong even as that: a second sample's estimate varies around the true value, not around this sample's estimate, so its chance of landing inside this interval is lower than 95 % (about 83 % for a repeat of the same size, though that figure is not needed to reject the option).",
    method: "Ask what the 95 % is a property of: repeated application of the method. Distinguish parameter, individuals and future samples.",
    hints: ["Is the true level of support a random quantity, or a fixed one we do not know?", "What does 'confidence' describe: this interval, or the procedure that produced it?", "Which option talks about repeated sampling?"],
    commonErrors: [
      { description: "Attached the 95 % probability to this interval rather than to the procedure.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Read an interval for a parameter as a statement about individuals.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Read the interval as a prediction for the next sample.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["confidence-interval", "interpretation"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Tests and p-values                                                 */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-11",
    skill: "statistics",
    subskill: "p_value_interpretation",
    concepts: ["p-values-and-significance", "hypothesis-testing", "conditional-probability"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A randomised trial compares a new drug with placebo and reports p = 0.03 for the difference in recovery rates. Which statement is a correct reading of that p-value?",
    options: [
      "There is a 3 % probability that the drug has no effect.",
      "There is a 3 % probability that the observed difference arose by chance.",
      "If the drug had no effect, a difference at least as large as the one observed would occur in about 3 % of trials like this one.",
      "The result would replicate in about 97 % of repeat trials.",
      "The drug's effect is large enough to be clinically important.",
    ],
    answer: 2,
    solution:
      "A p-value is P(data at least this extreme | null hypothesis true). The conditioning runs from hypothesis to data. Option 3 states exactly that. Option 1 reverses the conditioning to P(null | data), which requires a prior and Bayes' theorem; it is the same error as reading P(positive test | ill) as P(ill | positive test). Option 2 is the most common misreading in print: under the null everything is chance, so 'the probability the result is due to chance' is not a quantity the test computes. Option 4 confuses significance with replication probability; the chance of a replication reaching p < 0.05 depends on the true effect size and the power of the replication, and for a study that just scraped under 0.05 it is often closer to 50 %. Option 5 confuses significance with size: a large trial makes trivial differences significant.",
    method: "Write the p-value as a conditional probability with the null on the right of the bar, then reject every option that puts it on the left or that talks about size or replication.",
    hints: ["Which side of the conditioning bar is the null hypothesis on?", "'Probability the null is true' and 'probability of data this extreme if the null were true' are different quantities. Which does a test compute?", "Only one option keeps the null as the assumption rather than the conclusion."],
    commonErrors: [
      { description: "Read p as the probability that the null hypothesis is true (inverse conditional).", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Read p as the probability that the result is due to chance.", category: "STATISTICAL_ERROR", optionIndex: 1 },
      { description: "Read 1 − p as the probability of replication.", category: "STATISTICAL_ERROR", optionIndex: 3 },
      { description: "Confused statistical significance with the size of the effect.", category: "CONCEPTUAL_ERROR", optionIndex: 4 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["p-value", "interpretation"],
    origin: "seeded",
  },
  {
    id: "it-statistics-12",
    skill: "statistics",
    subskill: "non_significant_results",
    concepts: ["hypothesis-testing", "statistical-power"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A pilot study with 10 patients per group finds that a new treatment's recovery rate is not significantly different from the standard treatment (p = 0.40). Which conclusion is justified?",
    options: [
      "The new treatment has no effect beyond the standard one.",
      "The study could not distinguish the effect from zero; with 10 per group it had little chance of doing so even if a useful effect exists.",
      "There is a 40 % probability that the two treatments are equivalent.",
      "The new treatment is probably worse, since it failed to show a benefit.",
    ],
    answer: 1,
    solution:
      "Failing to reject the null means the data did not distinguish the effect from zero at the chosen level. It does not mean the effect is zero. With ten patients per group, a difference in recovery rates of 20 percentage points would be found significant only a small fraction of the time; a null result is what such a study produces whether or not the treatment works, so it carries little information either way. Option 1 treats absence of evidence as evidence of absence. Option 3 reads the p-value as a probability about the hypothesis. Option 4 draws a direction from a result that could not establish one. The right response is to report the estimated difference with its wide confidence interval and, if the question matters, run a study large enough to answer it.",
    method: "Ask what the study could have detected before asking what it found. A non-significant result from a low-powered study is close to uninformative.",
    hints: ["What is the difference between 'no significant effect' and 'no effect'?", "How likely was a study this small to detect a real, moderate effect?", "Which option describes what the study could and could not do?"],
    commonErrors: [
      { description: "Treated absence of evidence as evidence of absence.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Read the p-value as a probability about the hypothesis.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Inferred a direction from a result that established none.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["hypothesis-testing", "power"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Effect sizes and power                                             */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-13",
    skill: "statistics",
    subskill: "cohens_d",
    concepts: ["effect-sizes", "descriptive-statistics"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "Students taught with method A score a mean of 78 on a test; students taught with method B score a mean of 72. The pooled standard deviation is 12. What is Cohen's d for the difference?",
    answer: 0.5,
    tolerance: 0.01,
    solution:
      "Cohen's d = (mean A − mean B)/pooled SD = (78 − 72)/12 = 6/12 = 0.5. The groups differ by half a standard deviation, a 'medium' effect by Cohen's rough benchmarks (0.2, 0.5, 0.8), which he offered as conventions rather than as rules. What d adds to the raw difference of 6 points is comparability: a 6-point gap on a test where scores spread by 12 is a different thing from a 6-point gap where they spread by 3, and d puts both on one scale. It does not say whether the gain matters; that depends on what the test measures and what the methods cost.",
    method: "Difference in means divided by the pooled standard deviation.",
    hints: ["d expresses the difference in standard-deviation units.", "Difference in means is 6. Divide by what?", "6/12."],
    commonErrors: [
      { description: "Reported the raw difference in means without standardising.", category: "CONCEPTUAL_ERROR", value: 6 },
      { description: "Divided by the variance (144) rather than the standard deviation.", category: "ALGEBRA_ERROR", value: 0.042 },
      { description: "Divided the difference by a group mean, producing a percentage change rather than d.", category: "CONCEPTUAL_ERROR", value: 0.083 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["effect-size"],
    origin: "seeded",
  },
  {
    id: "it-statistics-14",
    skill: "statistics",
    subskill: "absolute_vs_relative_risk",
    concepts: ["effect-sizes", "fractions-ratios-percentages", "base-rates"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A drug reduces the five-year risk of a stroke from 4 % to 3 %. The manufacturer's release describes this as a 25 % reduction in risk. How many people must take the drug for five years for one stroke to be prevented (the number needed to treat)?",
    answer: 100,
    tolerance: 0,
    solution:
      "The absolute risk reduction is 4 % − 3 % = 1 percentage point, or 0.01. The number needed to treat is 1/0.01 = 100: treat a hundred people for five years and, on average, one stroke is prevented; the other 99 get the side effects and the bill without a change in outcome. The 25 % figure is the relative reduction, (4 − 3)/4, and it is not wrong; it is simply the number that makes the drug look best, because it hides the base rate. The same relative reduction applied to a risk of 40 % would prevent ten strokes per hundred, and the decision would be very different. Always ask for the absolute figures.",
    method: "Absolute risk reduction = difference in risks; NNT = 1/ARR.",
    hints: ["Start from the two absolute risks, not from the 25 %.", "What is the difference between 4 % and 3 %, as a fraction?", "NNT = 1 divided by that fraction."],
    commonErrors: [
      { description: "Took the reciprocal of the relative reduction (1/0.25).", category: "CONCEPTUAL_ERROR", value: 4 },
      { description: "Reported the relative risk reduction as the answer.", category: "MISREAD", value: 25 },
      { description: "Reported the absolute risk reduction in percentage points rather than the number needed to treat.", category: "MISREAD", value: 1 },
      { description: "Used the treated risk alone (1/0.03).", category: "CONCEPTUAL_ERROR", value: 33 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["effect-size", "risk"],
    origin: "seeded",
  },
  {
    id: "it-statistics-15",
    skill: "statistics",
    subskill: "power_determinants",
    concepts: ["statistical-power", "hypothesis-testing"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A team is planning a study and wants to raise its power to detect a real effect. Which of the following changes would reduce power rather than increase it?",
    options: [
      "Increasing the sample size from 100 to 400.",
      "Tightening the significance level from α = 0.05 to α = 0.01.",
      "Improving the measurement instrument so that outcome scores are less noisy.",
      "Studying a dose of the treatment that produces a larger true effect.",
    ],
    answer: 1,
    solution:
      "Power is the probability of rejecting the null when the effect of the stated size is real. It rises with sample size, with the true effect size and with less noise in the outcome, because all three make the observed difference stand further from zero relative to its standard error. It rises with α too: a looser threshold is easier to cross. Tightening α from 0.05 to 0.01 therefore lowers power, other things equal; that is the price of fewer false positives. Every design faces this trade, and the way to get both a low false-positive rate and high power is the first option: more data.",
    method: "List the four determinants of power (n, effect size, noise, α) and the direction each works in.",
    hints: ["Which of the four changes makes the threshold for 'significant' harder to reach?", "A lower α means fewer false positives. What does it cost?", "Three options raise power; one lowers it."],
    commonErrors: [
      { description: "Thought that a bigger sample could lower power.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Did not connect measurement noise to power.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Did not connect the true effect size to power.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["power"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Regression                                                         */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-16",
    skill: "statistics",
    subskill: "regression_reading",
    concepts: ["regression", "correlation-vs-causation"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "A regression of annual salary (in £) on years of experience, fitted to 400 employees of one firm, gives: salary = 21,000 + 850 × experience, with a standard error of 110 on the slope and R² = 0.30. Which reading is correct?",
    options: [
      "Among these employees, each additional year of experience is associated with about £850 more salary on average; the slope is estimated precisely (about eight standard errors from zero).",
      "Since R² is only 0.30, the slope is unreliable and experience has little to do with salary.",
      "Gaining a year of experience causes an employee's salary to rise by £850.",
      "The model mispredicts 70 % of employees' salaries.",
    ],
    answer: 0,
    solution:
      "The slope says how predicted salary changes per year of experience among these employees: £850 per year. Its standard error of 110 puts it about 7.7 standard errors from zero, so the estimate is precise. R² = 0.30 says that 30 % of the variance in salary is accounted for by the fitted line, and 70 % by everything else (role, performance, negotiation, luck). A low R² and a precise slope are entirely compatible: experience matters, and so do many other things. Option 2 confuses how much variance a predictor explains with how well its coefficient is estimated. Option 3 reads an association as a cause; people with more experience may differ in seniority, role or the cohort they were hired in, and the model holds none of that fixed. Option 4 misreads R² as a share of cases; it is a share of variance, and every prediction has some error.",
    method: "Read the slope with its units and standard error, then R² as a share of variance, then ask what the design permits about causation.",
    hints: ["What are the units of the slope? Per what?", "How many standard errors from zero is 850?", "R² is a share of variance, not of people, and not a measure of the slope's reliability."],
    commonErrors: [
      { description: "Confused a low R² with an imprecise or unimportant slope.", category: "STATISTICAL_ERROR", optionIndex: 1 },
      { description: "Read an observational regression coefficient as a causal effect.", category: "CAUSAL_ERROR", optionIndex: 2 },
      { description: "Read R² as the proportion of cases predicted correctly.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["regression"],
    origin: "seeded",
  },
  {
    id: "it-statistics-17",
    skill: "statistics",
    subskill: "regression_prediction",
    concepts: ["regression", "linear-equations"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "Using the fitted line salary = 21,000 + 850 × experience (in years), how much higher is the predicted salary of an employee with 15 years of experience than one with 5 years? Answer in pounds.",
    answer: 8500,
    tolerance: 1,
    unit: "£",
    solution:
      "The difference between two predictions from a straight line is the slope times the difference in x: 850 × (15 − 5) = 850 × 10 = £8,500. The intercept cancels, which is worth noticing: for questions about differences, the intercept never matters. Computing both predictions explicitly gives the same thing: 21,000 + 850 × 15 = 33,750 and 21,000 + 850 × 5 = 25,250, whose difference is 8,500. The prediction is an average for employees at those experience levels in the data the line was fitted to; an individual's salary will differ, and extrapolating to 40 years of experience, if nobody in the data has it, would be a guess wearing the line's clothes.",
    method: "Difference in predictions = slope × difference in x; the intercept cancels.",
    hints: ["The predicted difference depends on the slope and the gap in experience.", "The gap is 10 years.", "850 × 10."],
    commonErrors: [
      { description: "Reported the prediction at 15 years rather than the difference.", category: "MISREAD", value: 33750 },
      { description: "Reported the slope, ignoring the ten-year gap.", category: "MISREAD", value: 850 },
      { description: "Added the intercept to the difference.", category: "ALGEBRA_ERROR", value: 29500 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: false,
    tags: ["regression"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Multiple comparisons                                               */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-18",
    skill: "statistics",
    subskill: "multiple_comparisons",
    concepts: ["multiple-comparisons", "probability-rules", "independence"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "A marketing team tests twelve different versions of a web page against the current one, each with its own independent test at α = 0.05. Suppose none of the twelve versions is actually any better. What is the probability that at least one is declared significantly better? Give a decimal.",
    answer: 0.46,
    tolerance: 0.01,
    solution:
      "Each test, with a true null, has a 0.05 chance of a false positive and a 0.95 chance of a correct non-rejection. With twelve independent tests, P(no false positives) = 0.95^12 ≈ 0.540, so P(at least one) = 1 − 0.540 ≈ 0.46. Nearly even odds of a 'winner' that is nothing of the kind. The tempting shortcut 12 × 0.05 = 0.60 over-counts, because the false positives can overlap; it is the same error as adding probabilities of non-exclusive events. The fix is either to lower the per-test threshold (Bonferroni: 0.05/12 ≈ 0.004) or to confirm the winning version in a fresh test before acting on it.",
    method: "Complement of 'all twelve tests correctly fail to reject': 1 − (1 − α)^m.",
    hints: ["Find the probability that none of the twelve tests gives a false positive first.", "Each test has a 0.95 chance of not rejecting; the tests are independent.", "1 − 0.95^12."],
    commonErrors: [
      { description: "Multiplied 12 × 0.05, adding probabilities of overlapping events.", category: "CONCEPTUAL_ERROR", value: 0.6 },
      { description: "Ignored the multiplicity and answered with the single-test rate.", category: "STATISTICAL_ERROR", value: 0.05 },
      { description: "Reported the probability of no false positives rather than at least one.", category: "MISREAD", value: 0.54 },
    ],
    transfer: 1,
    minutes: 3,
    examEligible: true,
    tags: ["multiple-comparisons", "a-b-testing"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Reading research                                                   */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-19",
    skill: "statistics",
    subskill: "regression_to_the_mean",
    concepts: ["regression-to-the-mean", "counterfactuals"],
    level: "transfer",
    difficulty: 3,
    format: "mcq",
    prompt: "A company sends its twenty worst-performing sales staff of the quarter on a training course. In the following quarter their average sales rise by 15 %. The training manager presents this as proof that the course works. What is the strongest objection, and what would answer it?",
    options: [
      "The twenty were chosen because their quarter was extreme, and part of an extreme quarter is bad luck that does not repeat; they would be expected to improve without any course. A comparison group of similarly poor performers who were not trained would show how much of the 15 % the course earned.",
      "Sales staff cannot be trained; the rise is entirely due to the general market improving that quarter.",
      "The sample of twenty is too small to show anything; the course must be given to at least a hundred people before its effect can be assessed.",
      "The improvement shows that training the bottom performers is the best use of the budget and should be extended to the top performers as well.",
    ],
    answer: 0,
    solution:
      "Any quarter's sales figure mixes a stable component (skill, territory) with noise (which clients happened to close). Selecting the twenty lowest figures selects, on average, people whose noise was unusually negative that quarter. Noise does not persist, so their next quarter is expected to sit closer to their normal level whether or not anything was done in between. Regression to the mean therefore predicts an improvement, and the course gets the credit. The only clean answer is a comparison group selected by the same rule but not trained: the difference between the trained and untrained bottom performers is the course's effect. Option 2 asserts a different cause with no more evidence than the manager had. Option 3 is not the objection; sample size governs precision, and twenty is enough to see a large effect if the comparison were valid. Option 4 accepts the flawed inference and builds on it.",
    method: "When an intervention follows selection on an extreme value, expect movement toward the mean regardless; demand a control group selected the same way.",
    hints: ["Why were these twenty chosen? What does being chosen for a very low figure tell you about their luck that quarter?", "If nothing had been done, would you expect the twenty to have the same average next quarter, or a better one?", "What comparison would separate the course's effect from the expected rebound?"],
    commonErrors: [
      { description: "Replaced one unsupported causal story with another.", category: "CAUSAL_ERROR", optionIndex: 1 },
      { description: "Treated a selection problem as a sample-size problem.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Accepted the before-after comparison as proof and generalised from it.", category: "CAUSAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 4,
    examEligible: true,
    tags: ["regression-to-the-mean", "evaluation"],
    origin: "seeded",
  },
  {
    id: "it-statistics-20",
    skill: "statistics",
    subskill: "simpsons_paradox",
    concepts: ["simpsons-paradox", "confounding", "conditional-probability"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt:
      "Two hospitals report surgical deaths over a year, split by the patient's risk category on admission.\n\nHospital A: low-risk 100 patients, 1 death; high-risk 900 patients, 90 deaths.\nHospital B: low-risk 900 patients, 18 deaths; high-risk 100 patients, 15 deaths.\n\nA regulator ranks hospitals by overall death rate. Compute the rates and choose the correct reading.",
    options: [
      "Hospital B is safer: its overall death rate is 3.3 % against A's 9.1 %.",
      "Hospital A is safer for every kind of patient (1 % v 2 % among low-risk, 10 % v 15 % among high-risk); its overall rate is higher only because nine-tenths of its patients are high-risk. The overall figure compares case mixes, not care.",
      "The figures are contradictory and one of the hospitals must have reported them wrongly.",
      "Hospital A is safer for high-risk patients and Hospital B for low-risk patients, so each patient should choose by category.",
    ],
    answer: 1,
    solution:
      "Overall rates: A has 91 deaths in 1,000 patients, 9.1 %; B has 33 in 1,000, 3.3 %. Within categories: low-risk, A 1/100 = 1 % against B 18/900 = 2 %; high-risk, A 90/900 = 10 % against B 15/100 = 15 %. A is better in both strata and worse overall. There is no contradiction: an overall rate is a weighted average of the stratum rates, and A's weights are 10 % low-risk, 90 % high-risk, while B's are the reverse. A takes the hard cases, as specialist centres do, and the pooled figure penalises it for that. Risk category is decided before treatment and affects both which hospital a patient reaches and how likely they are to die, which is exactly the structure that makes the stratified comparison the right one and the pooled one misleading. Option 4 misreads the table: A is better in both categories. Option 3 mistakes a weighted-average effect for an error.",
    method: "Compute the pooled rates and the stratum rates; when they disagree, find the variable that decides both group membership and outcome, and stratify on it if it precedes treatment.",
    hints: ["Work out all six rates: two overall, four within category.", "What share of each hospital's patients are high-risk?", "An overall rate is a weighted average of the category rates. What are the weights?"],
    commonErrors: [
      { description: "Trusted the pooled rate without checking the case mix.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Treated a weighted-average reversal as a data error.", category: "CONCEPTUAL_ERROR", optionIndex: 2 },
      { description: "Misread the within-category comparison.", category: "MISREAD", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 5,
    examEligible: true,
    tags: ["simpsons-paradox", "table"],
    origin: "seeded",
  },
  {
    id: "it-statistics-21",
    skill: "statistics",
    subskill: "reading_a_study",
    concepts: ["interpreting-research", "experiments-vs-observational", "effect-sizes", "confidence-intervals", "confounding"],
    level: "synthesis",
    difficulty: 5,
    format: "free",
    prompt:
      "A press release reads: 'New study: coffee drinkers live longer. Researchers followed 500,000 adults for ten years. Those who drank three or more cups a day had 12 % lower mortality than non-drinkers (hazard ratio 0.88, 95 % CI 0.84 to 0.92). The study was funded by a national coffee association.'\n\nIn 150 to 250 words, assess what this study can and cannot support. Name the design, say what the numbers mean in absolute terms as far as you can, identify the main threats to a causal reading, and state what further evidence would change your view.",
    keyPoints: [
      "observational|cohort|not randomised|not randomized|did not assign|self-selected|chose to drink",
      "confound|healthier|smok|income|wealth|lifestyle|education|reverse caus|already ill|stopped drinking",
      "relative|absolute|hazard ratio|base rate|percentage point|how many deaths|12 % of what",
      "interval|0.84|0.92|precise|narrow|large sample|sampling error only",
      "fund|sponsor|conflict of interest|coffee association",
      "cannot conclude|cannot support|does not show|causal|cause|association",
      "randomis|randomiz|trial|natural experiment|mendelian|adjust|control for|replicat|meta-analys|dose",
    ],
    rubric: [
      { criterion: "Identifies the design as observational (cohort) and explains why that limits causal claims", weight: 0.25, description: "Names the design; explains that participants chose their own coffee intake and that whatever drives that choice may drive mortality." },
      { criterion: "Translates the relative figure and reads the interval correctly", weight: 0.2, description: "Explains that 12 % is relative; notes that the absolute difference depends on the base mortality rate, which is not given; reads the narrow interval as precision of the estimate, not as freedom from bias." },
      { criterion: "Names specific confounders or reverse causality", weight: 0.25, description: "At least two concrete alternatives: smoking, income, health status, people who are ill giving up coffee, and so on." },
      { criterion: "Weighs the funding source proportionately", weight: 0.1, description: "Treats sponsorship as a reason for scrutiny of choices made in analysis and reporting, not as a refutation." },
      { criterion: "States what evidence would change the assessment", weight: 0.2, description: "Adjusted analyses, dose-response, replication across cohorts, a natural experiment or genetic instrument, or a trial." },
    ],
    solution:
      "Design: a prospective cohort, observational. Participants chose how much coffee to drink; nobody assigned it. So the comparison is between kinds of people as much as between drinks, and whatever leads someone to drink three cups a day (income, employment, sociability, not being ill) may also lower their mortality. Reverse causality is live: people who become seriously ill often cut caffeine, which would make non-drinkers look sicker. Numbers: a hazard ratio of 0.88 is a 12 % relative reduction in the death rate; without the base rate one cannot say what that is in absolute terms, and for ten-year mortality in a mostly middle-aged cohort it might be a couple of percentage points. The interval 0.84 to 0.92 is narrow because n is huge; that is precision about the association, and says nothing about bias. Funding: a reason to check whether outcomes, cut-points and adjustments were chosen after the data were seen, not a reason to dismiss the result. What would move the assessment: analyses adjusted for smoking and health status that leave the effect intact; a dose-response gradient; replication in cohorts with different confounding structures; a Mendelian randomisation study using caffeine-metabolism genes; and, though unlikely to be run, a trial. As it stands, the study supports 'coffee drinking is associated with lower mortality in this cohort' and does not support 'coffee makes you live longer'.",
    method: "Design, sample, estimate with interval, absolute translation, comparisons and flexibility, funding, then what would change your mind; write the conclusion the design permits and no stronger.",
    hints: ["Who decided who drank coffee: the researchers or the participants?", "What kind of people drink three cups a day, and what kind of people stop?", "Is 12 % a relative or an absolute figure, and what does the narrow interval actually tell you?"],
    commonErrors: [
      { description: "Concluded that coffee causes longer life from an observational association.", category: "CAUSAL_ERROR", pattern: "coffee causes|proves that coffee|coffee makes you live" },
      { description: "Dismissed the study entirely because of its funding.", category: "EVIDENCE_ERROR", pattern: "worthless|cannot be trusted at all|ignore the study" },
      { description: "Treated the narrow interval as evidence against confounding.", category: "STATISTICAL_ERROR", pattern: "narrow interval shows|precise so it must be|large sample rules out" },
    ],
    transfer: 2,
    minutes: 12,
    examEligible: true,
    tags: ["reading-research", "free-response"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Charts and design                                                  */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-22",
    skill: "statistics",
    subskill: "chart_reading",
    concepts: ["visualising-data", "descriptive-statistics"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "A slide shows a bar chart of customer satisfaction: 'Before: 42 %. After: 45 %.' The vertical axis runs from 40 % to 46 %, so the second bar is two and a half times the height of the first. What is the honest description of what the data show, and what is wrong with the chart?",
    options: [
      "Satisfaction rose by 3 percentage points, about 7 % in relative terms; the truncated axis makes a modest change look like a large one, because bars encode value as length from a baseline.",
      "Satisfaction more than doubled, as the bars show; the axis choice is a matter of taste.",
      "Satisfaction rose by 3 %, and the chart is fine because the numbers are printed on it.",
      "The chart is misleading because bar charts should never be used for percentages.",
    ],
    answer: 0,
    solution:
      "The change is from 42 % to 45 %: 3 percentage points, or 3/42 ≈ 7 % relative. A bar's message is its length from the baseline, so when the baseline is 40 rather than 0, the lengths are 2 and 5 instead of 42 and 45 and the visual ratio becomes 2.5 to 1. The eye reads the ratio before the labels, which is why printing the numbers does not repair the chart. A line chart with a labelled window may legitimately zoom in on a change, because a line encodes position rather than length; a bar chart may not. Option 2 accepts the visual lie. Option 3 confuses percentage points with per cent and excuses the design. Option 4 is a rule that does not exist.",
    method: "Read the numbers, compute both the absolute and the relative change, then ask what the chart's encoding (length from a baseline) implies about where the axis must start.",
    hints: ["What are the actual numbers, and what is the difference in percentage points?", "What does the length of a bar represent, and from where is it measured?", "Would the same axis be acceptable on a line chart?"],
    commonErrors: [
      { description: "Read the visual ratio of the bars as the change in the data.", category: "MISREAD", optionIndex: 1 },
      { description: "Confused percentage points with per cent and dismissed the axis problem.", category: "PRECISION_ERROR", optionIndex: 2 },
      { description: "Invented a rule against bar charts for percentages.", category: "KNOWLEDGE_GAP", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 2,
    examEligible: true,
    tags: ["charts"],
    origin: "seeded",
  },
  {
    id: "it-statistics-23",
    skill: "statistics",
    subskill: "study_design",
    concepts: ["experiments-vs-observational", "randomised-experiments"],
    level: "basic",
    difficulty: 2,
    format: "mcq",
    prompt: "Which of these studies is an experiment?",
    options: [
      "A school lets parents choose whether their child joins a new reading programme, then compares the reading scores of joiners and non-joiners.",
      "A school assigns pupils to the new reading programme or the existing one by coin toss, then compares reading scores.",
      "A school introduces the programme for every pupil and compares this year's reading scores with last year's.",
      "A researcher surveys 2,000 schools and finds that those using the programme have higher scores.",
    ],
    answer: 1,
    solution:
      "An experiment is defined by one feature: the investigator assigns the treatment, ideally at random. Only option 2 does that. Because the coin toss is unrelated to anything about the pupil, the two groups are alike in expectation on every characteristic, measured or not, and a difference in scores can be attributed to the programme. Option 1 lets parents assign, and the parents who opt in differ from those who do not. Option 3 compares two cohorts across time, with no control for everything else that changed between years. Option 4 is a cross-sectional survey in which schools chose whether to adopt, and the adopters differ from the rest in resources and ambition. All three are observational, and each can be useful; none can support the causal claim as cleanly.",
    method: "Ask who assigned the treatment. If the investigator did, and at random, it is a randomised experiment; if the participants, the institutions or time did, it is observational.",
    hints: ["The defining feature of an experiment is who assigns the treatment.", "In which option did something other than the participants' or schools' own choice decide who got the programme?", "A coin toss is unrelated to anything about the pupil. Why does that matter?"],
    commonErrors: [
      { description: "Treated a self-selected comparison as an experiment because two groups were compared.", category: "CAUSAL_ERROR", optionIndex: 0 },
      { description: "Treated a before-after comparison as an experiment because something was changed.", category: "CAUSAL_ERROR", optionIndex: 2 },
      { description: "Treated a large survey as an experiment because of its size.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 0,
    minutes: 2,
    examEligible: true,
    tags: ["design"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Exam-only items: never shown in Train or in lessons                 */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-24",
    skill: "statistics",
    subskill: "standard_error_proportion",
    concepts: ["sampling-variability", "distributions"],
    level: "intermediate",
    difficulty: 3,
    format: "numeric",
    prompt: "In a random sample of 400 voters, 40 % say they will vote for a proposal. What is the standard error of that proportion? Give three decimal places as a decimal (not a percentage).",
    answer: 0.0245,
    tolerance: 0.0006,
    solution:
      "For a proportion, SE = √(p(1 − p)/n) = √(0.4 × 0.6/400) = √(0.24/400) = √0.0006 ≈ 0.0245, or about 2.4 percentage points. The 95 % interval is therefore roughly 40 % ± 4.8 points, from 35 % to 45 %. The factor p(1 − p) is largest at p = 0.5 (0.25), which is why pollsters quote a single margin of error for a whole poll using the worst case: 0.5/√400 = 0.025. Two common slips: forgetting the square root (0.0006 is a variance, and far too small), and dividing p by √n as if it were a standard deviation.",
    method: "SE of a proportion = √(p(1 − p)/n).",
    hints: ["The variance of a single yes/no observation is p(1 − p).", "Divide by n, then take the square root.", "√(0.24/400)."],
    commonErrors: [
      { description: "Forgot the square root and reported the variance of the proportion.", category: "ALGEBRA_ERROR", value: 0.0006 },
      { description: "Divided p by √n, treating the proportion as a standard deviation.", category: "CONCEPTUAL_ERROR", value: 0.02 },
      { description: "Omitted n: reported √(p(1 − p)).", category: "CONCEPTUAL_ERROR", value: 0.49 },
    ],
    transfer: 0,
    minutes: 3,
    examOnly: true,
    tags: ["standard-error", "proportion"],
    origin: "seeded",
  },
  {
    id: "it-statistics-25",
    skill: "statistics",
    subskill: "p_value_interpretation",
    concepts: ["p-values-and-significance", "hypothesis-testing"],
    level: "intermediate",
    difficulty: 3,
    format: "mcq",
    prompt: "An A/B test of two checkout pages reports p = 0.20 for the difference in conversion rates. Which statement is correct?",
    options: [
      "There is a 20 % probability that the two pages convert equally well.",
      "If the two pages converted equally well, a difference at least as large as the observed one would appear in about 20 % of tests of this size.",
      "The observed difference has an 80 % chance of being real.",
      "The pages have been shown to be equivalent.",
    ],
    answer: 1,
    solution:
      "p = P(data at least this extreme | no true difference). Option 2 says that and nothing more. Option 1 inverts the conditioning into a probability about the hypothesis, which a p-value cannot supply without a prior. Option 3 does the same with the complement. Option 4 reads a non-significant result as evidence of equivalence; the test failed to distinguish the difference from zero, which is what a modest test would do whether or not the pages differ. The honest report is the estimated difference with its interval, and a decision about whether the interval is narrow enough to act on.",
    method: "Keep the null on the right of the conditioning bar; reject any option that makes a claim about the probability of the hypothesis or about equivalence.",
    hints: ["What is the p-value conditional on?", "Can a test tell you the probability that a hypothesis is true?", "What does a non-significant result establish?"],
    commonErrors: [
      { description: "Inverted the conditioning: read p as the probability of the null.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Read 1 − p as the probability that the effect is real.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Read a non-significant result as proof of equivalence.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 1,
    minutes: 3,
    examOnly: true,
    tags: ["p-value"],
    origin: "seeded",
  },
  {
    id: "it-statistics-26",
    skill: "statistics",
    subskill: "regression_to_the_mean",
    concepts: ["regression-to-the-mean", "sampling-variability"],
    level: "advanced",
    difficulty: 4,
    format: "mcq",
    prompt: "A magazine profiles the ten investment funds that returned the most last year. This year the same ten funds have, on average, performed close to the market median. Which explanation requires the fewest assumptions?",
    options: [
      "The managers became complacent after the publicity.",
      "The funds were selected for an extreme result that mixed skill with luck; the luck did not repeat, so their returns moved toward the average. No change in the managers is needed to explain it.",
      "Other investors copied their strategies and competed the returns away within a year.",
      "The magazine's profiling caused so much money to flow in that the funds could no longer find good investments.",
    ],
    answer: 1,
    solution:
      "Any year's return mixes persistent ability with chance. Selecting the ten best returns from hundreds of funds selects, on average, unusually lucky years. Next year's luck is independent, so the expected return of the ten is nearer the mean: regression to the mean, with no change in anyone required. Options 1, 3 and 4 may each hold in some cases, but each posits a mechanism for which there is no evidence in the description, and each would have to explain why the pattern appears just as reliably for the ten worst funds, which improve, and for sports teams, students and hospitals. The general explanation that needs no mechanism is the one to prefer until specific evidence arrives.",
    method: "When something is chosen for being extreme and then measured again, expect movement toward the mean before looking for a cause.",
    hints: ["How were the ten funds chosen?", "What does being in the top ten out of hundreds tell you about the role of luck in that year's result?", "Which explanation would also account for the worst ten funds improving?"],
    commonErrors: [
      { description: "Attributed the reversion to a psychological change in the managers.", category: "CAUSAL_ERROR", optionIndex: 0 },
      { description: "Attributed the reversion to competition without evidence.", category: "CAUSAL_ERROR", optionIndex: 2 },
      { description: "Attributed the reversion to fund inflows without evidence.", category: "CAUSAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examOnly: true,
    tags: ["regression-to-the-mean", "finance"],
    origin: "seeded",
  },

  /* ---------------------------------------------------------------- */
  /* Transfer items for lessons                                         */
  /* ---------------------------------------------------------------- */
  {
    id: "it-statistics-27",
    skill: "statistics",
    subskill: "small_sample_extremes",
    concepts: ["sampling-variability", "law-of-large-numbers"],
    level: "transfer",
    difficulty: 3,
    format: "mcq",
    prompt: "A map of kidney-cancer rates by county in the United States shows that the counties with the lowest rates are mostly rural, sparsely populated and in the Midwest and West. A second map shows that the counties with the highest rates are also mostly rural, sparsely populated and in the Midwest and West. What explains both maps at once?",
    options: [
      "Rural life is healthier in some counties and less healthy in others, depending on local water and farming practices.",
      "Small counties have few cases, so their rates are noisy: a county of 2,000 people goes from the lowest rate to the highest on the strength of one or two cases. Both extremes are dominated by small counties because small samples produce extreme statistics.",
      "The data were collected differently in rural areas, producing errors in both directions.",
      "Rural counties are more numerous, so by chance more of them appear at both ends of any ranking.",
    ],
    answer: 1,
    solution:
      "A rate computed from a small population has a large standard error. With an underlying rate of a few cases per 100,000 per year, a county of 2,000 people will usually record zero cases (lowest rate in the country) and occasionally one or two (among the highest). Large urban counties record hundreds of cases and their rates sit close to the national figure. So the tails of any ranking of rates are filled by small units, at both ends, for no reason other than sampling variability; the example is Howard Wainer's, and the same pattern appears in small schools, small hospitals and small funds. Option 1 invents two opposite causes for one statistical fact. Option 3 posits errors with no evidence. Option 4 is about counts, not rates: even if rural counties were more numerous, being numerous would not put them disproportionately at the extremes unless their rates were noisier.",
    method: "When extremes in a ranking are dominated by small units, suspect sampling variability before any substantive cause.",
    hints: ["What do the counties at both extremes have in common?", "How many cases does a county of 2,000 people record in a year, and what does one extra case do to its rate?", "Which explanation accounts for both maps with a single mechanism?"],
    commonErrors: [
      { description: "Invented opposite substantive causes for what is one statistical mechanism.", category: "CAUSAL_ERROR", optionIndex: 0 },
      { description: "Attributed sampling variability to measurement error.", category: "ASSUMPTION", optionIndex: 2 },
      { description: "Confused the number of small units with the variability of their rates.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["small-samples", "variability"],
    origin: "seeded",
  },
  {
    id: "it-statistics-28",
    skill: "statistics",
    subskill: "margin_of_error_difference",
    concepts: ["confidence-intervals", "sampling-variability"],
    level: "transfer",
    difficulty: 4,
    format: "mcq",
    prompt: "A poll of 1,000 voters puts candidate X on 51 % and candidate Y on 47 %, with a reported margin of error of ±3.1 percentage points. A newspaper says X's lead is 'outside the margin of error'. Is that right?",
    options: [
      "Yes: the lead is 4 points and the margin is 3.1 points, so the lead is statistically clear.",
      "No: the ±3.1 applies to each candidate's share separately. The margin on the difference between the two shares is roughly twice as large, about ±6 points, so a 4-point lead is within the noise.",
      "Yes: with 1,000 respondents any lead of more than 1 point is reliable.",
      "It cannot be judged without knowing the size of the electorate.",
    ],
    answer: 1,
    solution:
      "The quoted ±3.1 is the 95 % margin for a single share near 50 % from n = 1,000 (1.96 × 0.5/√1000 ≈ 0.031). The lead is a difference of two shares from the same sample, and when one goes up the other goes down, so the difference is about twice as variable as either share: the margin on X − Y is close to ±6 points (working it out from the two shares gives about ±6.1). A 4-point lead is well inside that. The newspaper's comparison of the lead with the single-share margin is the standard error of reporting on polls. Option 3 substitutes the size of the sample for the calculation. Option 4 is wrong because, for populations far larger than the sample, the margin depends on n and not on the electorate's size.",
    method: "The margin on a difference between two shares from one poll is about double the margin on a single share; compare the lead with that.",
    hints: ["What is the ±3.1 a margin for: one share, or the gap between two?", "If X's share is 3 points too high by chance, what has happened to Y's?", "Roughly double the single-share margin and compare the lead with it."],
    commonErrors: [
      { description: "Compared the lead with the margin for a single share.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Treated a large sample as sufficient without any calculation.", category: "STATISTICAL_ERROR", optionIndex: 2 },
      { description: "Believed the margin depends on the population size.", category: "CONCEPTUAL_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["polls", "confidence-interval"],
    origin: "seeded",
  },
  {
    id: "it-statistics-29",
    skill: "statistics",
    subskill: "z_statistic",
    concepts: ["hypothesis-testing", "sampling-variability", "distributions"],
    level: "basic",
    difficulty: 2,
    format: "numeric",
    prompt: "A factory's bottles are meant to contain 500 ml, with a known standard deviation of 15 ml per bottle. A random sample of 36 bottles has a mean of 503 ml. What is the z statistic for testing whether the process mean is still 500 ml?",
    answer: 1.2,
    tolerance: 0.01,
    solution:
      "The z statistic measures how many standard errors the sample mean sits from the value claimed by the null hypothesis. SE = σ/√n = 15/√36 = 15/6 = 2.5 ml. z = (503 − 500)/2.5 = 1.2. A z of 1.2 corresponds to a two-sided p-value of about 0.23: sample means this far from 500 occur nearly a quarter of the time when the process is on target, so the data give no real reason to suspect drift. Dividing the 3 ml difference by the bottle standard deviation of 15 (giving 0.2) answers a different question, how unusual one bottle would be, which is not what was asked.",
    method: "Standard error first (σ/√n), then z = (sample mean − null value)/SE.",
    hints: ["The test compares the sample mean with 500 in units of the standard error, not the standard deviation.", "SE = 15/√36.", "(503 − 500)/2.5."],
    commonErrors: [
      { description: "Divided by the standard deviation instead of the standard error.", category: "CONCEPTUAL_ERROR", value: 0.2 },
      { description: "Divided by σ/n rather than σ/√n.", category: "ALGEBRA_ERROR", value: 7.2 },
      { description: "Reported the raw difference of 3 ml.", category: "MISREAD", value: 3 },
    ],
    transfer: 0,
    minutes: 3,
    examEligible: true,
    tags: ["z-test"],
    origin: "seeded",
  },
  {
    id: "it-statistics-30",
    skill: "statistics",
    subskill: "reading_a_null_result",
    concepts: ["statistical-power", "confidence-intervals", "effect-sizes"],
    level: "transfer",
    difficulty: 4,
    format: "mcq",
    prompt: "A ministry trials a reading intervention in twelve classes. The evaluation reports an effect of d = 0.15 with a 95 % confidence interval from −0.20 to 0.50 and the headline 'no significant effect'. The ministry cancels the programme. Which assessment is right?",
    options: [
      "The decision is sound: the trial showed the intervention does not work.",
      "The interval runs from a small negative effect to a large positive one; the trial was too small to tell a useful effect from none. 'No significant effect' here means 'no information', and cancelling on that basis mistakes an inconclusive result for a negative one.",
      "The intervention should be adopted, since the point estimate of 0.15 is positive.",
      "The result proves the intervention is harmful, because the interval includes negative values.",
    ],
    answer: 1,
    solution:
      "Read the interval, not the verdict. Effects between −0.2 and 0.5 standard deviations are all compatible with the data, and that range includes effects (0.3, 0.4) that would be among the more valuable in education. The trial's width comes from twelve classes: low power, wide interval, inconclusive. Option 1 turns 'not significant' into 'does not work', the classic misreading of a null result. Option 3 makes the opposite mistake, treating a point estimate as a finding when the interval says the sign is uncertain. Option 4 reads the inclusion of negative values as proof of harm; the interval includes zero and positive values just as much. The defensible decision is to run a larger trial or to decide on other grounds (cost, plausibility, evidence from elsewhere), while saying plainly that this trial did not settle it.",
    method: "Report the estimate and the interval; ask what effect sizes remain plausible; distinguish 'not detected' from 'absent'.",
    hints: ["What effect sizes does the interval leave open?", "Is a d of 0.4 excluded by the data?", "What does a wide interval tell you about the trial rather than the intervention?"],
    commonErrors: [
      { description: "Read a non-significant result as evidence that the intervention does not work.", category: "STATISTICAL_ERROR", optionIndex: 0 },
      { description: "Treated the point estimate as a finding despite an interval spanning zero.", category: "OVERCONFIDENCE", optionIndex: 2 },
      { description: "Read an interval containing negative values as proof of harm.", category: "LOGIC_ERROR", optionIndex: 3 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: false,
    tags: ["power", "policy"],
    origin: "seeded",
  },
  {
    id: "it-statistics-31",
    skill: "statistics",
    subskill: "log_regression_reading",
    concepts: ["regression", "exponents-and-logarithms"],
    level: "transfer",
    difficulty: 4,
    format: "numeric",
    prompt: "A wage regression is fitted with the natural logarithm of hourly wage as the outcome: ln(wage) = 2.10 + 0.08 × years of schooling. By roughly what percentage is predicted hourly wage higher for each additional year of schooling? Give a number of per cent (for example, 5 for 5 %).",
    answer: 8.3,
    tolerance: 0.4,
    unit: "%",
    solution:
      "A slope on a log-transformed outcome is a proportional change. One extra year of schooling raises ln(wage) by 0.08, which multiplies the wage by e^0.08 ≈ 1.0833, an increase of about 8.3 %. For small coefficients the rule of thumb 'read the slope as a percentage' (8 %) is close enough, and the exact figure is only slightly higher; for larger coefficients the gap grows (0.5 on the log scale is a 65 % rise, not 50 %). The intercept 2.10 is the predicted log wage at zero years of schooling: e^2.1 ≈ £8.17 per hour, an extrapolation that may lie outside the data. Reading the slope as '£0.08 per year' or as '0.08 %' are the two errors to avoid.",
    method: "For ln(y) = a + b·x, a unit change in x multiplies y by e^b; for small b, the percentage change is about 100b.",
    hints: ["The outcome is a logarithm. What does adding 0.08 to a log do to the original quantity?", "e^0.08 is a multiplier. Subtract one and express as a percentage.", "About 8 per cent; the exact figure is a little more."],
    commonErrors: [
      { description: "Reported the slope as a fraction (0.08) rather than a percentage.", category: "PRECISION_ERROR", value: 0.08 },
      { description: "Reported the intercept.", category: "MISREAD", value: 2.1 },
      { description: "Treated the slope as a wage in currency units and reported 0.8 %.", category: "CONCEPTUAL_ERROR", value: 0.8 },
    ],
    transfer: 2,
    minutes: 3,
    examEligible: true,
    tags: ["regression", "logarithms"],
    origin: "seeded",
  },
  {
    id: "it-statistics-32",
    skill: "statistics",
    subskill: "simpsons_paradox",
    concepts: ["simpsons-paradox", "causal-graphs", "confounding"],
    level: "transfer",
    difficulty: 4,
    format: "mcq",
    prompt: "A firm publishes its pay figures: women's average pay is 12 % below men's. A further table shows that within every job grade, women earn on average slightly more than men. Which reading is correct?",
    options: [
      "The two tables contradict each other, so one of them is wrong.",
      "The overall gap is a composition effect: women are concentrated in lower grades. Whether the within-grade comparison is the fair one depends on whether grade itself is assigned fairly; if promotion is where the disadvantage lies, stratifying on grade hides it rather than explains it.",
      "The within-grade figures prove that the firm pays fairly and the overall figure should be ignored.",
      "The overall figure is the only meaningful one because it uses all the data.",
    ],
    answer: 1,
    solution:
      "This is Simpson's paradox with a twist about which level to believe. Arithmetically there is no contradiction: an overall average is a weighted average of grade averages, and if women sit disproportionately in lower grades their overall mean falls below men's even while they are paid slightly more within each grade. Which comparison answers the question 'is there a pay disadvantage?' depends on the causal role of grade. If grade were decided by something unrelated to sex, the within-grade comparison would be the right one and the overall gap would be a composition effect. If grade is itself where the disadvantage operates (slower promotion for equal performance), then grade is on the causal path from sex to pay, and stratifying on it conditions away the effect being asked about. The tables settle the arithmetic and raise the real question, which is about promotion. Options 3 and 4 each pick one level as if the choice were statistical; it is causal.",
    method: "Confirm the weighted-average arithmetic, then ask whether the stratifying variable is a confounder (stratify on it) or a mediator on the path from cause to outcome (do not).",
    hints: ["Can both tables be true at once? Think of the overall figure as a weighted average.", "Which grades do women occupy, and how did they come to be there?", "If the disadvantage acts through promotion, what does comparing within grade do to it?"],
    commonErrors: [
      { description: "Treated a weighted-average reversal as a contradiction.", category: "CONCEPTUAL_ERROR", optionIndex: 0 },
      { description: "Treated the stratified comparison as automatically the fair one, ignoring that grade may be a mediator.", category: "CAUSAL_ERROR", optionIndex: 2 },
      { description: "Treated the pooled comparison as automatically right because it uses all the data.", category: "STATISTICAL_ERROR", optionIndex: 3 },
    ],
    transfer: 3,
    minutes: 4,
    examEligible: true,
    tags: ["simpsons-paradox", "pay-gap"],
    origin: "seeded",
  },
];
