import type { CaseDefinition } from "@/lib/domain/types";

/** The first case: self-contained so onboarding never depends on the seeded Casebook. */
export const BASELINE_CASE: CaseDefinition = {
  id: "case-baseline-lost-bag",
  number: "0001",
  title: "The Bag That Was Not There",
  setting: "The Marlowe, a mid-sized city hotel. Monday, 07:50.",
  summary: "A guest says the porter took her bag to her room last night and it never arrived. The porter says he delivered it. The bag is nowhere. Nobody is lying, necessarily.",
  difficulty: 2,
  estimatedMinutes: 14,
  faculties: ["observation", "inference", "social", "calibration"],
  subskills: ["observation.detail", "observation.text", "observation.chronology", "observation.separation", "inference.hypothesis", "inference.alternatives", "inference.information_value", "inference.updating", "inference.evidence_weighting", "rhetoric.explanation"],
  groundTruth: "The night porter delivered the bag to room 611, not 617: the handwritten luggage tag read 617 but a second, older tag from a previous hotel still hung from the handle with the number 611. The guest in 611 checked out at 06:30 and left the bag at reception in confusion; it is behind the desk. Nobody lied.",
  conceptLinks: ["base-rate-fallacy", "availability-heuristic"],
  safetyTags: ["fictional", "no-real-persons"],
  origin: "seeded",
  tags: ["travel", "psychology"],
  stages: [
    { id: "enter", kind: "enter", title: "The Bag That Was Not There", setting: "The Marlowe, a mid-sized city hotel. Monday, 07:50.", narrative: "You are covering the front desk for a colleague who is late. A guest, Ms Adeyemi from room 617, is at the desk with her coat on and her phone in her hand. Her bag was taken up by the night porter at 22:40 last night, she says, and it never arrived; she waited, then slept, and now she has a flight at 11:00. Tomasz, the night porter, is signing off in the back office and says he delivered it. The luggage log is on the desk in front of you.\n\nRead it as if you will need every line of it in five minutes." },
    { id: "notice", kind: "notice", title: "The luggage log", narrative: "The log, as it was left on the desk.", material: { kind: "document", title: "MARLOWE HOTEL — LUGGAGE LOG — SUNDAY NIGHT", seconds: 35, lines: ["22:31  ADEYEMI, room 617, one black wheeled case, tag written by T.K.", "22:34  PORTER LIFT out of service — using service stairs (note by T.K.)", "22:40  Delivered case to 6th floor — signature: T.K.", "22:52  Room 611 — do not disturb sign; case left inside door per guest request (phone call 22:49)", "23:15  OKAFOR, room 302, two bags, delivered 23:20, signed", "00:05  Lift engineer arrived; porter lift back in service 00:40", "06:30  Room 611 checked out — express, key cards left at desk", "06:45  Reception: 'a case behind desk, no ticket' — note by day porter", "07:20  Room 617 — guest called: bag not received", "Tag note (margin): case had TWO tags — ours (617) and an older hotel tag (611)"] } },
    {
      id: "recall",
      kind: "recall",
      title: "What was in the log?",
      narrative: "The log has been put away. Answer only what you actually read.",
      questions: [
        { id: "q1", prompt: "What time did the porter lift go out of service?", kind: "short", answer: "22:34", accept: ["2234", "10:34", "10.34", "22.34"], subskill: "observation.text" },
        { id: "q2", prompt: "Which room had a 'do not disturb' sign and asked for a case to be left inside the door?", kind: "mcq", options: ["611", "617", "302", "612"], answer: "611", subskill: "observation.detail" },
        { id: "q3", prompt: "How many tags were on the case, according to the margin note?", kind: "number", answer: "2", accept: ["two"], subskill: "observation.text" },
        { id: "q4", prompt: "Which happened first: the 611 checkout, or the day porter's note about a case behind the desk?", kind: "mcq", options: ["The 611 checkout", "The note about the case", "They were at the same time", "The log does not say"], answer: "The 611 checkout", subskill: "observation.chronology" },
        { id: "q5", prompt: "Who wrote the luggage tag for Ms Adeyemi's case?", kind: "short", answer: "T.K.", accept: ["tk", "t.k", "tomasz", "the porter", "t k"], subskill: "observation.detail" },
        { id: "q6", prompt: "What time did room 617 call to say the bag had not arrived?", kind: "short", answer: "07:20", accept: ["0720", "7:20", "7.20", "07.20"], subskill: "observation.text" },
      ],
    },
    {
      id: "separate",
      kind: "separate",
      title: "Observation, or story?",
      narrative: "Which of these did the log actually show, which are conclusions, and which does the log not settle?",
      statements: [
        { id: "s1", text: "The porter lift was out of service when the case was carried up.", truth: "observation", why: "22:34 out of service; 22:40 delivery. The log states both." },
        { id: "s2", text: "Tomasz delivered the case to room 617.", truth: "unknown", why: "The log says 'delivered to 6th floor' with no room number on that line." },
        { id: "s3", text: "The case had two tags with different room numbers.", truth: "observation", why: "The margin note says so explicitly." },
        { id: "s4", text: "Ms Adeyemi is exaggerating to get compensation.", truth: "inference", why: "Nothing in the log bears on her motives. A story, not a reading." },
        { id: "s5", text: "A case was behind the reception desk at 06:45 with no ticket.", truth: "observation", why: "The day porter's note at 06:45." },
        { id: "s6", text: "The guest in 611 took the case by mistake.", truth: "inference", why: "Plausible from the timeline, but the log does not say who moved the case." },
        { id: "s7", text: "The 611 guest asked for a case to be left inside their door.", truth: "observation", why: "22:52 entry, citing a phone call at 22:49." },
      ],
    },
    {
      id: "hypotheses",
      kind: "hypotheses",
      title: "Three explanations",
      narrative: "Before you talk to anyone, write what could have happened. The first explanation is easy. The second and third are the work.",
      rubric: {
        minimum: 2,
        plausible: [
          { title: "Delivered to 611 by the old tag", keywords: ["611", "wrong room", "old tag", "second tag", "other tag", "misread", "mixed up"], note: "Two tags, one of them 611; a 611 guest asked for a case to be left inside the door that same hour." },
          { title: "Case left behind at reception and never carried up", keywords: ["never delivered", "left at reception", "behind the desk", "still downstairs", "not carried", "stairs"], note: "The lift was out; the 'delivered to 6th floor' line has no room number." },
          { title: "Delivered to 617, then removed or moved", keywords: ["taken from 617", "stolen", "removed", "housekeeping", "moved", "someone took"], note: "Possible, but nothing in the log suggests it; it would require a further actor." },
          { title: "Guest error: she never handed it over or has it", keywords: ["kept it", "never gave", "in the room", "she has it", "forgot", "confused"], note: "The 22:31 log line makes this unlikely, but not impossible." },
        ],
      },
    },
    {
      id: "question",
      kind: "question",
      title: "One question",
      narrative: "Tomasz is putting on his jacket. Ms Adeyemi is looking at her watch. You can ask exactly one question before you act.",
      allowFreeQuestion: true,
      questionOptions: [
        { id: "o1", text: "Tomasz, which room did you leave the case in, and which tag did you read?", informationValue: 0.9, rapportCost: 0.1, leading: false, feedback: "The one question that separates the two leading explanations: it asks for a fact he has, without accusing." },
        { id: "o2", text: "Tomasz, did you actually deliver it, or did you leave it downstairs because the lift was out?", informationValue: 0.45, rapportCost: 0.5, leading: true, feedback: "Suggests its own answer and an accusation. He will say he delivered it; you learn little." },
        { id: "o3", text: "Ms Adeyemi, are you certain you handed the case to the porter?", informationValue: 0.25, rapportCost: 0.45, leading: false, feedback: "The log already records the handover at 22:31. This spends rapport re-asking what is written down." },
        { id: "o4", text: "Is the case behind the desk black, wheeled, and does it have two tags?", informationValue: 0.8, rapportCost: 0.0, leading: false, feedback: "Excellent and free: it tests the 611 explanation directly against the object in front of you." },
        { id: "o5", text: "Has anything like this happened before at the Marlowe?", informationValue: 0.2, rapportCost: 0.05, leading: false, feedback: "Base rates are useful, but this question does not help find this bag before 11:00." },
      ],
    },
    { id: "evidence", kind: "evidence", title: "Behind the desk", narrative: "You look.", reveal: { title: "The case behind the desk", text: "Black, wheeled, two tags. One in Tomasz's handwriting reads 617. The older one, from a hotel in Lyon, reads 611. A key card sleeve for 611 is tucked into the handle strap. The 611 guest checked out at 06:30 in a hurry and left it with a shrug and no explanation.", supports: ["Delivered to 611 by the old tag"], undermines: ["Case left behind at reception and never carried up", "Delivered to 617, then removed or moved", "Guest error: she never handed it over or has it"] } },
    { id: "update", kind: "update", title: "Update", narrative: "Given what you have just seen, how sure are you now of your primary explanation?", updatePrompt: "Confidence in your primary explanation, now." },
    {
      id: "decision",
      kind: "decision",
      title: "Decide",
      narrative: "It is 07:58. Ms Adeyemi has a flight at 11:00.",
      decisionOptions: [
        { id: "d1", text: "Return the case now, apologise plainly, and note the two-tag error in the log so it is checked at handover in future.", quality: 0.95, feedback: "The bag, the apology, and the fix for next time. Nobody is blamed for a mistake the system invited." },
        { id: "d2", text: "Return the case and reprimand Tomasz for delivering to the wrong room.", quality: 0.45, feedback: "The bag is returned, but the reprimand punishes a reading error caused by two tags and a broken lift, and teaches the next porter to hide mistakes.", errorType: "ASSUMPTION" },
        { id: "d3", text: "Hold the case until the 611 guest can be reached to confirm it is not theirs.", quality: 0.2, feedback: "Ms Adeyemi's name is on the tag in Tomasz's hand; the 611 guest has gone. Caution here is a cost with no benefit.", errorType: "PREMATURE_CLOSURE" },
        { id: "d4", text: "Offer compensation for the night without returning the case yet, to defuse the complaint.", quality: 0.15, feedback: "Solves the wrong problem. She wants her bag, not a voucher.", errorType: "MISREAD" },
      ],
    },
    { id: "explain", kind: "explain", title: "Explain", explainPrompt: "In a few sentences: what you observed, what you inferred from it, the alternative you rejected, and what would have changed your mind." },
    { id: "debrief", kind: "debrief", title: "Debrief", expertReasoning: "An experienced desk manager reads the log for what it does not say: 'delivered to 6th floor' has no room number, and the margin note about two tags is the highest-information line on the page. Two explanations survive that reading, and the object behind the desk separates them at no cost. The tempting story, that someone is lying, requires a further actor and explains nothing the two-tag story does not. The decision follows from the diagnosis: fix the system that produced the error rather than the person who fell into it.", keyInsight: "The most useful line in a document is often the one in the margin." },
  ],
};
