/**
 * Inference room content, part B.
 * How Sure (calibration), Information Value, the Inference Ladder, Causal, Fast/Slow.
 *
 * Keywords are lower-case stems for deterministic matching (substring, see keyPointCoverage in lib/scoring/text.ts);
 * each keyword may carry synonyms separated by "|".
 */
import type {
  HowSureChallenge,
  InformationValueChallenge,
  LadderChallenge,
  CausalChallenge,
  FastSlowChallenge,
} from "@/lib/domain/content";

/* ---------------- How Sure ----------------
 * Each answer is paired with a confidence. The point is not the answer; it is whether
 * 70% means 70%. Roughly half the items should leave a well-read person honestly unsure.
 */
export const HOW_SURE: HowSureChallenge[] = [
  {
    id: "hs-westphalia-year",
    title: "The end of the Thirty Years' War",
    question: "The Peace of Westphalia, which ended the Thirty Years' War, was signed in which year?",
    options: [
      { id: "a", text: "1618" },
      { id: "b", text: "1648" },
      { id: "c", text: "1688" },
      { id: "d", text: "1713" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "1648. The war began in 1618, so the first option is the start, not the end. 1688 is England's Glorious Revolution and 1713 the Treaty of Utrecht. The treaties were signed at Osnabrück and Münster after five years of negotiation.",
    difficulty: 2,
  },
  {
    id: "hs-suez-vs-panama",
    title: "Two canals",
    question: "Compare the lengths of the Suez Canal and the Panama Canal. Which is closest to the truth?",
    options: [
      { id: "a", text: "They are roughly the same length" },
      { id: "b", text: "Suez is roughly twice as long as Panama" },
      { id: "c", text: "Panama is roughly twice as long as Suez" },
      { id: "d", text: "Suez is roughly ten times as long as Panama" },
    ],
    correct: "b",
    domain: "quantitative",
    explanation:
      "Suez runs about 193 km from Port Said to Suez; Panama is about 82 km from Atlantic to Pacific. A ratio of roughly 2.4. People who picture Panama as the great engineering feat often guess it is longer; it is shorter but climbs through locks, which Suez never needed.",
    difficulty: 4,
  },
  {
    id: "hs-bretton-woods-year",
    title: "Designing the post-war money",
    question: "The Bretton Woods conference, which created the IMF and the World Bank, met in which year?",
    options: [
      { id: "a", text: "1929" },
      { id: "b", text: "1936" },
      { id: "c", text: "1944" },
      { id: "d", text: "1971" },
    ],
    correct: "c",
    domain: "knowledge",
    explanation:
      "July 1944, in New Hampshire, before the war in Europe had ended. 1929 is the crash, 1936 the Tripartite Agreement on currencies, and 1971 the year the system it created came apart.",
    difficulty: 2,
  },
  {
    id: "hs-nixon-gold-window",
    title: "Closing the gold window",
    question: "In which year did the United States suspend the dollar's convertibility into gold, ending the Bretton Woods arrangement in practice?",
    options: [
      { id: "a", text: "1944" },
      { id: "b", text: "1965" },
      { id: "c", text: "1971" },
      { id: "d", text: "1985" },
    ],
    correct: "c",
    domain: "knowledge",
    explanation:
      "15 August 1971, announced by Nixon on a Sunday evening. 1944 is the creation of the system; 1985 is the Plaza Accord, which managed floating currencies rather than fixed ones.",
    difficulty: 3,
  },
  {
    id: "hs-gutenberg-decade",
    title: "The first printed Bible",
    question: "Gutenberg's printed Bible was completed in which decade?",
    options: [
      { id: "a", text: "1390s" },
      { id: "b", text: "1450s" },
      { id: "c", text: "1490s" },
      { id: "d", text: "1520s" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "Around 1454 to 1455 in Mainz. The 1490s tempt people because Columbus and Aldus Manutius make that decade feel like the start of the modern; the 1520s tempt because of Luther, whose success depended on presses that had by then been running for seventy years.",
    difficulty: 3,
  },
  {
    id: "hs-black-death-arrival",
    title: "Plague reaches Europe",
    question: "The Black Death arrived in Europe, at Sicilian ports, in which year?",
    options: [
      { id: "a", text: "1247" },
      { id: "b", text: "1347" },
      { id: "c", text: "1447" },
      { id: "d", text: "1547" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "October 1347, on Genoese ships from the Black Sea port of Caffa. Within four years it had reached Scandinavia and Russia. The spacing of the options by a century is deliberate: if you were between two of them, that is worth knowing about yourself.",
    difficulty: 2,
  },
  {
    id: "hs-constantinople-1453",
    title: "The city falls",
    question: "Which Ottoman sultan took Constantinople in 1453?",
    options: [
      { id: "a", text: "Suleiman I" },
      { id: "b", text: "Mehmed II" },
      { id: "c", text: "Bayezid I" },
      { id: "d", text: "Selim I" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "Mehmed II, aged twenty-one, thereafter called the Conqueror. Bayezid I had besieged the city half a century earlier and failed. Suleiman, the best-known name, reigned from 1520.",
    difficulty: 3,
  },
  {
    id: "hs-genghis-death",
    title: "The death of Genghis Khan",
    question: "In which year did Genghis Khan die?",
    options: [
      { id: "a", text: "1187" },
      { id: "b", text: "1227" },
      { id: "c", text: "1267" },
      { id: "d", text: "1294" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "1227, during a campaign against the Western Xia. 1294 is the death of his grandson Kublai. Most people can place the Mongol conquests in the thirteenth century and no closer; 65% confidence between two adjacent options is an honest answer here.",
    difficulty: 5,
  },
  {
    id: "hs-voc-founded",
    title: "The first joint-stock giant",
    question: "The Dutch East India Company (VOC) received its charter in which year?",
    options: [
      { id: "a", text: "1582" },
      { id: "b", text: "1602" },
      { id: "c", text: "1652" },
      { id: "d", text: "1702" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "1602, two years after the English East India Company. The Amsterdam exchange that traded its shares followed shortly after. 1652 is the founding of the Cape settlement by the same company.",
    difficulty: 4,
  },
  {
    id: "hs-bach-year",
    title: "Three composers, one year",
    question: "Johann Sebastian Bach was born in the same year as Handel and Domenico Scarlatti. Which year?",
    options: [
      { id: "a", text: "1645" },
      { id: "b", text: "1685" },
      { id: "c", text: "1725" },
      { id: "d", text: "1750" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "1685. 1750 is the year Bach died, which musicologists use as a convenient end-date for the Baroque; if you chose it, you had the right century and the wrong end of a life.",
    difficulty: 4,
  },
  {
    id: "hs-impression-sunrise",
    title: "A name meant as an insult",
    question: "The word Impressionism was coined by a critic mocking a painting by which artist?",
    options: [
      { id: "a", text: "Édouard Manet" },
      { id: "b", text: "Claude Monet" },
      { id: "c", text: "Edgar Degas" },
      { id: "d", text: "Pierre-Auguste Renoir" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "Monet's Impression, Sunrise, shown at the group's first exhibition in 1874; the critic Louis Leroy used the title against the whole show. Manet is the common confusion: an ally and influence, but he never exhibited with the group.",
    difficulty: 3,
  },
  {
    id: "hs-odyssey-years",
    title: "How long was Odysseus away?",
    question: "In the Odyssey, how many years pass between Odysseus leaving Ithaca for Troy and his return?",
    options: [
      { id: "a", text: "7" },
      { id: "b", text: "10" },
      { id: "c", text: "20" },
      { id: "d", text: "30" },
    ],
    correct: "c",
    domain: "knowledge",
    explanation:
      "Twenty: ten years of war and ten years of return, of which seven were spent on Calypso's island. The fast answer is ten, because the wandering is the famous part; Telemachus, an infant at the departure, is a young man on his father's return.",
    difficulty: 4,
  },
  {
    id: "hs-michelin-first-guide",
    title: "The tyre company's guidebook",
    question: "The first Michelin Guide, given away free to French motorists, appeared in which year?",
    options: [
      { id: "a", text: "1889" },
      { id: "b", text: "1900" },
      { id: "c", text: "1926" },
      { id: "d", text: "1936" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "1900, when France had a few thousand cars. The point was to make people drive more and wear out tyres. Restaurant stars came in 1926 and the three-tier system in the early 1930s, which is why the later options attract confident wrong answers.",
    difficulty: 5,
  },
  {
    id: "hs-everest-boiling",
    title: "Boiling water on Everest",
    question: "Roughly what is the boiling point of water at the summit of Everest, where air pressure is about a third of sea level?",
    options: [
      { id: "a", text: "About 100 °C" },
      { id: "b", text: "About 85 °C" },
      { id: "c", text: "About 70 °C" },
      { id: "d", text: "About 50 °C" },
    ],
    correct: "c",
    domain: "quantitative",
    explanation:
      "About 70 °C. Boiling point falls roughly one degree per 300 metres of altitude near sea level and somewhat faster higher up; at 8,849 m that is close to thirty degrees lost. Tea at the summit is disappointing and rice does not cook.",
    difficulty: 4,
  },
  {
    id: "hs-co2-share",
    title: "How much of the air is carbon dioxide?",
    question: "Roughly what share of Earth's atmosphere, by volume, is carbon dioxide?",
    options: [
      { id: "a", text: "About 4%" },
      { id: "b", text: "About 0.4%" },
      { id: "c", text: "About 0.04%" },
      { id: "d", text: "About 0.004%" },
    ],
    correct: "c",
    domain: "quantitative",
    explanation:
      "About 0.04%, or a little over 420 parts per million. Nitrogen and oxygen make up 99%, argon almost all of the rest. The number is small; its rise from about 280 ppm before industry is what matters. Most people guess an order of magnitude too high.",
    difficulty: 3,
  },
  {
    id: "hs-dice-seven",
    title: "Two dice",
    question: "You roll two fair six-sided dice. What is the probability that the faces sum to 7?",
    options: [
      { id: "a", text: "1/12" },
      { id: "b", text: "1/6" },
      { id: "c", text: "1/4" },
      { id: "d", text: "1/3" },
    ],
    correct: "b",
    domain: "quantitative",
    explanation:
      "Six of the 36 equally likely ordered pairs sum to 7 (1-6, 2-5, 3-4 and their reverses), so 6/36 = 1/6. Seven is the most likely total precisely because it can be made in the most ways.",
    difficulty: 2,
  },
  {
    id: "hs-birthday-room",
    title: "Shared birthdays",
    question: "How many people must be in a room for it to be more likely than not that two of them share a birthday?",
    options: [
      { id: "a", text: "23" },
      { id: "b", text: "57" },
      { id: "c", text: "183" },
      { id: "d", text: "366" },
    ],
    correct: "a",
    domain: "quantitative",
    explanation:
      "23. The intuition that pulls toward 183 is asking a different question: how many people you need for someone to share your birthday. Pairs grow with the square of the group size, and 23 people make 253 pairs. At 57 people the probability is already 99%.",
    difficulty: 3,
  },
  {
    id: "hs-five-flips",
    title: "Five coin flips",
    question: "A fair coin is flipped five times. What is the probability of exactly three heads?",
    options: [
      { id: "a", text: "1/2" },
      { id: "b", text: "3/8" },
      { id: "c", text: "5/16" },
      { id: "d", text: "1/4" },
    ],
    correct: "c",
    domain: "quantitative",
    explanation:
      "There are 32 equally likely sequences and C(5,3) = 10 of them contain exactly three heads: 10/32 = 5/16, a little under a third. Three-of-five feels like the 'typical' outcome, which makes 1/2 tempting; typical is not the same as probable.",
    difficulty: 4,
  },
  {
    id: "hs-late-delivery",
    title: "What follows?",
    question: "All of the shop's Tuesday deliveries arrive late. A delivery has just arrived late. What can you conclude?",
    options: [
      { id: "a", text: "It is a Tuesday delivery" },
      { id: "b", text: "It is not a Tuesday delivery" },
      { id: "c", text: "Nothing about which day it was scheduled for" },
      { id: "d", text: "It is a Tuesday delivery, and the driver is at fault" },
    ],
    correct: "c",
    domain: "inference",
    explanation:
      "Tuesday implies late; late does not imply Tuesday. Deliveries on other days may also be late. This is affirming the consequent, and it is the shape of most everyday misreadings of evidence: a symptom that always accompanies one cause is taken to prove that cause.",
    difficulty: 2,
  },
  {
    id: "hs-ledger-negation",
    title: "Denying a universal",
    question: "An auditor writes: it is false that every entry in this ledger is dated. Which statement must be true?",
    options: [
      { id: "a", text: "No entry in the ledger is dated" },
      { id: "b", text: "At least one entry is undated" },
      { id: "c", text: "Most entries are undated" },
      { id: "d", text: "The ledger has been tampered with" },
    ],
    correct: "b",
    domain: "inference",
    explanation:
      "The negation of 'all' is 'at least one is not', nothing stronger. One missing date makes the auditor's sentence true. The last option is an interpretation dressed as a conclusion; nothing in the sentence supports it.",
    difficulty: 2,
  },
  {
    id: "hs-northernmost-city",
    title: "Which is furthest north?",
    question: "Of these four cities, which lies furthest north?",
    options: [
      { id: "a", text: "New York" },
      { id: "b", text: "Rome" },
      { id: "c", text: "Istanbul" },
      { id: "d", text: "Beijing" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "Rome, at about 41.9° N; Istanbul is at 41.0°, New York 40.7° and Beijing 39.9°. All four sit within two degrees of latitude, which is why mental maps fail: New York's winters and Rome's summers make people place them a continent's width apart. Confidence here should be modest.",
    difficulty: 5,
  },
  {
    id: "hs-canal-no-locks",
    title: "A canal without locks",
    question: "Which of these canals has no locks at all?",
    options: [
      { id: "a", text: "Panama Canal" },
      { id: "b", text: "Kiel Canal" },
      { id: "c", text: "Suez Canal" },
      { id: "d", text: "Erie Canal" },
    ],
    correct: "c",
    domain: "knowledge",
    explanation:
      "Suez is a sea-level cut through flat desert between two seas with nearly equal levels, so it needs none. Panama climbs to Gatún Lake and back; the Kiel Canal has lock chambers at both ends to manage the tidal difference; the Erie Canal descends the whole way from Lake Erie to the Hudson.",
    difficulty: 4,
  },
  {
    id: "hs-gold-standard-deficit",
    title: "The gold standard's discipline",
    question: "Under the classical gold standard, a country running a persistent trade deficit would, according to the standard account, tend to experience which of these?",
    options: [
      { id: "a", text: "Gold inflows and rising domestic prices" },
      { id: "b", text: "Gold outflows and falling domestic prices" },
      { id: "c", text: "Gold outflows and rising domestic prices" },
      { id: "d", text: "No change in its gold stock, since exchange rates would adjust" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "Deficits were settled in gold, the outflow shrank the money supply, prices fell, exports became cheaper and the deficit closed. That is Hume's price-specie flow mechanism. The last option describes floating currencies; fixed gold parities were the whole point, so the adjustment had to fall on prices and wages instead.",
    difficulty: 4,
  },
  {
    id: "hs-silk-road-name",
    title: "Who named the Silk Road?",
    question: "The term Silk Road was coined in 1877 by which of these?",
    options: [
      { id: "a", text: "Marco Polo" },
      { id: "b", text: "Ferdinand von Richthofen" },
      { id: "c", text: "Alexander von Humboldt" },
      { id: "d", text: "Aurel Stein" },
    ],
    correct: "b",
    domain: "knowledge",
    explanation:
      "The German geographer Ferdinand von Richthofen, writing about routes across Central Asia. Marco Polo travelled the routes six centuries earlier and never called them anything of the kind; Stein excavated along them a generation after Richthofen. Traders on the routes did not think of themselves as being on a single road at all.",
    difficulty: 5,
  },
];

/* ---------------- Information Value ----------------
 * One question. Which reduces uncertainty most? Exactly one is clearly best; one is clearly leading.
 */
export const INFORMATION_VALUE: InformationValueChallenge[] = [
  {
    id: "iv-late-delivery",
    title: "The Late Delivery",
    scenario: "A supplier's shipment that was promised for Monday arrives on Thursday. The invoice is dated Monday. Your operations lead says this has happened twice before. The supplier's account manager, usually quick to reply, took two days to answer your email and then apologised without explanation.",
    unknowns: ["Whether the delay originated with the supplier or the carrier", "Whether the invoice date reflects dispatch or paperwork", "Whether the previous two delays had the same cause", "Whether the account manager knows the cause", "Whether other customers were affected"],
    questions: [
      { id: "q1", text: "Which carrier collected the shipment, and on what date did they scan it?", informationValue: 0.9, rapportCost: 0.05, leading: false, feedback: "Separates supplier delay from carrier delay with a checkable fact, and dates the invoice against reality." },
      { id: "q2", text: "Is it true that your warehouse has been having problems again?", informationValue: 0.2, rapportCost: 0.55, leading: true, feedback: "Assumes the cause and invites a defensive denial. Even a yes tells you little." },
      { id: "q3", text: "Were other customers' orders delayed this week?", informationValue: 0.6, rapportCost: 0.1, leading: false, feedback: "Useful: a systemic problem versus something specific to your order. But the answer may be hard for them to give honestly." },
      { id: "q4", text: "Can you make sure this doesn't happen again?", informationValue: 0.1, rapportCost: 0.3, leading: false, feedback: "A request, not a question. It produces reassurance rather than information." },
      { id: "q5", text: "Was the delay the same reason as the previous two?", informationValue: 0.5, rapportCost: 0.15, leading: false, feedback: "Good instinct about patterns, but it asks for an interpretation rather than a fact you can verify." },
    ],
    debrief: "The strongest question asks for a checkable fact that discriminates between the two main explanations. Questions that ask the other party to characterise themselves rarely move you far.",
    difficulty: 3,
  },
  {
    id: "iv-quiet-colleague",
    title: "The Quiet Colleague",
    scenario: "A colleague who usually contributes readily in meetings has said almost nothing for two weeks. They have started arriving earlier than anyone else and leaving on time. Their work quality is unchanged. Another colleague mentioned, in passing, that they had been asked to sit on an interview panel.",
    unknowns: ["Whether something outside work has changed", "Whether they are preparing for a role change", "Whether they feel sidelined in meetings", "Whether the pattern is deliberate", "Whether they want to talk about it"],
    questions: [
      { id: "q1", text: "You've seemed a bit withdrawn. Is everything alright at home?", informationValue: 0.25, rapportCost: 0.5, leading: true, feedback: "Presumes a personal cause and a problem. Likely to produce 'fine, thanks' and a closed door." },
      { id: "q2", text: "How are you finding the meetings at the moment?", informationValue: 0.75, rapportCost: 0.05, leading: false, feedback: "Open, specific to the observed change, and leaves room for any explanation, including one you have not thought of." },
      { id: "q3", text: "Are you going for the new role?", informationValue: 0.45, rapportCost: 0.35, leading: false, feedback: "Direct and possibly right, but it forces disclosure they may not be ready to make and reveals you have been speculating." },
      { id: "q4", text: "Do you want to grab a coffee this week?", informationValue: 0.35, rapportCost: 0.0, leading: false, feedback: "Builds the conditions for information rather than gathering it. A fine move, but not the question that resolves the unknowns." },
      { id: "q5", text: "Has someone said something to upset you?", informationValue: 0.2, rapportCost: 0.4, leading: true, feedback: "Assumes conflict. If untrue it is awkward; if true it is unlikely to be answered honestly on the spot." },
    ],
    debrief: "In social situations, the question that reduces uncertainty most is often the open one attached to a specific observation. It respects the other person's control of the disclosure.",
    difficulty: 3,
  },
  {
    id: "iv-falling-sales",
    title: "The Falling Number",
    scenario: "Monthly sales of a product fell 18% compared with the same month last year. Marketing spend was unchanged. A competitor launched a cheaper product four months ago. The company changed its website checkout in the last month. Regional managers report nothing unusual.",
    unknowns: ["Whether the fall is concentrated in online sales", "Whether it began before or after the checkout change", "Whether the competitor is taking share", "Whether the fall is seasonal noise", "Whether returns or cancellations rose"],
    questions: [
      { id: "q1", text: "What is the weekly sales figure for the last sixteen weeks, split online and in-store?", informationValue: 0.92, rapportCost: 0.05, leading: false, feedback: "One dataset answers three unknowns at once: timing relative to the checkout change, channel concentration, and noise versus trend." },
      { id: "q2", text: "Isn't this obviously the competitor's price cut?", informationValue: 0.15, rapportCost: 0.3, leading: true, feedback: "Announces a conclusion. Anyone who agrees is agreeing with you, not with the evidence." },
      { id: "q3", text: "Did the checkout change break anything?", informationValue: 0.45, rapportCost: 0.2, leading: false, feedback: "Reasonable, but 'anything' is vague and the people asked have an incentive to say no." },
      { id: "q4", text: "How did sales move in the same month two years ago?", informationValue: 0.5, rapportCost: 0.0, leading: false, feedback: "Tests seasonality. Useful, but narrower than the weekly split." },
      { id: "q5", text: "What do the regional managers think caused it?", informationValue: 0.3, rapportCost: 0.05, leading: false, feedback: "Opinions from people who already reported nothing unusual. Low expected surprise." },
    ],
    debrief: "When several explanations differ in timing and channel, ask for the data that would separate them along those axes. One good dataset beats five opinions.",
    difficulty: 4,
  },
  {
    id: "iv-the-referee",
    title: "The Referee's Report",
    scenario: "Your paper was rejected. The editor's note says two referees were split. Referee A called the method sound but the contribution modest. Referee B found a 'fatal flaw' but did not specify it in the excerpt you received. The editor invites resubmission after 'substantial revision'.",
    unknowns: ["What the fatal flaw is", "Whether the editor agrees with B", "Whether resubmission goes to the same referees", "Whether 'substantial' means scope or correctness", "Whether B read the appendix"],
    questions: [
      { id: "q1", text: "Could you share Referee B's full comments, particularly the section describing the flaw?", informationValue: 0.9, rapportCost: 0.05, leading: false, feedback: "The single biggest unknown, asked for directly and politely. Everything else depends on it." },
      { id: "q2", text: "Do you think Referee B actually read the paper?", informationValue: 0.15, rapportCost: 0.6, leading: true, feedback: "Insulting to the process and to the editor's judgement. It tells you nothing you can use." },
      { id: "q3", text: "Would a resubmission go to the same referees?", informationValue: 0.5, rapportCost: 0.1, leading: false, feedback: "Practical and useful, but secondary until you know what you are fixing." },
      { id: "q4", text: "Is the revision you have in mind about scope or about correctness?", informationValue: 0.65, rapportCost: 0.1, leading: false, feedback: "A good discriminating question about the editor's own view. Slightly less valuable than seeing B's argument itself." },
      { id: "q5", text: "Would it help if I added more experiments?", informationValue: 0.3, rapportCost: 0.15, leading: false, feedback: "Proposes a remedy before the diagnosis. The editor can only guess." },
    ],
    debrief: "When one unknown dominates the others, ask about that one. Ask for the text of an argument rather than someone's summary of it.",
    difficulty: 3,
  },
  {
    id: "iv-the-flat",
    title: "The Flat Viewing",
    scenario: "You are viewing a flat to rent. It is freshly painted, smells faintly of damp near the bathroom, and the agent says the previous tenants 'left quickly'. The rent is 12% below similar flats nearby. The listing has been live for six weeks.",
    unknowns: ["Whether there is a damp problem", "Why the previous tenants left", "Why the rent is low", "Whether the flat has been let and fallen through", "Whether the landlord is responsive to repairs"],
    questions: [
      { id: "q1", text: "Has the flat had any damp or mould treatment in the last two years, and can I see the inspection or invoice?", informationValue: 0.85, rapportCost: 0.15, leading: false, feedback: "Targets the most consequential unknown with a request for a document rather than a reassurance." },
      { id: "q2", text: "This place has damp, doesn't it?", informationValue: 0.25, rapportCost: 0.45, leading: true, feedback: "The agent will deny it; you already suspected it. Net information: almost none." },
      { id: "q3", text: "How many people have viewed the flat in six weeks, and did anyone apply?", informationValue: 0.6, rapportCost: 0.1, leading: false, feedback: "Reveals whether others saw something you should see. A strong second question." },
      { id: "q4", text: "Can you tell me why the previous tenants left?", informationValue: 0.4, rapportCost: 0.1, leading: false, feedback: "Fair, but the agent's answer is unverifiable and likely to be bland." },
      { id: "q5", text: "Is the landlord good with repairs?", informationValue: 0.2, rapportCost: 0.05, leading: false, feedback: "No agent will say no. Ask for the last repair's date and what it was instead." },
    ],
    debrief: "Questions that request evidence (documents, dates, counts) outperform questions that request characterisations, especially from someone with an incentive to reassure.",
    difficulty: 3,
  },
  {
    id: "iv-the-diagnosis-analogy",
    title: "The Slow Website",
    scenario: "Users report that the site is slow 'in the afternoons'. The server metrics show normal CPU. A new analytics script was added last week. Two of the three complaints came from the same office, which shares one internet connection. The database was migrated to a new host a month ago.",
    unknowns: ["Whether slowness is server-side or client-side", "Whether it is specific to one network", "Whether the analytics script is responsible", "Whether the database host is slower at peak", "Whether 'afternoon' correlates with a load pattern"],
    questions: [
      { id: "q1", text: "What are the server-measured response times by hour for the past two weeks, and do they rise in the afternoons?", informationValue: 0.85, rapportCost: 0.0, leading: false, feedback: "Distinguishes server-side from client-side and tests the afternoon claim with data rather than reports." },
      { id: "q2", text: "Did the new analytics script cause this?", informationValue: 0.3, rapportCost: 0.1, leading: false, feedback: "One hypothesis, tested by opinion. A better version asks for page load timings with the script disabled." },
      { id: "q3", text: "Surely it's that office's connection?", informationValue: 0.2, rapportCost: 0.3, leading: true, feedback: "Plausible, and asked in a way that dismisses the users. Test it instead: ask the third complainant where they were." },
      { id: "q4", text: "Did the database migration change query latency?", informationValue: 0.55, rapportCost: 0.0, leading: false, feedback: "A real candidate, but only one of several; the hourly response data would reveal it anyway." },
      { id: "q5", text: "Has anyone complained who was not in that office?", informationValue: 0.6, rapportCost: 0.0, leading: false, feedback: "Cheap and discriminating: it tests the shared-connection hypothesis directly." },
    ],
    debrief: "When a report is anecdotal, the highest-value question converts it into a measurement that can discriminate between explanations.",
    difficulty: 4,
  },
  {
    id: "iv-the-gift",
    title: "The Unexpected Gift",
    scenario: "A business contact you have met twice sends an expensive bottle of wine to your office with a card reading 'Looking forward to working together'. You have no active project with them. Your company has a gifts policy with a threshold you suspect this exceeds.",
    unknowns: ["What they expect in return", "Whether they sent the same to others", "Whether they know your policy", "Whether an approach is coming", "Whether the gift is customary in their culture or firm"],
    questions: [
      { id: "q1", text: "Thank you — what did you have in mind when you wrote 'working together'?", informationValue: 0.85, rapportCost: 0.05, leading: false, feedback: "Warm, direct, and it makes the sender state the intention rather than leaving you to infer it." },
      { id: "q2", text: "Are you trying to influence a decision?", informationValue: 0.25, rapportCost: 0.7, leading: true, feedback: "Accusatory. Whatever the intention, the answer will be no." },
      { id: "q3", text: "Did you send these to the whole team?", informationValue: 0.5, rapportCost: 0.2, leading: false, feedback: "Tests whether it is targeted. Useful, but the intention question covers it more gracefully." },
      { id: "q4", text: "Are you aware we have a gifts policy?", informationValue: 0.35, rapportCost: 0.4, leading: false, feedback: "Necessary to raise, but as a question it produces embarrassment rather than information." },
      { id: "q5", text: "Is this a tradition at your firm?", informationValue: 0.4, rapportCost: 0.05, leading: false, feedback: "Offers a face-saving explanation. Reasonable, but it invites them to take the exit rather than state the purpose." },
    ],
    debrief: "The best question here uses the sender's own words. It forces a statement of purpose while keeping the relationship intact.",
    difficulty: 3,
  },
  {
    id: "iv-the-broken-experiment",
    title: "The Result That Vanished",
    scenario: "A promising effect seen in a pilot study disappears in a larger replication run by a different lab. The pilot used a sample of 24; the replication used 240. The replication changed the measurement instrument to a newer model. The pilot's lead author has moved institutions and did not respond to requests for raw data.",
    unknowns: ["Whether the pilot result was noise", "Whether the instrument change matters", "Whether the populations differ", "Whether the analysis was the same", "Whether the pilot data still exist"],
    questions: [
      { id: "q1", text: "Was the replication's analysis pre-registered, and does re-running the pilot's exact analysis on the replication data recover the effect?", informationValue: 0.85, rapportCost: 0.05, leading: false, feedback: "Separates analytic flexibility from a genuine null. Very high information per question." },
      { id: "q2", text: "Isn't the pilot just p-hacked?", informationValue: 0.2, rapportCost: 0.6, leading: true, feedback: "An accusation dressed as a question. It may be right and still yields nothing usable." },
      { id: "q3", text: "Does the new instrument produce systematically different readings from the old one?", informationValue: 0.6, rapportCost: 0.0, leading: false, feedback: "A real confound worth checking. Narrower than the analysis question." },
      { id: "q4", text: "Do you believe the effect is real?", informationValue: 0.15, rapportCost: 0.05, leading: false, feedback: "Belief is not evidence. You want the analysis, not the vote." },
      { id: "q5", text: "Where did each study recruit participants?", informationValue: 0.45, rapportCost: 0.0, leading: false, feedback: "Population differences are possible, though with n=24 noise remains the leading explanation." },
    ],
    debrief: "With small pilots, the base rate says noise. The best question tests whether the difference is analytic or real before reaching for exotic explanations.",
    difficulty: 5,
  },
  {
    id: "iv-the-neighbour",
    title: "The Neighbour's Extension",
    scenario: "A neighbour tells you they are building a small extension 'next month'. You have seen no planning notice. A builder's van has been parked outside twice. They mention that 'the council were fine with it'. Your bedroom window faces the proposed wall.",
    unknowns: ["Whether planning permission is required", "Whether it was obtained", "What the extension's height and position will be", "Whether the neighbour knows your window is affected", "Whether the work is imminent"],
    questions: [
      { id: "q1", text: "Could I see the drawings? I'd like to understand the height and how close it comes to my window.", informationValue: 0.85, rapportCost: 0.1, leading: false, feedback: "Asks for the artefact that settles most unknowns, and states your interest plainly without hostility." },
      { id: "q2", text: "You haven't got permission for this, have you?", informationValue: 0.3, rapportCost: 0.7, leading: true, feedback: "Starts a dispute. Even if right, you have lost the cooperative route." },
      { id: "q3", text: "When you say the council were fine, was that a formal decision or a conversation?", informationValue: 0.7, rapportCost: 0.15, leading: false, feedback: "Excellent clarifying question. It pins down an ambiguous phrase without accusing." },
      { id: "q4", text: "Who is your builder?", informationValue: 0.2, rapportCost: 0.05, leading: false, feedback: "Friendly, but it does not touch the unknowns that matter to you." },
      { id: "q5", text: "Will it block my light?", informationValue: 0.4, rapportCost: 0.2, leading: false, feedback: "Asks them to judge your interest for you. The drawings would let you judge it yourself." },
    ],
    debrief: "Two questions here are strong. The document request wins because it replaces the neighbour's interpretation with something you can read yourself.",
    difficulty: 3,
  },
  {
    id: "iv-the-candidate",
    title: "The Reference Call",
    scenario: "You are calling a referee for a job candidate. The referee is the candidate's former manager. The candidate's CV says they 'led' a project that the referee's company website credits to someone else. The referee has been warm but general for five minutes.",
    unknowns: ["What the candidate's actual role on the project was", "Why the referee is being general", "Whether the candidate left on good terms", "Whether the referee would rehire them", "What the candidate's weaknesses are"],
    questions: [
      { id: "q1", text: "On the platform project, what specifically did they own, and who else was on it?", informationValue: 0.9, rapportCost: 0.05, leading: false, feedback: "Converts 'led' into a description of responsibilities and a cross-check against the credited name." },
      { id: "q2", text: "They didn't really lead that project, did they?", informationValue: 0.3, rapportCost: 0.5, leading: true, feedback: "Puts the referee in the position of either contradicting the candidate or agreeing with you. Neither yields a clean fact." },
      { id: "q3", text: "Would you hire them again?", informationValue: 0.55, rapportCost: 0.1, leading: false, feedback: "A classic and a good one; the hesitation before the answer is often the answer. But it is second to the specific role question." },
      { id: "q4", text: "Is there anything I should know?", informationValue: 0.25, rapportCost: 0.0, leading: false, feedback: "Too open. A warm-but-general referee will stay warm and general." },
      { id: "q5", text: "What would their closest colleague say they need to work on?", informationValue: 0.5, rapportCost: 0.1, leading: false, feedback: "A good way to ask for weaknesses without asking the referee to be disloyal." },
    ],
    debrief: "The verb 'led' is doing a lot of work on the CV. The highest-value question asks the referee to replace the verb with the facts.",
    difficulty: 4,
  },
];

/* ---------------- Inference Ladder ---------------- */
export const LADDER: LadderChallenge[] = [
  {
    id: "ld-empty-office",
    title: "The Empty Office at Nine",
    situation: "You arrive at the office at 9:10. The lights on the second floor are on but no one is at the twelve desks. Three monitors are awake. There is a coat on the back of one chair and a laptop bag under another. The kitchen kettle is warm to the touch. The meeting room's glass wall is frosted, which happens only when someone sets it from inside. A courier's delivery slip is on the reception counter, timed 8:52.",
    observations: [
      { text: "Twelve desks, no people, lights on", keywords: ["desks", "lights on", "no one", "nobody", "empty"] },
      { text: "Three monitors awake", keywords: ["monitor", "screens awake", "three monitors"] },
      { text: "Coat on a chair, bag under another", keywords: ["coat", "bag", "laptop bag"] },
      { text: "Kettle warm", keywords: ["kettle", "warm"] },
      { text: "Meeting room frosted from inside", keywords: ["frosted", "meeting room", "glass"] },
      { text: "Courier slip timed 8:52", keywords: ["courier", "8:52", "slip", "delivery"] },
    ],
    inferences: [
      { text: "People were here recently and are still in the building", keywords: ["recently", "still here", "still in the building", "nearby"] },
      { text: "A meeting is in progress in the frosted room", keywords: ["meeting", "in progress", "in the room"] },
      { text: "Someone accepted the delivery at 8:52", keywords: ["accepted", "delivery", "signed"] },
    ],
    alternatives: [
      { text: "A fire drill or evacuation, with people outside", keywords: ["fire drill", "evacuation", "outside", "alarm"] },
      { text: "An all-hands meeting elsewhere in the building", keywords: ["all-hands", "another floor", "elsewhere", "town hall"] },
      { text: "The room was frosted earlier and nobody unset it", keywords: ["frosted earlier", "left frosted", "not unset"] },
    ],
    debrief: "The frosted glass is the strongest single clue because it requires an action from inside. But it does not date that action. The warm kettle does the dating. Notice how many of your inferences depend on stacking one on another.",
    difficulty: 3,
  },
  {
    id: "ld-the-invoice",
    title: "The Duplicate Invoice",
    situation: "Two invoices from the same supplier arrive one week apart. Both are for 'consulting services, March'. The first is for 4,800 and numbered 2211; the second is for 4,800 and numbered 2211-A. The second has a different bank account number in the payment details. The supplier's usual contact is on leave, according to an out-of-office reply. The second invoice's email came from the supplier's domain, but the display name has a typo.",
    observations: [
      { text: "Same amount, same description, numbers 2211 and 2211-A", keywords: ["same amount", "4,800", "2211", "2211-a"] },
      { text: "Different bank account on the second invoice", keywords: ["bank account", "different account", "payment details"] },
      { text: "Usual contact on leave", keywords: ["on leave", "out-of-office", "out of office"] },
      { text: "Second email from the supplier's domain with a typo in the display name", keywords: ["display name", "typo", "domain"] },
    ],
    inferences: [
      { text: "The second invoice may be a payment-diversion attempt", keywords: ["fraud", "diversion", "scam", "phishing", "diverted"] },
      { text: "Someone knows the contact is away", keywords: ["knows", "away", "timing"] },
    ],
    alternatives: [
      { text: "A legitimate corrected invoice from a colleague covering leave, with a new account", keywords: ["legitimate", "corrected", "colleague", "genuine", "new account"] },
      { text: "The supplier changed banks and reissued", keywords: ["changed banks", "reissued", "switched"] },
    ],
    debrief: "The observations are unambiguous; the inference is probable but not certain. The correct action is to verify the account by a channel you already trust, which is the same action under every hypothesis. Sometimes the decision does not require the inference to be resolved.",
    difficulty: 4,
  },
  {
    id: "ld-the-garden",
    title: "The Garden in October",
    situation: "A neighbour's garden, usually immaculate, has grass three weeks overgrown. The bins have not been put out for two collections. Post is visible through the door's glass panel. A light is on in an upstairs room at 2pm. A car that is normally in the drive is absent. A second neighbour says they saw a taxi collect a suitcase 'a while ago'.",
    observations: [
      { text: "Grass overgrown about three weeks", keywords: ["grass", "overgrown", "three weeks", "lawn"] },
      { text: "Bins not out for two collections", keywords: ["bins", "collections", "not put out"] },
      { text: "Post visible inside the door", keywords: ["post", "mail", "letters"] },
      { text: "Upstairs light on in the afternoon", keywords: ["light on", "upstairs", "2pm", "afternoon"] },
      { text: "Car absent; taxi with suitcase reported", keywords: ["car", "taxi", "suitcase", "absent", "drive"] },
    ],
    inferences: [
      { text: "The occupant has been away for roughly three weeks", keywords: ["away", "three weeks", "travelling", "holiday"] },
      { text: "The departure was planned enough to involve a suitcase and a taxi", keywords: ["planned", "suitcase", "taxi"] },
    ],
    alternatives: [
      { text: "Hospital stay or family emergency rather than travel", keywords: ["hospital", "emergency", "ill", "family"] },
      { text: "The light is on a timer for security", keywords: ["timer", "security", "automatic"] },
      { text: "The occupant is home but unwell", keywords: ["home", "unwell", "inside"] },
    ],
    debrief: "Every observation is consistent with absence. None distinguishes a holiday from an emergency. The light on a timer is the sort of detail people over-read; it supports planned absence but weakly. A good next step is a question, not a conclusion.",
    difficulty: 3,
  },
  {
    id: "ld-the-cafe-table",
    title: "The Table by the Window",
    situation: "In a cafe, a table has two cups: one empty with a lipstick mark, one three-quarters full and no longer steaming. A folded newspaper is open at the crossword, half done in pen. One chair is pushed in, the other angled outward. A phone lies face down beside the fuller cup. A receipt shows two flat whites at 10:14; the wall clock reads 10:58.",
    observations: [
      { text: "Two cups: one empty with lipstick, one three-quarters full, not steaming", keywords: ["two cups", "lipstick", "three-quarters", "not steaming", "empty cup"] },
      { text: "Crossword half done in pen", keywords: ["crossword", "pen", "half done", "newspaper"] },
      { text: "One chair pushed in, one angled out", keywords: ["chair", "pushed in", "angled"] },
      { text: "Phone face down by the fuller cup", keywords: ["phone", "face down"] },
      { text: "Receipt 10:14, clock 10:58", keywords: ["10:14", "10:58", "receipt", "clock", "forty"] },
    ],
    inferences: [
      { text: "Two people sat here; one has left or stepped away", keywords: ["two people", "one left", "stepped away", "gone"] },
      { text: "The remaining drink was abandoned or its owner is nearby", keywords: ["abandoned", "nearby", "coming back", "bathroom"] },
      { text: "They have been here at least forty minutes", keywords: ["forty", "44", "minutes", "at least"] },
    ],
    alternatives: [
      { text: "One person ordered two drinks for a friend who never came", keywords: ["never came", "one person", "no-show", "waiting"] },
      { text: "The phone owner is at the counter or the bathroom and will return", keywords: ["counter", "bathroom", "return", "ordering"] },
    ],
    debrief: "The phone face down beside the fuller cup is the detail that argues for a return: people rarely leave phones. The cups tell you about timing; the chairs tell you about manner of leaving. Nothing here tells you about mood, and it should not.",
    difficulty: 2,
  },
  {
    id: "ld-the-startup-metrics",
    title: "The Board Deck",
    situation: "A startup's board deck shows monthly revenue up 40% quarter on quarter. The chart's y-axis starts at 180,000. Customer count is reported as 'over 300'. A footnote defines revenue as 'contracted annual value recognised monthly'. Churn is not shown. The CEO's summary says 'the market is pulling us forward'. Headcount grew from 22 to 41.",
    observations: [
      { text: "Revenue up 40% quarter on quarter; axis starts at 180,000", keywords: ["40%", "axis", "180,000", "truncated", "y-axis"] },
      { text: "Customers reported as 'over 300'", keywords: ["over 300", "customers", "vague"] },
      { text: "Revenue defined as contracted annual value recognised monthly", keywords: ["contracted", "annual value", "recognised", "footnote", "definition"] },
      { text: "Churn not shown", keywords: ["churn", "not shown", "missing"] },
      { text: "Headcount 22 to 41", keywords: ["headcount", "22", "41", "hiring"] },
    ],
    inferences: [
      { text: "Growth may be smaller than the chart suggests", keywords: ["smaller", "exaggerated", "less than", "overstated"] },
      { text: "Revenue is a booking metric, not cash", keywords: ["bookings", "not cash", "contracted", "recognition"] },
      { text: "Costs roughly doubled", keywords: ["costs", "doubled", "burn"] },
    ],
    alternatives: [
      { text: "The growth is real and the presentation is merely conventional", keywords: ["real", "conventional", "standard practice", "genuine"] },
      { text: "Churn is omitted because it is low, not because it is high", keywords: ["low churn", "omitted", "not a problem"] },
    ],
    debrief: "Nothing here proves the numbers are misleading. The observations establish what is not shown and how what is shown is defined. The ladder's value is in refusing to let the summary sentence do your inferring for you.",
    difficulty: 5,
  },
  {
    id: "ld-the-museum-label",
    title: "The Museum Label",
    situation: "A small oil painting in a regional museum is labelled 'Circle of Rembrandt, c. 1640'. The frame is 19th-century. The label was updated in 2019 from 'Attributed to Rembrandt'. A conservation note in the catalogue mentions 'later overpaint removed, 2018'. The museum acquired the work by bequest in 1931. A visiting scholar's blog post argues it is by a specific pupil.",
    observations: [
      { text: "Label: 'Circle of Rembrandt, c. 1640', downgraded in 2019 from 'Attributed to'", keywords: ["circle of", "attributed", "2019", "label", "downgraded"] },
      { text: "Frame is 19th-century", keywords: ["frame", "19th", "nineteenth"] },
      { text: "Overpaint removed in 2018", keywords: ["overpaint", "2018", "conservation", "cleaned"] },
      { text: "Bequest, 1931", keywords: ["bequest", "1931", "acquired"] },
      { text: "A scholar's blog attributes it to a pupil", keywords: ["blog", "scholar", "pupil", "attribut"] },
    ],
    inferences: [
      { text: "The conservation revealed something that weakened the attribution", keywords: ["revealed", "weakened", "cleaning changed", "after cleaning"] },
      { text: "The museum is being cautious rather than claiming", keywords: ["cautious", "conservative", "careful"] },
    ],
    alternatives: [
      { text: "The relabelling followed a scholarly consensus shift unrelated to the cleaning", keywords: ["consensus", "scholarship", "unrelated", "rembrandt research"] },
      { text: "The cleaning revealed higher quality and the museum is awaiting a formal opinion", keywords: ["higher quality", "awaiting", "opinion", "upgrade"] },
    ],
    debrief: "The sequence (cleaning 2018, relabel 2019) is suggestive, but sequence is not cause. Two readings fit equally. The honest confidence here is moderate at best, and 'what would change my mind' is a technical report.",
    difficulty: 5,
  },
  {
    id: "ld-the-team-chat",
    title: "The Group Chat",
    situation: "In a team chat, a message at 17:40 from the project lead reads 'Let's discuss tomorrow.' Four people react with a thumbs-up within a minute. One person, usually quick to react, does not. At 17:55 that person posts in a different channel about an unrelated topic. The next morning's meeting starts without them; they join eleven minutes late saying 'sorry, trains'.",
    observations: [
      { text: "Lead's message at 17:40; four thumbs-up within a minute", keywords: ["17:40", "thumbs", "four", "reacted"] },
      { text: "One usually-quick person did not react", keywords: ["did not react", "no reaction", "didn't react"] },
      { text: "Same person posted elsewhere at 17:55", keywords: ["17:55", "different channel", "posted elsewhere"] },
      { text: "Joined the meeting eleven minutes late citing trains", keywords: ["eleven", "late", "trains", "11 minutes"] },
    ],
    inferences: [
      { text: "They saw the message and chose not to react", keywords: ["saw", "chose", "deliberately", "ignored"] },
      { text: "Something about the discussion topic may be uncomfortable for them", keywords: ["uncomfortable", "avoid", "reluctant"] },
    ],
    alternatives: [
      { text: "They were online but did not see that channel", keywords: ["did not see", "didn't see", "missed", "notifications"] },
      { text: "The train excuse is simply true", keywords: ["trains", "true", "genuine delay"] },
      { text: "They dislike reacting with emoji", keywords: ["never react", "habit", "doesn't use"] },
    ],
    debrief: "This is the ladder at its most dangerous. Every observation is real; the inference about discomfort is a story. The honest confidence is low, and the correct next move is a neutral question, not a theory.",
    difficulty: 4,
  },
  {
    id: "ld-the-shop-window",
    title: "The Shop That Closed",
    situation: "A bakery on a busy street has a handwritten sign: 'Closed for refurbishment. Back soon!' The sign's paper is yellowed and curling. Through the window, the display shelves are empty but the ovens are visible and intact. A planning notice on the lamppost outside is for 'change of use, A1 to A3'. A rival bakery opened two streets away four months ago.",
    observations: [
      { text: "Handwritten 'closed for refurbishment' sign, yellowed and curling", keywords: ["sign", "yellowed", "curling", "refurbishment", "handwritten"] },
      { text: "Shelves empty; ovens visible and intact", keywords: ["shelves empty", "ovens", "intact"] },
      { text: "Planning notice: change of use A1 to A3", keywords: ["planning", "change of use", "a1", "a3", "notice"] },
      { text: "Rival bakery opened nearby four months ago", keywords: ["rival", "four months", "competitor", "two streets"] },
    ],
    inferences: [
      { text: "The closure has lasted longer than 'back soon' implies", keywords: ["longer", "months", "not soon", "long time"] },
      { text: "The premises are changing to a restaurant or cafe use", keywords: ["restaurant", "cafe", "change of use", "different business"] },
    ],
    alternatives: [
      { text: "The same owner is converting the bakery into a cafe", keywords: ["same owner", "converting", "own cafe"] },
      { text: "The notice refers to a neighbouring unit", keywords: ["neighbouring", "next door", "another unit"] },
      { text: "The sign is old but a genuine refurbishment is still coming", keywords: ["genuine", "still coming", "delayed refurbishment"] },
    ],
    debrief: "The planning notice is documentary evidence; the rival bakery is a tempting narrative. The ladder should weight the document above the story, while noticing that the notice's address needs checking.",
    difficulty: 3,
  },
];

/* ---------------- Causal reasoning ---------------- */
export const CAUSAL: CausalChallenge[] = [
  {
    id: "ca-hospital-mortality",
    title: "Hospital and Mortality",
    claim: "Patients treated at the region's largest hospital have a higher mortality rate than those treated at small local hospitals. Therefore the large hospital provides worse care.",
    context: "The large hospital houses the region's trauma centre and takes referrals of the most difficult cases from the small hospitals.",
    options: [
      { id: "a", text: "The claim is sound: higher mortality indicates worse care.", correct: false, why: "It ignores who is treated where.", errorType: "CAUSAL_ERROR" },
      { id: "b", text: "Selection: the large hospital receives sicker patients, so raw mortality cannot be compared.", correct: true, why: "Case mix is the confounder. Risk-adjusted outcomes are needed before any inference about care quality." },
      { id: "c", text: "Small hospitals under-report deaths.", correct: false, why: "Possible but unsupported; it is an assumption introduced to rescue the comparison.", errorType: "ASSUMPTION" },
      { id: "d", text: "The difference is too small to matter.", correct: false, why: "No magnitude was given; this dodges the question.", errorType: "PRECISION" },
    ],
    debrief: "Whenever groups are compared, ask how people ended up in each group. Referral pathways sort patients by severity before any treatment happens.",
    difficulty: 3,
  },
  {
    id: "ca-reading-shoes",
    title: "Shoe Size and Reading",
    claim: "Among schoolchildren, larger shoe size is strongly correlated with better reading ability. Bigger feet help children read.",
    context: "The sample includes children aged five to eleven.",
    options: [
      { id: "a", text: "Growth causes both: age is the hidden variable.", correct: true, why: "Older children have bigger feet and read better. Age confounds the relationship completely." },
      { id: "b", text: "Reading practice stimulates growth.", correct: false, why: "Reverse causation with no plausible mechanism.", errorType: "CAUSAL_ERROR" },
      { id: "c", text: "The correlation is a coincidence.", correct: false, why: "A strong correlation across a large sample is unlikely to be chance; it has a cause, just not the claimed one.", errorType: "CAUSAL_ERROR" },
      { id: "d", text: "Bigger children are more confident and so read more.", correct: false, why: "Invents a mechanism when a simpler confounder is available.", errorType: "ASSUMPTION" },
    ],
    debrief: "A correlation can be real, strong and entirely explained by a third variable. The first question is always: what else varies with both?",
    difficulty: 2,
  },
  {
    id: "ca-regression-coach",
    title: "The Coach's Reprimand",
    claim: "After a pilot's unusually bad landing, the instructor shouts at them; the next landing is better. After an unusually good landing, the instructor praises them; the next is worse. So criticism works and praise backfires.",
    context: "Landing quality varies from attempt to attempt around each pilot's average.",
    options: [
      { id: "a", text: "Criticism improves performance and praise reduces it.", correct: false, why: "The observed pattern would occur with no feedback at all.", errorType: "CAUSAL_ERROR" },
      { id: "b", text: "Regression to the mean: extreme performances tend to be followed by more average ones regardless of feedback.", correct: true, why: "An unusually bad landing is partly bad luck; the next is likely to be closer to the pilot's average. The feedback is along for the ride." },
      { id: "c", text: "Pilots try harder after being shouted at.", correct: false, why: "Possibly, but the pattern does not require it; you cannot infer it from these observations.", errorType: "ASSUMPTION" },
      { id: "d", text: "Praise makes pilots complacent.", correct: false, why: "A story fitted to the pattern; unsupported.", errorType: "ASSUMPTION" },
    ],
    debrief: "Regression to the mean is the most common way an intervention gets credit it did not earn. Anything applied after an extreme will look effective.",
    difficulty: 4,
  },
  {
    id: "ca-survivorship-founders",
    title: "The Dropout Founders",
    claim: "Many famous company founders dropped out of university. Dropping out of university increases your chances of building a great company.",
    context: "You have read about a dozen famous founders.",
    options: [
      { id: "a", text: "Survivorship: you only hear about the dropouts who succeeded, not the many who did not.", correct: true, why: "The sample is selected on the outcome. The dropouts who failed are invisible." },
      { id: "b", text: "University teaches conformity that hinders founders.", correct: false, why: "A mechanism supplied to fit the anecdotes.", errorType: "ASSUMPTION" },
      { id: "c", text: "Famous founders are simply exceptional; university is irrelevant.", correct: false, why: "Closer, but it does not identify the selection problem in the evidence.", errorType: "CAUSAL_ERROR" },
      { id: "d", text: "The claim is correct because the examples are so prominent.", correct: false, why: "Prominence is exactly what biases the sample.", errorType: "BASE_RATE_NEGLECT" },
    ],
    debrief: "Ask how the examples reached you. If the process that selected them depends on the outcome, the examples cannot tell you about the cause.",
    difficulty: 3,
  },
  {
    id: "ca-simpson-admissions",
    title: "The Admissions Paradox",
    claim: "A university admits 44% of male applicants and 35% of female applicants. Yet within each department, women are admitted at equal or higher rates than men. This is impossible, so the department figures must be wrong.",
    context: "Departments differ greatly in how selective they are and in how many applicants of each sex they receive.",
    options: [
      { id: "a", text: "The department figures must contain an error.", correct: false, why: "Both sets of figures can be simultaneously true.", errorType: "CAUSAL_ERROR" },
      { id: "b", text: "Simpson's paradox: women applied more often to the most selective departments, so the aggregate rate falls even though each department treats them at least equally.", correct: true, why: "Aggregating across groups of different sizes and different base rates can reverse the within-group direction." },
      { id: "c", text: "The overall figure is the only one that matters.", correct: false, why: "The aggregate hides the mechanism; which figure matters depends on the question being asked.", errorType: "PRECISION" },
      { id: "d", text: "Men are more likely to apply in the first place.", correct: false, why: "Irrelevant to admission rates conditional on applying.", errorType: "ASSUMPTION" },
    ],
    debrief: "When an aggregate contradicts every subgroup, look at how applicants are distributed across subgroups. Neither figure is wrong; they answer different questions.",
    difficulty: 6,
  },
  {
    id: "ca-ice-cream",
    title: "Ice Cream and Drowning",
    claim: "Months with high ice-cream sales have more drownings. Ice cream causes drowning, perhaps by cramps after eating.",
    context: "Both series are monthly and national.",
    options: [
      { id: "a", text: "A common cause: warm weather increases both swimming and ice-cream sales.", correct: true, why: "Season drives both variables. Neither causes the other." },
      { id: "b", text: "Drownings drive people to comfort-eat ice cream.", correct: false, why: "Reverse causation without plausibility.", errorType: "CAUSAL_ERROR" },
      { id: "c", text: "The old cramp theory is correct.", correct: false, why: "The cramp claim itself is unsupported; and the correlation does not test it.", errorType: "ASSUMPTION" },
      { id: "d", text: "The data are too coarse to say anything.", correct: false, why: "They say something: that a confounder is at work.", errorType: "PRECISION" },
    ],
    debrief: "The classic example, still worth one pass. The lesson is not 'correlation isn't causation' but 'find the third variable'.",
    difficulty: 1,
  },
  {
    id: "ca-mentoring",
    title: "The Mentoring Programme",
    claim: "Employees who joined the voluntary mentoring programme were promoted twice as often as those who did not. The programme doubles promotion chances.",
    context: "Joining was voluntary and required a manager's nomination.",
    options: [
      { id: "a", text: "The programme is highly effective.", correct: false, why: "It ignores how people entered the programme.", errorType: "CAUSAL_ERROR" },
      { id: "b", text: "Selection: those nominated and choosing to join were already the more ambitious, better-regarded employees.", correct: true, why: "Both nomination and volunteering select for the traits that predict promotion. The programme's own effect is unknown." },
      { id: "c", text: "Mentors lobby for their mentees, which is unfair but real.", correct: false, why: "A possible mechanism for a real effect, but the comparison cannot establish any effect.", errorType: "ASSUMPTION" },
      { id: "d", text: "The non-joiners were discriminated against.", correct: false, why: "Nothing supports this.", errorType: "ASSUMPTION" },
    ],
    debrief: "Voluntary programmes almost always look effective because the people who volunteer differ. Random assignment, or at least a comparison of nominees who did not join, is needed.",
    difficulty: 3,
  },
  {
    id: "ca-crime-police",
    title: "Police and Crime",
    claim: "Cities with more police officers per capita have more recorded crime. Police cause crime, or at least do not prevent it.",
    context: "Police numbers are set by city budgets responding to crime levels; recording depends on police presence.",
    options: [
      { id: "a", text: "Reverse causation and measurement: high crime leads to more hiring, and more officers record more of the crime that exists.", correct: true, why: "Two effects run in the wrong direction for the claim: cities respond to crime with police, and police presence increases recording." },
      { id: "b", text: "Police are ineffective.", correct: false, why: "Cannot be concluded from a cross-section where police levels respond to crime.", errorType: "CAUSAL_ERROR" },
      { id: "c", text: "Bigger cities have both.", correct: false, why: "Per-capita figures already adjust for size.", errorType: "PRECISION" },
      { id: "d", text: "The data must be fabricated.", correct: false, why: "No basis.", errorType: "ASSUMPTION" },
    ],
    debrief: "When the supposed cause is itself a response to the effect, cross-sectional correlations say little. Look for natural experiments or timing.",
    difficulty: 4,
  },
  {
    id: "ca-coincidence-dreams",
    title: "The Prophetic Dream",
    claim: "You dreamt about an old friend and they called the next day. Dreams can predict events.",
    context: "You have hundreds of dreams a year and dozens of old friends.",
    options: [
      { id: "a", text: "Coincidence: with many dreams and many friends, some matches are expected by chance, and the misses are forgotten.", correct: true, why: "The number of opportunities for a match is huge; the memorable hit is the one that survived." },
      { id: "b", text: "The friend sensed you thinking about them.", correct: false, why: "A mechanism with no support.", errorType: "ASSUMPTION" },
      { id: "c", text: "You unconsciously knew they would call.", correct: false, why: "Possible in principle if cues existed, but the simpler explanation is chance.", errorType: "CAUSAL_ERROR" },
      { id: "d", text: "This is one data point; it proves nothing either way, so the claim stands.", correct: false, why: "One point does not support the claim; the burden runs the other way.", errorType: "BASE_RATE_NEGLECT" },
    ],
    debrief: "Count the opportunities. Rare coincidences are common when there are many chances for them and the failures are not recorded.",
    difficulty: 2,
  },
  {
    id: "ca-remote-productivity",
    title: "Remote Work and Output",
    claim: "In the year the company allowed remote work, output per employee rose 9%. Remote work raised productivity.",
    context: "In the same year the company retired an old software system, cut its least profitable product line, and lost its lowest-performing 8% of staff to a rival.",
    options: [
      { id: "a", text: "Remote work raised productivity by 9%.", correct: false, why: "Several other changes coincided.", errorType: "CAUSAL_ERROR" },
      { id: "b", text: "Multiple concurrent changes: system retirement, product mix and workforce composition each could explain part or all of the rise.", correct: true, why: "With four simultaneous changes and one outcome, the effect of any one cannot be isolated from this observation." },
      { id: "c", text: "Losing weak staff explains all of it.", correct: false, why: "Plausibly a large part, but claiming all of it is the same error in the other direction.", errorType: "PRECISION" },
      { id: "d", text: "Productivity gains are always temporary, so this means nothing.", correct: false, why: "An unsupported generalisation.", errorType: "ASSUMPTION" },
    ],
    debrief: "Before-and-after comparisons are only informative when one thing changed. List everything that changed, then ask what would isolate the effect you care about.",
    difficulty: 4,
  },
];

/* ---------------- Fast, then Slow ---------------- */
export const FAST_SLOW: FastSlowChallenge[] = [
  {
    id: "fs-ticket-pen",
    title: "The Ticket and the Pen",
    question: "A concert ticket and a pen cost 1.10 together. The ticket costs 1.00 more than the pen. How much is the pen?",
    options: [{ id: "a", text: "0.10" }, { id: "b", text: "0.05" }, { id: "c", text: "0.15" }, { id: "d", text: "1.00" }],
    correct: "b",
    fastSeconds: 12,
    explanation: "If the pen were 0.10, the ticket would be 1.10 and the pair 1.20. The pen is 0.05, the ticket 1.05. The intuitive answer is produced by subtracting 1.00 from 1.10 without checking.",
    domain: "quantitative",
    difficulty: 2,
  },
  {
    id: "fs-lily-pads",
    title: "The Lily Pond",
    question: "A patch of lily pads doubles in size every day. It covers the whole pond on day 48. On which day did it cover half the pond?",
    options: [{ id: "a", text: "Day 24" }, { id: "b", text: "Day 47" }, { id: "c", text: "Day 46" }, { id: "d", text: "Day 12" }],
    correct: "b",
    fastSeconds: 12,
    explanation: "Doubling means half the pond is one day before full. The fast answer halves the number of days instead of reasoning about the process.",
    domain: "quantitative",
    difficulty: 2,
  },
  {
    id: "fs-linda",
    title: "The Cautious Accountant",
    question: "Mara is 34, studied philosophy, and volunteers at a debating society. Which is more probable?",
    options: [{ id: "a", text: "Mara is an accountant" }, { id: "b", text: "Mara is an accountant who is active in a political party" }, { id: "c", text: "They are equally probable" }, { id: "d", text: "It cannot be determined" }],
    correct: "a",
    fastSeconds: 12,
    explanation: "A conjunction can never be more probable than one of its parts. Every accountant active in politics is an accountant; the reverse does not hold. The description's fit to option B is what pulls intuition the wrong way.",
    domain: "inference",
    difficulty: 3,
  },
  {
    id: "fs-wason",
    title: "The Four Cards",
    question: "Four cards show A, K, 4, 7. Each has a letter on one side and a number on the other. Rule: if a card has a vowel on one side, it has an even number on the other. Which cards must you turn to test the rule?",
    options: [{ id: "a", text: "A and 4" }, { id: "b", text: "A and 7" }, { id: "c", text: "A only" }, { id: "d", text: "A, 4 and 7" }],
    correct: "b",
    fastSeconds: 12,
    explanation: "A vowel with an odd number would break the rule, so turn A (a vowel) and 7 (an odd number that might hide a vowel). Turning 4 cannot falsify anything: the rule says nothing about what sits behind an even number.",
    domain: "inference",
    difficulty: 4,
  },
  {
    id: "fs-framing-disease",
    title: "Two Programmes",
    question: "An outbreak threatens 600 people. Programme A saves 200 for certain. Programme B saves all 600 with probability one third, and no one with probability two thirds. Programme C: 400 die for certain. Programme D: no one dies with probability one third, 600 die with probability two thirds. Which statement is true?",
    options: [{ id: "a", text: "A and C describe the same outcome; B and D describe the same outcome" }, { id: "b", text: "A is safer than C" }, { id: "c", text: "B has a higher expected value than D" }, { id: "d", text: "C is the worst option" }],
    correct: "a",
    fastSeconds: 12,
    explanation: "Saving 200 of 600 is the same as 400 dying; the gambles are likewise identical. The framing (lives saved versus lives lost) reliably flips people's preferences even though nothing changed.",
    domain: "inference",
    difficulty: 4,
  },
  {
    id: "fs-machines",
    title: "The Machines",
    question: "If 5 machines take 5 minutes to make 5 widgets, how long would 100 machines take to make 100 widgets?",
    options: [{ id: "a", text: "100 minutes" }, { id: "b", text: "5 minutes" }, { id: "c", text: "20 minutes" }, { id: "d", text: "1 minute" }],
    correct: "b",
    fastSeconds: 12,
    explanation: "Each machine makes one widget in five minutes. A hundred machines make a hundred widgets in the same five minutes. The fast answer pattern-matches the numbers instead of the rate.",
    domain: "quantitative",
    difficulty: 2,
  },
  {
    id: "fs-anchoring-population",
    title: "The Anchor",
    question: "You were just told a colleague guessed that the Ottoman Empire lasted 'about 900 years'. Without looking anything up, roughly how long did it last, from founding around 1299 to abolition in 1922?",
    options: [{ id: "a", text: "About 620 years" }, { id: "b", text: "About 900 years" }, { id: "c", text: "About 450 years" }, { id: "d", text: "About 1,100 years" }],
    correct: "a",
    fastSeconds: 12,
    explanation: "1922 minus 1299 is 623. The colleague's number is an anchor; the question even supplied the dates, and the fast pass often still drifts toward 900.",
    domain: "knowledge",
    difficulty: 2,
  },
  {
    id: "fs-two-children",
    title: "The Two Children",
    question: "A family has two children. You learn that at least one is a boy. What is the probability that both are boys, assuming boy and girl are equally likely and independent?",
    options: [{ id: "a", text: "One half" }, { id: "b", text: "One third" }, { id: "c", text: "One quarter" }, { id: "d", text: "Two thirds" }],
    correct: "b",
    fastSeconds: 12,
    explanation: "The four equally likely families are BB, BG, GB, GG. 'At least one boy' rules out GG, leaving three, of which one is BB. The fast answer treats the known boy as a specific child, which would make it one half.",
    domain: "quantitative",
    difficulty: 5,
  },
  {
    id: "fs-sunk-cost",
    title: "The Half-Watched Film",
    question: "You paid for a cinema ticket and after forty minutes the film is dull. Nothing you do can recover the money. What should decide whether you stay?",
    options: [{ id: "a", text: "Whether the remaining film is worth your next hour more than the alternatives" }, { id: "b", text: "The ticket price" }, { id: "c", text: "How much of the film you have already seen" }, { id: "d", text: "Whether leaving would look rude" }],
    correct: "a",
    fastSeconds: 12,
    explanation: "The ticket is a sunk cost. Only the future matters: the remaining film against whatever else you could do. The forty minutes already spent pull intuition toward staying.",
    domain: "strategy",
    difficulty: 2,
  },
  {
    id: "fs-availability-flights",
    title: "The Dangerous Journey",
    question: "After a widely reported air crash, a friend decides to drive 600 miles instead of flying, for safety. Per mile travelled, which is more dangerous for an ordinary passenger?",
    options: [{ id: "a", text: "Driving" }, { id: "b", text: "Flying" }, { id: "c", text: "They are about the same" }, { id: "d", text: "It depends entirely on the airline" }],
    correct: "a",
    fastSeconds: 12,
    explanation: "Commercial aviation has far fewer deaths per passenger-mile than driving. A vivid, recent crash raises the felt probability of flying deaths; the availability heuristic is doing the reasoning.",
    domain: "inference",
    difficulty: 3,
  },
];
