import type { StrategyScenario } from "@/lib/domain/types";

/** Strategy Table scenarios 6–10. */
export const STRATEGY_B: StrategyScenario[] = [
  {
    id: "st-exclusivity",
    title: "The First Big Customer",
    mode: "story",
    setting: "A four-person startup's first negotiation with a large enterprise customer, over three weeks.",
    summary: "A logistics company with 3,000 staff wants to buy your scheduling software: a 240,000 annual contract, ten times your current revenue. Their procurement lead asks for exclusivity in the logistics sector for three years, a 30% discount, and source-code escrow. You have four months of runway.",
    actors: [
      { name: "You (founder)", goals: ["Close the deal", "Keep the company sellable to others", "Survive"], constraints: ["Four months of runway", "No lawyer on retainer"], leverage: ["They have already run a successful pilot", "Their ops director champions you"], fears: ["Losing the deal", "Signing away the market"], alternatives: ["Raise a bridge round", "Smaller customers", "Walk away"] },
      { name: "Procurement lead", goals: ["Get every concession his checklist allows", "Show savings against the pilot price"], constraints: ["Does not own the budget", "Measured on discounts obtained"], leverage: ["The size of the contract", "Your visible urgency"], fears: ["A vendor collapsing mid-contract (hence escrow)"], alternatives: ["An incumbent's inferior module", "Delay"] },
      { name: "Operations director (champion)", goals: ["Get the software live before peak season", "Stop the pilot from expiring"], constraints: ["Cannot override procurement", "Under pressure on peak season"], leverage: ["Owns the budget", "Can escalate"], fears: ["A four-month delay into peak"], alternatives: ["Extend the pilot informally"] },
    ],
    rootNodeId: "n1",
    difficulty: 5,
    estimatedMinutes: 12,
    subskills: ["strategy.negotiation", "strategy.optionality", "strategy.incentives", "strategy.second_order", "social.incentive_recognition"],
    conceptLinks: ["game-theory", "dutch-east-india-company"],
    origin: "seeded",
    nodes: [
      {
        id: "n1",
        situation: "The term sheet arrives: 30% discount, three-year sector exclusivity, source-code escrow, net-90 payment. Procurement asks for a reply within a week.",
        moves: [
          { id: "m1", text: "Accept the terms. The revenue solves the runway problem.", quality: 0.15, consequence: "It does, for a year. Then an investor's lawyer finds the exclusivity clause and the round stalls: you have signed away your largest market. Net-90 means the first cash arrives in month four, one week before the runway ends.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n6" },
          { id: "m2", text: "Reject exclusivity flatly and hold the price.", quality: 0.4, consequence: "Procurement reads it as inexperience and stalls. The champion, who needs go-live before peak, is now caught between you and his own procurement team.", nextNodeId: "n3" },
          { id: "m3", text: "Ask the champion, separately, what each term is for: who wants exclusivity, who wants escrow, and what the real deadline is.", quality: 0.9, consequence: "Exclusivity came from procurement's template, not from the business; the ops director does not care about it. Escrow is a genuine board requirement because a supplier once folded. The real deadline is go-live eight weeks before peak, which is nine weeks away.", reveals: "Exclusivity is a template term nobody in the business wants; escrow is a real fear; the deadline is theirs, not yours.", nextNodeId: "n2" },
          { id: "m4", text: "Tell procurement you have other interested customers and need to consider.", quality: 0.3, consequence: "You do not, and he suspects it. Bluffs cost credibility with people who negotiate for a living.", errorType: "ASSUMPTION", nextNodeId: "n3" },
        ],
      },
      {
        id: "n2",
        situation: "You know exclusivity is a template term, escrow is a real need, and their deadline is nine weeks. Procurement is waiting.",
        moves: [
          { id: "m1", text: "Counter: no sector exclusivity, but a twelve-month 'most favoured customer' clause on price; escrow agreed via a standard third-party service; a 15% discount in exchange for annual payment in advance; signature this month to hit their go-live.", quality: 0.95, consequence: "Procurement gets three concessions to report (MFC, escrow, discount); the business gets its date; you get cash in month one instead of month four and keep the market. The champion pushes it through in nine days.", counterpartyReply: "Procurement: 'If escrow and MFC are in, I can live without the sector clause.'", nextNodeId: "n5" },
          { id: "m2", text: "Offer exclusivity for one year instead of three, keep the 30% discount.", quality: 0.45, consequence: "Better than three years, but you have conceded the principle and the price for a term nobody on their side needed. The one-year clause still appears in your next investor's diligence.", nextNodeId: "n4" },
          { id: "m3", text: "Go over procurement's head to the ops director and ask him to force the deal through.", quality: 0.3, consequence: "He tries; procurement digs in on principle; the deal takes eleven weeks and closes with exclusivity intact because you never addressed it.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n4" },
        ],
      },
      {
        id: "n3",
        situation: "The deal has stalled. Runway is down to three months. The champion wants to help but needs something to take to procurement.",
        moves: [
          { id: "m1", text: "Give the champion a package he can sell internally: escrow, a modest discount for prepayment, no exclusivity, with a one-page rationale.", quality: 0.8, consequence: "He takes it to procurement with the peak-season deadline attached. The deal closes in three weeks on those terms.", nextNodeId: "n5" },
          { id: "m2", text: "Concede exclusivity to get it done.", quality: 0.25, consequence: "It closes. Eighteen months later your best prospect is a logistics firm you cannot sell to.", errorType: "PREMATURE_CLOSURE", nextNodeId: "n6" },
        ],
      },
      {
        id: "n4",
        situation: "The contract closes with some form of exclusivity and a deep discount. Runway is solved; the market is narrower.",
        moves: [],
        terminal: true,
        debrief: "A survivable deal that will cost more later than it saved now. The template exclusivity clause was never a business requirement; it survived because nobody asked whose it was. The second-order cost of exclusivity lands in the next fundraising, where clauses like this are the first thing a lawyer finds.",
      },
      {
        id: "n5",
        situation: "Signed in under three weeks: no exclusivity, escrow via a third party, a modest discount for cash up front. The customer is live before peak.",
        moves: [],
        terminal: true,
        debrief: "Separating the terms by whose interest they served turned a hostile checklist into a trade. Procurement needed concessions to report; the business needed a date; the board needed escrow; you needed cash early and a free market. Each term was cheap for the side that gave it and valuable for the side that got it. That is what a good deal looks like: not a split, but a sort.",
      },
      {
        id: "n6",
        situation: "The company survives the year and stalls the next, boxed out of its own market by a clause it did not need to sign.",
        moves: [],
        terminal: true,
        debrief: "Urgency makes every term look like the price of survival. The irreversible term (three-year exclusivity) was accepted for a reversible benefit (a year's revenue). Ask of every clause: who asked for it, what is it protecting them from, and what will it cost me in the round after this one?",
      },
    ],
  },
  {
    id: "st-museum-loan",
    title: "The Loaned Object",
    mode: "premortem",
    setting: "A regional museum, eighteen months from now. Assume the plan has failed publicly. Work backwards.",
    summary: "The museum plans to borrow a celebrated carved panel from a national collection abroad for a six-month exhibition. The panel was acquired in the 1890s under circumstances now contested by a community in its country of origin. The director is enthusiastic; the board is nervous. Imagine it is eighteen months later and the exhibition has become a public controversy. Why?",
    actors: [
      { name: "Museum director", goals: ["A landmark exhibition", "Visitor numbers", "Reputation for ambition"], constraints: ["A cautious board", "A small communications team"], leverage: ["The lending relationship"], fears: ["A cancelled show", "Being called naive"], alternatives: ["A different object", "A co-curated show", "Postpone"] },
      { name: "The lending institution", goals: ["Lend on standard terms", "Avoid becoming the story"], constraints: ["Its own restitution review is ongoing"], leverage: ["Owns the object"], fears: ["A precedent"], alternatives: ["Withdraw the loan"] },
      { name: "The community of origin", goals: ["Recognition of the object's history", "A voice in how it is shown", "Possibly return"], constraints: ["Far away; few resources"], leverage: ["Moral authority", "Media interest"], fears: ["Being ignored again"], alternatives: ["Public campaign", "Dialogue", "Legal challenge"] },
      { name: "The board", goals: ["No scandal", "Solvency"], constraints: ["Meets quarterly"], leverage: ["Approval"], fears: ["Donor flight"], alternatives: ["Veto"] },
    ],
    rootNodeId: "n1",
    difficulty: 5,
    estimatedMinutes: 12,
    subskills: ["strategy.adversarial", "strategy.second_order", "social.perspective", "strategy.planning", "social.incentive_recognition"],
    conceptLinks: ["rosetta-stone", "diplomatic-immunity"],
    origin: "seeded",
    nodes: [
      {
        id: "n1",
        situation: "Pre-mortem. It is eighteen months on and the exhibition is a controversy on the front page. Which failure was the most likely first cause?",
        moves: [
          { id: "m1", text: "The community of origin learned of the exhibition from the press release and launched a campaign.", quality: 0.9, consequence: "The most probable failure: an affected party finds out last. Their statement is reasonable and quotable; the museum's reply, drafted in a hurry, sounds defensive. The lender, fearing a precedent, withdraws the loan three weeks before opening.", reveals: "The first cause was sequencing: the people with the strongest moral claim were the last to hear.", nextNodeId: "n2" },
          { id: "m2", text: "A protester damaged the panel.", quality: 0.3, consequence: "Vivid, rare, and not the first cause. Damage follows controversy; it does not start it. Pre-mortems that begin with the dramatic event miss the mundane failure that made it possible.", errorType: "BASE_RATE_NEGLECT", nextNodeId: "n2" },
          { id: "m3", text: "The board vetoed the show late, after marketing had begun.", quality: 0.6, consequence: "Plausible, and itself a symptom: a board that vetoes late is a board that was informed late. What did it learn, and from whom?", nextNodeId: "n2" },
          { id: "m4", text: "Visitor numbers were poor and the show lost money.", quality: 0.2, consequence: "A failure, but not a controversy. You were asked why it became a public controversy, not why it was quiet.", errorType: "MISREAD", nextNodeId: "n2" },
        ],
      },
      {
        id: "n2",
        situation: "Working backwards from that failure, what should the museum have done in month one?",
        moves: [
          { id: "m1", text: "Open a conversation with the community of origin before announcing anything, and ask what an exhibition they could support would look like.", quality: 0.95, consequence: "They propose co-authored interpretation, a named community curator, and a public panel on the object's history. The lender, seeing a managed process, is reassured. The show becomes a story about how museums handle contested objects, told by the museum.", nextNodeId: "n3" },
          { id: "m2", text: "Commission a legal opinion on the loan and proceed if it is clean.", quality: 0.4, consequence: "The opinion is clean; the controversy is not legal. Legality answers a question nobody was asking.", errorType: "ASSUMPTION", nextNodeId: "n4" },
          { id: "m3", text: "Prepare a strong communications plan for the announcement.", quality: 0.35, consequence: "You have prepared to explain a decision rather than to make it well. The community's first statement still lands as a surprise.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n4" },
        ],
      },
      {
        id: "n3",
        situation: "The community is a partner in the show. The lender is reassured. The board sees a process. What is the remaining risk?",
        moves: [
          { id: "m1", text: "That co-curation raises the question of return, which the museum cannot answer for a borrowed object.", quality: 0.85, consequence: "It does. The honest answer, agreed in advance with the lender, is that the exhibition is a forum for that question, not a decision about it. Because it was anticipated, the question strengthens the show rather than ambushing it.", nextNodeId: "n5" },
          { id: "m2", text: "That donors object to the community's involvement.", quality: 0.45, consequence: "One does; most are relieved to see the museum ahead of the issue. A lower risk than it feels, but worth a conversation with the two largest donors before the announcement.", nextNodeId: "n5" },
        ],
      },
      {
        id: "n4",
        situation: "The exhibition proceeds on legal and communications footing only. The controversy arrives, as the pre-mortem predicted.",
        moves: [],
        terminal: true,
        debrief: "A pre-mortem is only useful if you act on the failure it finds. The likeliest failure here was one of sequence: the affected party heard last. Legal cover and communications plans are responses to that failure, not prevention of it. Prevention meant changing who was in the room in month one.",
      },
      {
        id: "n5",
        situation: "The exhibition opens with a community curator, a public programme on the object's history, and a lender who cites it as a model.",
        moves: [],
        terminal: true,
        debrief: "Assuming failure and asking why produced the right first move: talk to the party with the strongest claim before anyone else. Every actor's incentive pointed the same way once the process was visible. The lender feared a precedent and got a process; the board feared scandal and got a story; the community feared being ignored and got a seat. Dramatic failures were downstream of a mundane one.",
      },
    ],
  },
  {
    id: "st-two-offers",
    title: "Two Offers",
    mode: "red_team",
    setting: "A kitchen table, Sunday evening. Two job offers, both expiring Friday.",
    summary: "Offer A: a large firm, 15% more money, a clear promotion path, a role you already know how to do. Offer B: a forty-person company, less money, equity of uncertain value, a role stretching you into management. Your plan is to take B 'because growth matters more than money at this stage'. The Study attacks the plan.",
    actors: [
      { name: "You", goals: ["A career with compounding options", "Enough money not to think about money", "Work you can explain to yourself"], constraints: ["Friday", "A partner whose job is not portable"], leverage: ["Two offers", "A week"], fears: ["Choosing the comfortable option and regretting it", "Choosing the brave option and failing"], alternatives: ["Negotiate either", "Ask for more time", "Decline both"] },
      { name: "The Study (red team)", goals: ["Find the assumption the plan rests on", "Make the decision better, not different"], constraints: ["Cannot see the future"], leverage: ["Questions"], fears: ["A decision made on a slogan"], alternatives: [] },
    ],
    rootNodeId: "n1",
    difficulty: 4,
    estimatedMinutes: 10,
    subskills: ["strategy.adversarial", "inference.disconfirmation", "strategy.optionality", "strategy.planning", "composure.ambiguity"],
    conceptLinks: ["falsifiability", "availability-heuristic"],
    origin: "seeded",
    nodes: [
      {
        id: "n1",
        situation: "Red team: 'Growth matters more than money at this stage.' Which assumption underneath that sentence is doing the most work?",
        moves: [
          { id: "m1", text: "That the small company will actually give me management growth rather than a title and a mess.", quality: 0.9, consequence: "Correct target. The offer letter says 'manage a team of three'. What it does not say is whether those three exist yet, whether you have budget, or whether the founder lets managers manage. That is checkable this week.", reveals: "The growth claim is an assumption about the company, not a fact in the offer.", nextNodeId: "n2" },
          { id: "m2", text: "That money doesn't matter to me.", quality: 0.5, consequence: "Partly. The plan says 'at this stage'; the question is whether the stage lasts. A 15% gap compounds, and equity of 'uncertain value' has a base rate near zero. Worth quantifying, but it is not the assumption that decides.", nextNodeId: "n2" },
          { id: "m3", text: "That the large firm would be boring.", quality: 0.35, consequence: "An assumption about your own reaction, and one you have evidence for: you have done the role. But boredom is not what the plan claims; growth is.", nextNodeId: "n2" },
          { id: "m4", text: "There is no hidden assumption; the plan is sound.", quality: 0.1, consequence: "Every plan has one. Refusing to look is how slogans become decisions.", errorType: "CONFIRMATION_BIAS", nextNodeId: "n2" },
        ],
      },
      {
        id: "n2",
        situation: "The assumption is 'B will actually grow me'. Red team: what would you expect to be true this week if that assumption were false?",
        moves: [
          { id: "m1", text: "The founder would be vague about the team, the budget and who I report to; former managers there would have left within a year.", quality: 0.95, consequence: "Observable and checkable. Two calls to people who have left, and one direct question to the founder, would settle it before Friday. You make them. One former manager left in eight months, citing a founder who 'managed around' her.", reveals: "A former manager left within a year, citing the founder managing around her.", nextNodeId: "n3" },
          { id: "m2", text: "The salary would be low.", quality: 0.2, consequence: "The salary is already known and is not evidence about growth.", errorType: "CAUSAL_ERROR", nextNodeId: "n3" },
          { id: "m3", text: "I would feel uneasy about it.", quality: 0.25, consequence: "Feelings are data about you, not about the company. The red team asked for observables.", errorType: "ASSUMPTION", nextNodeId: "n3" },
        ],
      },
      {
        id: "n3",
        situation: "Evidence: a former manager left within a year; the founder was vague on budget. Red team: does this kill the plan, or change it?",
        moves: [
          { id: "m1", text: "It changes it. Go back to B with specific conditions: a named team, a budget line, a reporting line that is not the founder for day-to-day work. If they agree in writing, the growth claim becomes real. If not, take A and build management experience there.", quality: 0.95, consequence: "B's founder, asked precisely, agrees to two of the three and says the budget depends on a funding round. That is an honest answer that tells you the growth is conditional. You choose with the assumption tested rather than assumed.", nextNodeId: "n4" },
          { id: "m2", text: "It kills it. Take A.", quality: 0.5, consequence: "Defensible, but one departure is a small sample, and you have not asked B the question that would settle it. You may be right for the wrong reason.", errorType: "OVER_UPDATE", nextNodeId: "n4" },
          { id: "m3", text: "It changes nothing; the former manager was probably a bad fit.", quality: 0.15, consequence: "You have explained away the one piece of disconfirming evidence you found. That is the pattern the red team exists to catch.", errorType: "CONFIRMATION_BIAS", nextNodeId: "n5" },
        ],
      },
      {
        id: "n4",
        situation: "You decide with the key assumption tested. Whichever you choose, you know what you are betting on.",
        moves: [],
        terminal: true,
        debrief: "The red team's job was not to change the decision but to find the assumption it rested on and make it observable. 'Growth' was a claim about the company that a week of calls could test. Notice how the disconfirming evidence, one departure, was neither fatal nor dismissable; it changed the plan into a conditional one, which is what a plan should be.",
      },
      {
        id: "n5",
        situation: "You take B on the strength of the slogan. Eight months later you are the second manager the founder has managed around.",
        moves: [],
        terminal: true,
        debrief: "Explaining away the only disconfirming evidence is the signature of a decision already made. A red team exists to say the thing you did not want to hear before reality says it.",
      },
    ],
  },
  {
    id: "st-congestion-charge",
    title: "The Congestion Charge",
    mode: "second_order",
    setting: "A mid-sized city's transport committee, deciding whether to introduce a weekday charge to drive into the centre.",
    summary: "The proposal: a daily charge for cars entering the central zone, 07:00–18:00, with revenue ringfenced for buses. Modelling predicts a 15% drop in central traffic. You chair the committee. The exercise is not whether to do it, but what happens because of what happens.",
    actors: [
      { name: "Committee chair (you)", goals: ["Less congestion", "A scheme that survives the next election"], constraints: ["Political capital", "Enforcement capacity"], leverage: ["Agenda", "Revenue allocation"], fears: ["A visible unintended consequence"], alternatives: ["Phase in", "Exemptions", "Do nothing"] },
      { name: "Central retailers", goals: ["Footfall"], constraints: ["Thin margins"], leverage: ["Chamber of commerce", "Local press"], fears: ["Shoppers going to the out-of-town centre"], alternatives: ["Lobby for exemptions", "Delivery-time changes"] },
      { name: "Residents of the ring just outside the zone", goals: ["Parking", "Quiet streets"], constraints: ["No control"], leverage: ["Votes", "Complaints"], fears: ["Becoming a car park"], alternatives: ["Demand permits"] },
      { name: "Delivery firms", goals: ["Predictable costs"], constraints: ["Must enter the zone"], leverage: ["Price pass-through"], fears: ["Charges without time savings"], alternatives: ["Night deliveries", "Consolidation"] },
    ],
    rootNodeId: "n1",
    difficulty: 5,
    estimatedMinutes: 11,
    subskills: ["strategy.second_order", "strategy.incentives", "strategy.planning", "inference.causal"],
    conceptLinks: ["game-theory", "inflation"],
    origin: "seeded",
    nodes: [
      {
        id: "n1",
        situation: "The charge begins. Central traffic falls 15%, as modelled. What happens because of that?",
        moves: [
          { id: "m1", text: "Drivers who used to pass through the centre now drive around it, and the ring road's traffic rises.", quality: 0.9, consequence: "Yes: the first second-order effect. Ring-road congestion rises about 8%, and residents just outside the zone find their streets used for parking by people walking in. A permit scheme for the ring becomes necessary within months.", reveals: "The charge moves traffic as well as reducing it.", nextNodeId: "n2" },
          { id: "m2", text: "Nothing else; the model captured it.", quality: 0.1, consequence: "Models capture first-order effects and are quiet about the behaviour they change. The ring road disagrees within a fortnight.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n2" },
          { id: "m3", text: "Retail footfall collapses.", quality: 0.4, consequence: "Feared, rarely observed at this scale. Footfall dips slightly, then recovers as buses improve and the centre becomes pleasanter. The retailers' campaign is loud before the evidence arrives.", nextNodeId: "n2" },
        ],
      },
      {
        id: "n2",
        situation: "Ring-road traffic is up; residents want permits; retailers are campaigning; bus revenue is flowing. Then what?",
        moves: [
          { id: "m1", text: "Use the ringfenced revenue visibly and quickly: more buses on the routes that serve the ring, and a permit scheme for residents funded from the same pot.", quality: 0.9, consequence: "Bus frequency rises within six months; residents get permits; the scheme now has constituencies that benefit and would fight to keep it. That is what political survival looks like.", nextNodeId: "n3" },
          { id: "m2", text: "Exempt retailers' customers with a validated-parking scheme.", quality: 0.3, consequence: "The exemption is exploited within weeks, revenue falls, and every other group asks for its own. The charge's logic unravels one exemption at a time.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n5" },
          { id: "m3", text: "Extend the zone to include the ring road.", quality: 0.4, consequence: "It solves the displacement and creates a new ring further out, with a new set of angry residents. Boundaries move problems; they rarely remove them.", nextNodeId: "n4" },
        ],
      },
      {
        id: "n3",
        situation: "The scheme is two years old with better buses, permits, stable retail and a small surplus. What happens because of that?",
        moves: [
          { id: "m1", text: "Property values inside the zone rise, and the people who were priced out are the ones who most needed the cheaper buses.", quality: 0.85, consequence: "The third-order effect: a pleasanter centre is a dearer one. It is not a reason to abandon the scheme, but it is a reason to spend some of the surplus on the routes serving the outer estates. Second-order thinking does not stop at two.", nextNodeId: "n6" },
          { id: "m2", text: "Nothing more; the scheme has settled.", quality: 0.3, consequence: "Systems do not settle; they move to the next equilibrium. The property effect arrives whether you predicted it or not.", nextNodeId: "n6" },
        ],
      },
      {
        id: "n4",
        situation: "The zone has been extended once. Displacement has moved outward. Enforcement costs have risen.",
        moves: [],
        terminal: true,
        debrief: "Extending a boundary treats a systemic effect as a geographic one. The traffic did not go away; it went around, and it will go around again. The durable moves were the ones that changed incentives (bus frequency, permits) rather than lines on a map.",
      },
      {
        id: "n5",
        situation: "Exemptions have multiplied. Revenue is half the forecast. The next council abolishes the charge.",
        moves: [],
        terminal: true,
        debrief: "The first exemption is the most expensive decision in the scenario, because it establishes that the rule is negotiable. Every actor with a grievance then negotiates. What happens because of what happens: an exemption for one group creates a claim for every group.",
      },
      {
        id: "n6",
        situation: "The charge survives two elections, its revenue funds the routes people actually use, and the committee spends its time on the third-order effects.",
        moves: [],
        terminal: true,
        debrief: "Every intervention changes the behaviour of the people it touches, and their new behaviour is the next problem. The chair who asked 'then what?' at each stage kept the scheme alive by building beneficiaries faster than opponents. The model predicted the first effect; the committee had to think through the rest.",
      },
    ],
  },
  {
    id: "st-delayed-shipment",
    title: "The Shipment in the Strait",
    mode: "counterparty",
    setting: "A trading company's office; a container of goods is nineteen days late.",
    summary: "You buy ceramics from a supplier in Izmir and sell them to a retailer in Rotterdam under a contract with a late-delivery penalty. The container, shipped via a feeder to Istanbul and onward through the Suez Canal, is nineteen days late. The supplier blames 'the strait'; the freight forwarder blames 'the canal'; the retailer wants its penalty. Someone is not telling you the whole story.",
    actors: [
      { name: "You (trader)", goals: ["Avoid the penalty or pass it on fairly", "Keep both relationships", "Learn what actually happened"], constraints: ["The retailer's penalty clause is clear", "You are not a shipping expert"], leverage: ["Future orders to the supplier", "Future bookings with the forwarder", "The bill of lading"], fears: ["Paying a penalty for someone else's failure"], alternatives: ["Absorb the penalty", "Claim against the forwarder", "Renegotiate with the retailer"] },
      { name: "Supplier (Izmir)", goals: ["Not be blamed", "Keep the account"], constraints: ["Knows the container left the factory late by four days"], leverage: ["Your dependence on their product"], fears: ["Losing the account", "A claim"], alternatives: ["Blame transit", "Offer a discount"] },
      { name: "Freight forwarder", goals: ["Avoid liability", "Keep the booking"], constraints: ["Knows the feeder missed its connection in Istanbul and the box waited nine days for the next sailing"], leverage: ["Controls the documents"], fears: ["A claim under the contract of carriage"], alternatives: ["Blame the canal", "Offer a credit"] },
      { name: "Retailer (Rotterdam)", goals: ["Stock for the season", "The penalty if it is owed"], constraints: ["Its own customers"], leverage: ["The contract"], fears: ["Empty shelves"], alternatives: ["Waive the penalty for a discount", "Enforce"] },
    ],
    rootNodeId: "n1",
    difficulty: 6,
    estimatedMinutes: 13,
    subskills: ["strategy.adversarial", "strategy.incentives", "social.incentive_recognition", "inference.evidence_weighting", "strategy.negotiation", "synthesis.transfer"],
    conceptLinks: ["suez-canal", "bosporus", "containerization", "istanbul"],
    origin: "seeded",
    nodes: [
      {
        id: "n1",
        situation: "Three explanations on the table: 'the strait', 'the canal', and, from the retailer, 'you'. Nineteen days. What is your first move?",
        moves: [
          { id: "m1", text: "Accept the forwarder's account (the canal) and tell the retailer it was force majeure.", quality: 0.2, consequence: "The retailer's lawyer asks for evidence of a canal delay affecting this vessel. The canal's public transit data show no disruption in the relevant week. You have repeated someone else's story as your own.", errorType: "ASSUMPTION", nextNodeId: "n4" },
          { id: "m2", text: "Reconstruct the timeline from documents: factory dispatch date, bill of lading date, feeder sailing, Istanbul transhipment, mother-vessel sailing, canal transit, arrival.", quality: 0.95, consequence: "The documents tell a different story from either party. The factory released the goods four days late. The feeder then missed its connection in Istanbul and the box sat nine days waiting for the next mother vessel. Canal transit was routine, as it is for most of the roughly fifty ships a day. Six further days were ordinary sailing.", reveals: "Four days: supplier. Nine days: forwarder's missed transhipment at Istanbul. Canal: normal. The delay was in the port, not the strait or the canal.", nextNodeId: "n2" },
          { id: "m3", text: "Ask the supplier and forwarder each to explain, in writing, what happened.", quality: 0.55, consequence: "Each writes a careful account that blames the other or the geography. Written accounts from interested parties are evidence about the parties, not the events.", nextNodeId: "n3" },
          { id: "m4", text: "Pay the penalty to keep the retailer happy and move on.", quality: 0.3, consequence: "Relationship preserved, at your cost, and nothing learned. The same thing happens on the next shipment because nobody's incentives changed.", errorType: "STRATEGIC_SHORTSIGHTEDNESS", nextNodeId: "n4" },
        ],
      },
      {
        id: "n2",
        situation: "You know where the nineteen days went: four with the supplier, nine at Istanbul transhipment, six ordinary. The penalty is due in a week.",
        moves: [
          { id: "m1", text: "Go to each party with the document showing their share: ask the supplier for a credit for four days, claim nine days against the forwarder's contract of carriage, and offer the retailer a partial discount in place of the penalty, with the timeline attached.", quality: 0.95, consequence: "The supplier, faced with its own dispatch note, offers a 5% credit. The forwarder, faced with the transhipment record, offers a freight credit rather than fight a claim. The retailer, seeing you have done the work, waives half the penalty. Nobody is happy and nobody is angry; the costs land where the delays were.", nextNodeId: "n5" },
          { id: "m2", text: "Claim the full nineteen days against the forwarder, since they controlled the box longest.", quality: 0.45, consequence: "They counter with the supplier's four late days and the ordinary transit time, and you settle for less than a precise claim would have won. Precision is leverage.", nextNodeId: "n5" },
          { id: "m3", text: "Tell the retailer the truth about the transhipment and ask them to waive the penalty out of goodwill.", quality: 0.5, consequence: "They waive part of it, and note that your forwarder is unreliable. You have absorbed a cost that the documents would have let you allocate.", nextNodeId: "n5" },
        ],
      },
      {
        id: "n3",
        situation: "Two written accounts, each blaming the other. The retailer's deadline is five days away.",
        moves: [
          { id: "m1", text: "Stop asking for accounts and pull the dates from the shipping documents.", quality: 0.85, consequence: "The documents settle it: a late release, a missed Istanbul connection, a routine canal transit. You go to each party with their share.", reveals: "The delay was at Istanbul transhipment, not in the strait or the canal.", nextNodeId: "n2" },
          { id: "m2", text: "Split the penalty three ways as a gesture.", quality: 0.3, consequence: "Fair-sounding, and wrong: it charges the party that caused four days the same as the party that caused nine, and charges you for days that were nobody's fault. Splitting is what people do instead of finding out.", errorType: "PREMATURE_CLOSURE", nextNodeId: "n4" },
        ],
      },
      {
        id: "n4",
        situation: "The penalty is paid, or split, on the basis of stories rather than documents. The next shipment goes the same route with the same forwarder.",
        moves: [],
        terminal: true,
        debrief: "Both counterparties told a story that pointed at geography, because geography cannot be sued. The Bosporus and the Suez Canal are famous enough to sound like causes. The documents showed the delay was a missed connection in port, which is where most container delays happen. The lesson transfers: when interested parties agree on a blameless cause, check the timeline before you accept it.",
      },
      {
        id: "n5",
        situation: "Costs allocated by the documents: a supplier credit, a forwarder credit, a reduced penalty, and a route review before the next season.",
        moves: [],
        terminal: true,
        debrief: "Reconstructing the timeline from documents beat every account offered by an interested party. Knowing what the Suez Canal and the Bosporus actually are, busy, routine corridors rather than mysterious hazards, made the geographic stories suspicious from the start. That is knowledge transferring into strategy: a fact from the Archive changed which explanation you believed.",
      },
    ],
  },
];
